Backend: Vivado
ClockPeriod: 5
HLSConfig:
  Model:
    Precision: ap_fixed<16,8>
    ReuseFactor: 1
    Strategy: Latency
IOType: io_parallel
KerasModel: !keras_model 'L1B_v9/keras_model.h5'
OutputDir: L1B_v9
ProjectName: myproject
Stamp: 045bFe3e
XilinxPart: xcvu9p-flgb2104-2-i
