// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module dense_latency_ap_fixed_ap_fixed_config10_0_0 (
        ap_ready,
        data_0_V_read,
        data_1_V_read,
        data_2_V_read,
        data_3_V_read,
        data_4_V_read,
        data_5_V_read,
        data_6_V_read,
        data_7_V_read,
        data_8_V_read,
        data_9_V_read,
        ap_return
);


output   ap_ready;
input  [15:0] data_0_V_read;
input  [15:0] data_1_V_read;
input  [15:0] data_2_V_read;
input  [15:0] data_3_V_read;
input  [15:0] data_4_V_read;
input  [15:0] data_5_V_read;
input  [15:0] data_6_V_read;
input  [15:0] data_7_V_read;
input  [15:0] data_8_V_read;
input  [15:0] data_9_V_read;
output  [15:0] ap_return;

wire  signed [15:0] mul_ln1118_fu_162_p0;
wire  signed [15:0] mul_ln1118_3_fu_164_p0;
wire  signed [15:0] mul_ln1118_2_fu_167_p0;
wire  signed [15:0] mul_ln1118_4_fu_168_p0;
wire  signed [15:0] mul_ln1118_1_fu_171_p0;
wire   [22:0] shl_ln_fu_408_p3;
wire  signed [23:0] sext_ln1118_fu_416_p1;
wire   [20:0] shl_ln1118_s_fu_426_p3;
wire   [23:0] sub_ln1118_fu_420_p2;
wire  signed [23:0] sext_ln1118_1_fu_434_p1;
wire   [23:0] sub_ln1118_1_fu_438_p2;
wire   [23:0] mul_ln1118_fu_162_p2;
wire   [22:0] mul_ln1118_1_fu_171_p2;
wire   [14:0] trunc_ln708_s_fu_474_p4;
wire   [21:0] shl_ln1118_1_fu_488_p3;
wire  signed [22:0] sext_ln1118_4_fu_496_p1;
wire   [16:0] shl_ln1118_2_fu_506_p3;
wire   [22:0] sub_ln1118_2_fu_500_p2;
wire  signed [22:0] sext_ln1118_5_fu_514_p1;
wire   [22:0] sub_ln1118_3_fu_518_p2;
wire   [14:0] trunc_ln708_2_fu_524_p4;
wire   [23:0] mul_ln1118_2_fu_167_p2;
wire  signed [15:0] sext_ln1118_7_fu_553_p0;
wire  signed [15:0] shl_ln1118_3_fu_557_p1;
wire   [22:0] shl_ln1118_3_fu_557_p3;
wire  signed [23:0] sext_ln1118_8_fu_565_p1;
wire   [23:0] sub_ln1118_4_fu_569_p2;
wire  signed [23:0] sext_ln1118_7_fu_553_p1;
wire   [23:0] sub_ln1118_5_fu_575_p2;
wire   [23:0] mul_ln1118_3_fu_164_p2;
wire   [23:0] mul_ln1118_4_fu_168_p2;
wire   [21:0] shl_ln1118_4_fu_621_p3;
wire   [18:0] shl_ln1118_5_fu_633_p3;
wire  signed [22:0] sext_ln1118_12_fu_641_p1;
wire  signed [22:0] sext_ln1118_11_fu_629_p1;
wire   [22:0] sub_ln1118_6_fu_645_p2;
wire   [14:0] trunc_ln708_3_fu_651_p4;
wire   [20:0] shl_ln1118_6_fu_665_p3;
wire   [17:0] shl_ln1118_7_fu_677_p3;
wire  signed [21:0] sext_ln1118_14_fu_685_p1;
wire  signed [21:0] sext_ln1118_13_fu_673_p1;
wire   [21:0] sub_ln1118_7_fu_689_p2;
wire   [13:0] tmp_4_fu_695_p4;
wire   [15:0] trunc_ln_fu_444_p4;
wire   [15:0] trunc_ln708_1_fu_459_p4;
wire  signed [15:0] sext_ln708_1_fu_534_p1;
wire   [15:0] trunc_ln708_4_fu_543_p4;
wire   [15:0] add_ln703_1_fu_715_p2;
wire  signed [15:0] sext_ln708_fu_484_p1;
wire   [15:0] add_ln703_2_fu_721_p2;
wire   [15:0] add_ln703_fu_709_p2;
wire   [15:0] trunc_ln708_6_fu_596_p4;
wire   [15:0] trunc_ln708_7_fu_611_p4;
wire   [15:0] add_ln703_4_fu_733_p2;
wire   [15:0] trunc_ln708_5_fu_581_p4;
wire  signed [14:0] sext_ln101_fu_705_p1;
wire   [14:0] add_ln703_6_fu_745_p2;
wire  signed [15:0] sext_ln703_fu_751_p1;
wire  signed [15:0] sext_ln708_2_fu_661_p1;
wire   [15:0] add_ln703_7_fu_755_p2;
wire   [15:0] add_ln703_5_fu_739_p2;
wire   [15:0] add_ln703_8_fu_761_p2;
wire   [15:0] add_ln703_3_fu_727_p2;

assign add_ln703_1_fu_715_p2 = ($signed(sext_ln708_1_fu_534_p1) + $signed(trunc_ln708_4_fu_543_p4));

assign add_ln703_2_fu_721_p2 = ($signed(add_ln703_1_fu_715_p2) + $signed(sext_ln708_fu_484_p1));

assign add_ln703_3_fu_727_p2 = (add_ln703_2_fu_721_p2 + add_ln703_fu_709_p2);

assign add_ln703_4_fu_733_p2 = (trunc_ln708_6_fu_596_p4 + trunc_ln708_7_fu_611_p4);

assign add_ln703_5_fu_739_p2 = (add_ln703_4_fu_733_p2 + trunc_ln708_5_fu_581_p4);

assign add_ln703_6_fu_745_p2 = ($signed(sext_ln101_fu_705_p1) + $signed(15'd20));

assign add_ln703_7_fu_755_p2 = ($signed(sext_ln703_fu_751_p1) + $signed(sext_ln708_2_fu_661_p1));

assign add_ln703_8_fu_761_p2 = (add_ln703_7_fu_755_p2 + add_ln703_5_fu_739_p2);

assign add_ln703_fu_709_p2 = (trunc_ln_fu_444_p4 + trunc_ln708_1_fu_459_p4);

assign ap_ready = 1'b1;

assign ap_return = (add_ln703_8_fu_761_p2 + add_ln703_3_fu_727_p2);

assign mul_ln1118_1_fu_171_p0 = data_2_V_read;

assign mul_ln1118_1_fu_171_p2 = ($signed(mul_ln1118_1_fu_171_p0) * $signed(-'h34));

assign mul_ln1118_2_fu_167_p0 = data_4_V_read;

assign mul_ln1118_2_fu_167_p2 = ($signed(mul_ln1118_2_fu_167_p0) * $signed(-'hC2));

assign mul_ln1118_3_fu_164_p0 = data_6_V_read;

assign mul_ln1118_3_fu_164_p2 = ($signed(mul_ln1118_3_fu_164_p0) * $signed('hA7));

assign mul_ln1118_4_fu_168_p0 = data_7_V_read;

assign mul_ln1118_4_fu_168_p2 = ($signed(mul_ln1118_4_fu_168_p0) * $signed('hEB));

assign mul_ln1118_fu_162_p0 = data_1_V_read;

assign mul_ln1118_fu_162_p2 = ($signed(mul_ln1118_fu_162_p0) * $signed('h47));

assign sext_ln101_fu_705_p1 = $signed(tmp_4_fu_695_p4);

assign sext_ln1118_11_fu_629_p1 = $signed(shl_ln1118_4_fu_621_p3);

assign sext_ln1118_12_fu_641_p1 = $signed(shl_ln1118_5_fu_633_p3);

assign sext_ln1118_13_fu_673_p1 = $signed(shl_ln1118_6_fu_665_p3);

assign sext_ln1118_14_fu_685_p1 = $signed(shl_ln1118_7_fu_677_p3);

assign sext_ln1118_1_fu_434_p1 = $signed(shl_ln1118_s_fu_426_p3);

assign sext_ln1118_4_fu_496_p1 = $signed(shl_ln1118_1_fu_488_p3);

assign sext_ln1118_5_fu_514_p1 = $signed(shl_ln1118_2_fu_506_p3);

assign sext_ln1118_7_fu_553_p0 = data_5_V_read;

assign sext_ln1118_7_fu_553_p1 = sext_ln1118_7_fu_553_p0;

assign sext_ln1118_8_fu_565_p1 = $signed(shl_ln1118_3_fu_557_p3);

assign sext_ln1118_fu_416_p1 = $signed(shl_ln_fu_408_p3);

assign sext_ln703_fu_751_p1 = $signed(add_ln703_6_fu_745_p2);

assign sext_ln708_1_fu_534_p1 = $signed(trunc_ln708_2_fu_524_p4);

assign sext_ln708_2_fu_661_p1 = $signed(trunc_ln708_3_fu_651_p4);

assign sext_ln708_fu_484_p1 = $signed(trunc_ln708_s_fu_474_p4);

assign shl_ln1118_1_fu_488_p3 = {{data_3_V_read}, {6'd0}};

assign shl_ln1118_2_fu_506_p3 = {{data_3_V_read}, {1'd0}};

assign shl_ln1118_3_fu_557_p1 = data_5_V_read;

assign shl_ln1118_3_fu_557_p3 = {{shl_ln1118_3_fu_557_p1}, {7'd0}};

assign shl_ln1118_4_fu_621_p3 = {{data_8_V_read}, {6'd0}};

assign shl_ln1118_5_fu_633_p3 = {{data_8_V_read}, {3'd0}};

assign shl_ln1118_6_fu_665_p3 = {{data_9_V_read}, {5'd0}};

assign shl_ln1118_7_fu_677_p3 = {{data_9_V_read}, {2'd0}};

assign shl_ln1118_s_fu_426_p3 = {{data_0_V_read}, {5'd0}};

assign shl_ln_fu_408_p3 = {{data_0_V_read}, {7'd0}};

assign sub_ln1118_1_fu_438_p2 = ($signed(sub_ln1118_fu_420_p2) - $signed(sext_ln1118_1_fu_434_p1));

assign sub_ln1118_2_fu_500_p2 = ($signed(23'd0) - $signed(sext_ln1118_4_fu_496_p1));

assign sub_ln1118_3_fu_518_p2 = ($signed(sub_ln1118_2_fu_500_p2) - $signed(sext_ln1118_5_fu_514_p1));

assign sub_ln1118_4_fu_569_p2 = ($signed(24'd0) - $signed(sext_ln1118_8_fu_565_p1));

assign sub_ln1118_5_fu_575_p2 = ($signed(sub_ln1118_4_fu_569_p2) - $signed(sext_ln1118_7_fu_553_p1));

assign sub_ln1118_6_fu_645_p2 = ($signed(sext_ln1118_12_fu_641_p1) - $signed(sext_ln1118_11_fu_629_p1));

assign sub_ln1118_7_fu_689_p2 = ($signed(sext_ln1118_14_fu_685_p1) - $signed(sext_ln1118_13_fu_673_p1));

assign sub_ln1118_fu_420_p2 = ($signed(24'd0) - $signed(sext_ln1118_fu_416_p1));

assign tmp_4_fu_695_p4 = {{sub_ln1118_7_fu_689_p2[21:8]}};

assign trunc_ln708_1_fu_459_p4 = {{mul_ln1118_fu_162_p2[23:8]}};

assign trunc_ln708_2_fu_524_p4 = {{sub_ln1118_3_fu_518_p2[22:8]}};

assign trunc_ln708_3_fu_651_p4 = {{sub_ln1118_6_fu_645_p2[22:8]}};

assign trunc_ln708_4_fu_543_p4 = {{mul_ln1118_2_fu_167_p2[23:8]}};

assign trunc_ln708_5_fu_581_p4 = {{sub_ln1118_5_fu_575_p2[23:8]}};

assign trunc_ln708_6_fu_596_p4 = {{mul_ln1118_3_fu_164_p2[23:8]}};

assign trunc_ln708_7_fu_611_p4 = {{mul_ln1118_4_fu_168_p2[23:8]}};

assign trunc_ln708_s_fu_474_p4 = {{mul_ln1118_1_fu_171_p2[22:8]}};

assign trunc_ln_fu_444_p4 = {{sub_ln1118_1_fu_438_p2[23:8]}};

endmodule //dense_latency_ap_fixed_ap_fixed_config10_0_0
