// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module pointwise_conv_1d_cl_0_0_0_0_0_0 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        ap_ce,
        data_0_V_read,
        data_1_V_read,
        data_2_V_read,
        data_3_V_read,
        data_4_V_read,
        data_5_V_read,
        data_6_V_read,
        data_7_V_read,
        data_8_V_read,
        data_9_V_read,
        data_10_V_read,
        data_11_V_read,
        data_12_V_read,
        data_13_V_read,
        data_14_V_read,
        data_15_V_read,
        data_16_V_read,
        data_17_V_read,
        data_18_V_read,
        data_19_V_read,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_return_4,
        ap_return_5,
        ap_return_6,
        ap_return_7,
        ap_return_8,
        ap_return_9
);

parameter    ap_ST_fsm_pp0_stage0 = 2'd1;
parameter    ap_ST_fsm_pp0_stage1 = 2'd2;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   ap_ce;
input  [15:0] data_0_V_read;
input  [15:0] data_1_V_read;
input  [15:0] data_2_V_read;
input  [15:0] data_3_V_read;
input  [15:0] data_4_V_read;
input  [15:0] data_5_V_read;
input  [15:0] data_6_V_read;
input  [15:0] data_7_V_read;
input  [15:0] data_8_V_read;
input  [15:0] data_9_V_read;
input  [15:0] data_10_V_read;
input  [15:0] data_11_V_read;
input  [15:0] data_12_V_read;
input  [15:0] data_13_V_read;
input  [15:0] data_14_V_read;
input  [15:0] data_15_V_read;
input  [15:0] data_16_V_read;
input  [15:0] data_17_V_read;
input  [15:0] data_18_V_read;
input  [15:0] data_19_V_read;
output  [15:0] ap_return_0;
output  [15:0] ap_return_1;
output  [15:0] ap_return_2;
output  [15:0] ap_return_3;
output  [15:0] ap_return_4;
output  [15:0] ap_return_5;
output  [15:0] ap_return_6;
output  [15:0] ap_return_7;
output  [15:0] ap_return_8;
output  [15:0] ap_return_9;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [1:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
wire    ap_block_pp0_stage0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_state2_pp0_stage1_iter0;
wire    ap_block_pp0_stage1_11001;
reg   [15:0] reg_12129;
reg    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state3_pp0_stage0_iter1;
reg    ap_block_pp0_stage0_11001;
reg   [15:0] reg_12133;
reg   [15:0] reg_12137;
reg   [15:0] reg_12141;
reg   [15:0] reg_12145;
reg   [15:0] reg_12149;
reg   [15:0] reg_12153;
reg   [15:0] reg_12157;
reg   [15:0] reg_12161;
reg   [15:0] reg_12165;
reg   [15:0] reg_12169;
reg   [15:0] reg_12173;
reg   [15:0] reg_12177;
reg   [15:0] reg_12181;
reg   [15:0] reg_12185;
reg   [15:0] reg_12189;
reg  signed [15:0] data_19_V_read_3_reg_14480;
reg  signed [15:0] data_16_V_read_3_reg_14487;
reg  signed [15:0] data_14_V_read_3_reg_14493;
reg  signed [15:0] data_13_V_read_3_reg_14500;
reg  signed [15:0] data_10_V_read11_reg_14507;
reg  signed [15:0] data_7_V_read_5_reg_14517;
reg  signed [15:0] data_4_V_read_5_reg_14525;
reg  signed [15:0] data_3_V_read_4_reg_14533;
reg  signed [15:0] data_0_V_read_5_reg_14538;
wire  signed [23:0] sext_ln1118_1_fu_12193_p1;
reg  signed [23:0] sext_ln1118_1_reg_14545;
reg   [15:0] mult_0_V_reg_14551;
wire  signed [23:0] sext_ln1118_2_fu_12208_p1;
reg  signed [23:0] sext_ln1118_2_reg_14556;
wire  signed [23:0] sext_ln1118_3_fu_12213_p1;
reg  signed [23:0] sext_ln1118_3_reg_14563;
reg   [15:0] mult_2_V_reg_14569;
wire  signed [23:0] sext_ln1118_5_fu_12229_p1;
reg  signed [23:0] sext_ln1118_5_reg_14574;
reg   [12:0] trunc_ln_reg_14579;
reg   [14:0] trunc_ln708_1_reg_14584;
wire  signed [23:0] sext_ln1118_10_fu_12294_p1;
reg  signed [23:0] sext_ln1118_10_reg_14589;
reg   [15:0] mult_5_V_reg_14594;
wire  signed [23:0] sext_ln1118_12_fu_12316_p1;
reg  signed [23:0] sext_ln1118_12_reg_14599;
wire  signed [23:0] sext_ln1118_13_fu_12322_p1;
reg  signed [23:0] sext_ln1118_13_reg_14605;
reg   [15:0] mult_8_V_reg_14610;
reg   [14:0] trunc_ln708_6_reg_14615;
wire  signed [23:0] sext_ln1118_24_fu_12377_p1;
reg  signed [23:0] sext_ln1118_24_reg_14620;
reg   [12:0] trunc_ln708_8_reg_14625;
reg   [15:0] mult_12_V_reg_14630;
wire  signed [23:0] sext_ln1118_28_fu_12442_p1;
reg  signed [23:0] sext_ln1118_28_reg_14635;
reg   [15:0] mult_14_V_reg_14641;
reg   [14:0] trunc_ln708_2_reg_14646;
reg   [14:0] trunc_ln708_3_reg_14651;
wire  signed [23:0] sext_ln1118_36_fu_12521_p1;
reg  signed [23:0] sext_ln1118_36_reg_14656;
wire  signed [23:0] sext_ln1118_38_fu_12536_p1;
reg  signed [23:0] sext_ln1118_38_reg_14661;
reg   [15:0] mult_19_V_reg_14668;
reg   [13:0] tmp_4_reg_14673;
reg   [15:0] mult_22_V_reg_14678;
reg   [15:0] mult_23_V_reg_14683;
reg   [15:0] mult_25_V_reg_14688;
reg   [14:0] trunc_ln708_9_reg_14693;
reg   [12:0] trunc_ln708_10_reg_14698;
reg   [15:0] mult_32_V_reg_14703;
reg   [15:0] mult_35_V_reg_14708;
reg   [15:0] mult_37_V_reg_14713;
reg   [11:0] trunc_ln708_12_reg_14718;
reg   [15:0] mult_45_V_reg_14723;
reg   [12:0] trunc_ln708_14_reg_14728;
reg   [15:0] mult_52_V_reg_14733;
reg   [15:0] mult_55_V_reg_14738;
reg   [15:0] mult_56_V_reg_14743;
reg   [15:0] mult_57_V_reg_14748;
reg   [15:0] mult_66_V_reg_14753;
reg   [15:0] mult_68_V_reg_14758;
reg   [15:0] mult_69_V_reg_14763;
reg   [13:0] trunc_ln708_20_reg_14768;
reg   [15:0] mult_72_V_reg_14773;
reg   [15:0] mult_75_V_reg_14778;
reg   [15:0] mult_78_V_reg_14783;
reg   [12:0] trunc_ln708_22_reg_14788;
reg   [15:0] mult_88_V_reg_14793;
reg   [15:0] mult_89_V_reg_14798;
reg   [15:0] mult_95_V_reg_14803;
reg   [15:0] mult_96_V_reg_14808;
reg   [15:0] mult_97_V_reg_14813;
reg   [15:0] mult_98_V_reg_14818;
reg   [10:0] tmp_6_reg_14823;
reg   [7:0] tmp_7_reg_14828;
reg   [13:0] tmp_8_reg_14833;
reg   [12:0] tmp_5_reg_14838;
reg   [15:0] mult_41_V_reg_14843;
reg   [14:0] trunc_ln708_13_reg_14848;
reg   [13:0] trunc_ln708_18_reg_14853;
reg   [13:0] trunc_ln708_19_reg_14858;
reg   [15:0] mult_80_V_reg_14863;
reg   [14:0] trunc_ln708_21_reg_14868;
reg   [15:0] mult_84_V_reg_14873;
wire   [15:0] add_ln703_5_fu_13771_p2;
reg   [15:0] add_ln703_5_reg_14878;
wire   [15:0] add_ln703_10_fu_13799_p2;
reg   [15:0] add_ln703_10_reg_14883;
wire   [15:0] add_ln703_15_fu_13827_p2;
reg   [15:0] add_ln703_15_reg_14888;
wire   [15:0] add_ln703_19_fu_13844_p2;
reg   [15:0] add_ln703_19_reg_14893;
wire   [14:0] add_ln703_24_fu_13856_p2;
reg   [14:0] add_ln703_24_reg_14898;
wire   [15:0] add_ln703_27_fu_13871_p2;
reg   [15:0] add_ln703_27_reg_14903;
wire   [15:0] add_ln703_30_fu_13877_p2;
reg   [15:0] add_ln703_30_reg_14908;
wire   [15:0] add_ln703_33_fu_13888_p2;
reg   [15:0] add_ln703_33_reg_14913;
wire   [15:0] add_ln703_35_fu_13894_p2;
reg   [15:0] add_ln703_35_reg_14918;
wire   [15:0] add_ln703_38_fu_13904_p2;
reg   [15:0] add_ln703_38_reg_14923;
wire   [15:0] add_ln703_49_fu_13910_p2;
reg   [15:0] add_ln703_49_reg_14928;
wire   [15:0] add_ln703_53_fu_13915_p2;
reg   [15:0] add_ln703_53_reg_14933;
wire   [15:0] add_ln703_56_fu_13926_p2;
reg   [15:0] add_ln703_56_reg_14938;
wire   [15:0] add_ln703_62_fu_13953_p2;
reg   [15:0] add_ln703_62_reg_14943;
wire   [15:0] add_ln703_75_fu_13959_p2;
reg   [15:0] add_ln703_75_reg_14948;
wire   [15:0] add_ln703_78_fu_13969_p2;
reg   [15:0] add_ln703_78_reg_14953;
wire   [15:0] add_ln703_80_fu_13974_p2;
reg   [15:0] add_ln703_80_reg_14958;
wire   [15:0] add_ln703_83_fu_13984_p2;
reg   [15:0] add_ln703_83_reg_14963;
wire   [15:0] add_ln703_86_fu_13990_p2;
reg   [15:0] add_ln703_86_reg_14968;
wire   [15:0] add_ln703_94_fu_13995_p2;
reg   [15:0] add_ln703_94_reg_14973;
wire   [15:0] add_ln703_98_fu_14001_p2;
reg   [15:0] add_ln703_98_reg_14978;
wire   [15:0] add_ln703_101_fu_14011_p2;
reg   [15:0] add_ln703_101_reg_14983;
wire   [15:0] add_ln703_103_fu_14017_p2;
reg   [15:0] add_ln703_103_reg_14988;
wire   [15:0] add_ln703_106_fu_14026_p2;
reg   [15:0] add_ln703_106_reg_14993;
reg    ap_enable_reg_pp0_iter0_reg;
reg    ap_block_pp0_stage0_subdone;
reg    ap_block_pp0_stage1_subdone;
wire  signed [15:0] mul_ln1118_34_fu_438_p1;
wire  signed [23:0] sext_ln1118_27_fu_12423_p1;
reg  signed [9:0] grp_fu_439_p0;
reg  signed [15:0] grp_fu_439_p1;
wire    ap_block_pp0_stage1;
reg  signed [9:0] grp_fu_440_p0;
reg  signed [15:0] grp_fu_440_p1;
wire  signed [23:0] sext_ln1118_9_fu_12279_p1;
wire  signed [15:0] mul_ln1118_13_fu_441_p1;
wire  signed [15:0] mul_ln1118_63_fu_442_p1;
wire  signed [23:0] sext_ln1118_17_fu_12345_p1;
wire  signed [15:0] mul_ln1118_67_fu_443_p1;
wire  signed [23:0] sext_ln1118_32_fu_12463_p1;
wire  signed [15:0] mul_ln1118_16_fu_444_p1;
wire  signed [15:0] mul_ln1118_69_fu_445_p1;
wire  signed [23:0] sext_ln1118_37_fu_12528_p1;
reg  signed [9:0] grp_fu_446_p0;
reg  signed [15:0] grp_fu_446_p1;
wire  signed [15:0] mul_ln1118_48_fu_447_p1;
reg   [8:0] grp_fu_448_p0;
reg  signed [15:0] grp_fu_448_p1;
wire  signed [22:0] sext_ln1118_18_fu_12351_p1;
wire  signed [15:0] mul_ln1118_54_fu_449_p1;
reg  signed [7:0] grp_fu_450_p0;
reg  signed [15:0] grp_fu_450_p1;
wire  signed [22:0] sext_ln1118_8_fu_12274_p1;
wire  signed [21:0] sext_ln1118_fu_13051_p1;
wire  signed [15:0] mul_ln1118_fu_451_p1;
reg  signed [9:0] grp_fu_452_p0;
reg  signed [15:0] grp_fu_452_p1;
reg  signed [9:0] grp_fu_453_p0;
reg  signed [15:0] grp_fu_453_p1;
wire  signed [15:0] mul_ln1118_36_fu_454_p1;
wire  signed [23:0] sext_ln1118_35_fu_12504_p1;
reg  signed [9:0] grp_fu_455_p0;
reg  signed [15:0] grp_fu_455_p1;
wire  signed [22:0] sext_ln1118_4_fu_13055_p1;
wire  signed [15:0] mul_ln1118_4_fu_456_p1;
wire  signed [15:0] mul_ln1118_24_fu_457_p1;
reg  signed [7:0] grp_fu_458_p0;
reg  signed [15:0] grp_fu_458_p1;
wire  signed [23:0] sext_ln1118_16_fu_12327_p1;
reg  signed [7:0] grp_fu_459_p0;
reg  signed [15:0] grp_fu_459_p1;
wire  signed [15:0] mul_ln1118_19_fu_460_p1;
reg  signed [15:0] grp_fu_461_p1;
reg  signed [8:0] grp_fu_462_p0;
reg  signed [15:0] grp_fu_462_p1;
wire  signed [15:0] mul_ln1118_45_fu_463_p1;
reg   [7:0] grp_fu_464_p0;
reg  signed [15:0] grp_fu_464_p1;
reg  signed [9:0] grp_fu_465_p0;
reg  signed [15:0] grp_fu_465_p1;
wire  signed [15:0] mul_ln1118_2_fu_466_p1;
reg  signed [8:0] grp_fu_467_p0;
reg  signed [15:0] grp_fu_467_p1;
reg  signed [15:0] grp_fu_468_p1;
wire  signed [15:0] mul_ln1118_49_fu_469_p1;
wire  signed [15:0] mul_ln1118_6_fu_470_p1;
wire  signed [15:0] mul_ln1118_51_fu_471_p1;
wire  signed [15:0] mul_ln1118_20_fu_472_p1;
reg  signed [9:0] grp_fu_473_p0;
reg  signed [15:0] grp_fu_473_p1;
wire  signed [15:0] mul_ln1118_14_fu_474_p1;
wire  signed [15:0] mul_ln1118_15_fu_475_p1;
wire  signed [15:0] mul_ln1118_35_fu_476_p1;
reg  signed [10:0] grp_fu_477_p0;
reg  signed [15:0] grp_fu_477_p1;
wire  signed [22:0] sext_ln1118_34_fu_12499_p1;
wire  signed [15:0] mul_ln1118_56_fu_478_p1;
wire  signed [15:0] mul_ln1118_9_fu_479_p1;
wire  signed [23:0] sext_ln1118_31_fu_12447_p1;
wire  signed [15:0] mul_ln1118_37_fu_480_p1;
wire  signed [15:0] mul_ln1118_68_fu_481_p1;
wire  signed [15:0] mul_ln1118_61_fu_482_p1;
wire  signed [15:0] mul_ln1118_8_fu_483_p1;
reg  signed [8:0] grp_fu_484_p0;
reg  signed [15:0] grp_fu_484_p1;
reg   [8:0] grp_fu_485_p0;
reg  signed [15:0] grp_fu_485_p1;
reg   [7:0] grp_fu_486_p0;
reg  signed [15:0] grp_fu_486_p1;
wire  signed [15:0] mul_ln1118_47_fu_487_p1;
wire   [23:0] grp_fu_452_p2;
wire   [23:0] grp_fu_461_p2;
wire   [23:0] grp_fu_462_p2;
wire   [23:0] grp_fu_446_p2;
wire   [23:0] grp_fu_458_p2;
wire   [23:0] grp_fu_473_p2;
wire   [23:0] grp_fu_468_p2;
wire   [23:0] grp_fu_440_p2;
wire   [23:0] grp_fu_486_p2;
wire   [23:0] grp_fu_453_p2;
wire   [23:0] grp_fu_484_p2;
wire   [23:0] grp_fu_467_p2;
wire   [23:0] grp_fu_485_p2;
wire   [23:0] grp_fu_439_p2;
wire   [23:0] grp_fu_464_p2;
wire   [23:0] grp_fu_465_p2;
wire  signed [15:0] sext_ln1118_1_fu_12193_p0;
wire   [23:0] mul_ln1118_fu_451_p2;
wire  signed [15:0] sext_ln1118_2_fu_12208_p0;
wire  signed [15:0] sext_ln1118_3_fu_12213_p0;
wire   [23:0] mul_ln1118_2_fu_466_p2;
wire  signed [15:0] sext_ln1118_5_fu_12229_p0;
wire  signed [15:0] shl_ln_fu_12234_p1;
wire   [19:0] shl_ln_fu_12234_p3;
wire  signed [15:0] shl_ln1118_1_fu_12246_p1;
wire   [17:0] shl_ln1118_1_fu_12246_p3;
wire  signed [20:0] sext_ln1118_7_fu_12254_p1;
wire  signed [20:0] sext_ln1118_6_fu_12242_p1;
wire   [20:0] add_ln1118_fu_12258_p2;
wire  signed [15:0] sext_ln1118_8_fu_12274_p0;
wire  signed [15:0] sext_ln1118_9_fu_12279_p0;
wire   [22:0] grp_fu_450_p2;
wire  signed [15:0] sext_ln1118_10_fu_12294_p0;
wire   [23:0] mul_ln1118_4_fu_456_p2;
wire  signed [15:0] sext_ln1118_11_fu_12311_p0;
wire  signed [15:0] sext_ln1118_12_fu_12316_p0;
wire  signed [15:0] sext_ln1118_13_fu_12322_p0;
wire  signed [15:0] sext_ln1118_16_fu_12327_p0;
wire   [23:0] mul_ln1118_6_fu_470_p2;
wire  signed [15:0] sext_ln1118_17_fu_12345_p0;
wire  signed [15:0] sext_ln1118_18_fu_12351_p0;
wire   [22:0] trunc_ln708_6_fu_12357_p1;
wire   [23:0] grp_fu_448_p2;
wire  signed [15:0] sext_ln1118_20_fu_12367_p0;
wire  signed [15:0] sext_ln1118_22_fu_12372_p0;
wire  signed [15:0] sext_ln1118_24_fu_12377_p0;
wire  signed [15:0] shl_ln1118_4_fu_12383_p1;
wire   [19:0] shl_ln1118_4_fu_12383_p3;
wire  signed [15:0] shl_ln1118_5_fu_12395_p1;
wire   [16:0] shl_ln1118_5_fu_12395_p3;
wire  signed [20:0] sext_ln1118_26_fu_12403_p1;
wire  signed [20:0] sext_ln1118_25_fu_12391_p1;
wire   [20:0] add_ln1118_2_fu_12407_p2;
wire   [23:0] mul_ln1118_8_fu_483_p2;
wire  signed [15:0] sext_ln1118_28_fu_12442_p0;
wire  signed [15:0] sext_ln1118_31_fu_12447_p0;
wire   [23:0] mul_ln1118_9_fu_479_p2;
wire  signed [15:0] sext_ln1118_32_fu_12463_p0;
wire  signed [15:0] shl_ln1118_8_fu_12471_p1;
wire   [21:0] shl_ln1118_8_fu_12471_p3;
wire  signed [22:0] sext_ln1118_33_fu_12479_p1;
wire   [22:0] sub_ln1118_1_fu_12483_p2;
wire  signed [15:0] sext_ln1118_34_fu_12499_p0;
wire  signed [15:0] sext_ln1118_35_fu_12504_p0;
wire   [22:0] trunc_ln708_3_fu_12511_p1;
wire   [23:0] grp_fu_477_p2;
wire  signed [15:0] sext_ln1118_36_fu_12521_p0;
wire  signed [15:0] sext_ln1118_37_fu_12528_p0;
wire  signed [15:0] sext_ln1118_38_fu_12536_p0;
wire   [23:0] mul_ln1118_13_fu_441_p2;
wire  signed [15:0] shl_ln1118_10_fu_12551_p1;
wire   [20:0] shl_ln1118_10_fu_12551_p3;
wire  signed [15:0] shl_ln1118_11_fu_12563_p1;
wire   [18:0] shl_ln1118_11_fu_12563_p3;
wire  signed [21:0] sext_ln1118_42_fu_12571_p1;
wire  signed [21:0] sext_ln1118_41_fu_12559_p1;
wire   [21:0] add_ln1118_4_fu_12575_p2;
wire   [23:0] mul_ln1118_14_fu_474_p2;
wire   [23:0] mul_ln1118_15_fu_475_p2;
wire   [23:0] mul_ln1118_16_fu_444_p2;
wire   [22:0] mul_ln1118_19_fu_460_p2;
wire   [20:0] mul_ln1118_20_fu_472_p2;
wire   [23:0] grp_fu_455_p2;
wire   [23:0] mul_ln1118_24_fu_457_p2;
wire   [23:0] grp_fu_459_p2;
wire  signed [15:0] shl_ln1118_15_fu_12671_p1;
wire   [18:0] shl_ln1118_15_fu_12671_p3;
wire  signed [15:0] shl_ln1118_16_fu_12683_p1;
wire   [16:0] shl_ln1118_16_fu_12683_p3;
wire  signed [19:0] sext_ln1118_47_fu_12691_p1;
wire  signed [19:0] sext_ln1118_46_fu_12679_p1;
wire   [19:0] add_ln1118_5_fu_12695_p2;
wire  signed [15:0] trunc_ln1118_fu_12711_p0;
wire   [14:0] trunc_ln1118_fu_12711_p1;
wire   [23:0] shl_ln1118_19_fu_12715_p3;
wire  signed [15:0] shl_ln1118_20_fu_12729_p1;
wire   [21:0] shl_ln1118_20_fu_12729_p3;
wire   [23:0] sub_ln1118_8_fu_12723_p2;
wire  signed [23:0] sext_ln1118_50_fu_12737_p1;
wire   [23:0] sub_ln1118_9_fu_12741_p2;
wire  signed [15:0] shl_ln1118_23_fu_12757_p1;
wire   [19:0] shl_ln1118_23_fu_12757_p3;
wire  signed [15:0] shl_ln1118_24_fu_12769_p1;
wire   [16:0] shl_ln1118_24_fu_12769_p3;
wire  signed [20:0] sext_ln1118_54_fu_12777_p1;
wire  signed [20:0] sext_ln1118_53_fu_12765_p1;
wire   [20:0] sub_ln1118_10_fu_12781_p2;
wire   [23:0] mul_ln1118_34_fu_438_p2;
wire   [23:0] mul_ln1118_35_fu_476_p2;
wire   [23:0] mul_ln1118_36_fu_454_p2;
wire   [23:0] mul_ln1118_37_fu_480_p2;
wire   [23:0] mul_ln1118_45_fu_463_p2;
wire   [23:0] mul_ln1118_47_fu_487_p2;
wire   [23:0] mul_ln1118_48_fu_447_p2;
wire   [21:0] mul_ln1118_49_fu_469_p2;
wire   [23:0] mul_ln1118_51_fu_471_p2;
wire   [23:0] mul_ln1118_54_fu_449_p2;
wire   [23:0] mul_ln1118_56_fu_478_p2;
wire   [20:0] mul_ln1118_61_fu_482_p2;
wire  signed [15:0] shl_ln1118_33_fu_12917_p1;
wire   [23:0] shl_ln1118_33_fu_12917_p3;
wire   [23:0] sub_ln1118_17_fu_12925_p2;
wire   [23:0] mul_ln1118_63_fu_442_p2;
wire   [23:0] mul_ln1118_67_fu_443_p2;
wire   [23:0] mul_ln1118_68_fu_481_p2;
wire  signed [15:0] trunc_ln1118_1_fu_12971_p0;
wire   [14:0] trunc_ln1118_1_fu_12971_p1;
wire  signed [15:0] shl_ln1118_36_fu_12983_p1;
wire   [19:0] shl_ln1118_36_fu_12983_p3;
wire  signed [23:0] sext_ln1118_62_fu_12991_p1;
wire   [23:0] shl_ln1118_35_fu_12975_p3;
wire   [23:0] sub_ln1118_19_fu_12995_p2;
wire   [23:0] mul_ln1118_69_fu_445_p2;
wire  signed [15:0] tmp_6_fu_13021_p1;
wire  signed [15:0] tmp_7_fu_13031_p1;
wire  signed [15:0] tmp_8_fu_13041_p1;
wire   [21:0] shl_ln1118_2_fu_13069_p3;
wire  signed [22:0] sext_ln1118_15_fu_13076_p1;
wire  signed [22:0] sext_ln1118_14_fu_13066_p1;
wire   [22:0] sub_ln1118_fu_13080_p2;
wire   [14:0] trunc_ln708_4_fu_13086_p4;
wire   [18:0] shl_ln1118_3_fu_13109_p3;
wire  signed [19:0] sext_ln1118_23_fu_13116_p1;
wire  signed [19:0] sext_ln1118_21_fu_13106_p1;
wire   [19:0] add_ln1118_1_fu_13120_p2;
wire   [11:0] trunc_ln708_7_fu_13126_p4;
wire   [21:0] shl_ln1118_6_fu_13143_p3;
wire   [18:0] shl_ln1118_7_fu_13154_p3;
wire  signed [22:0] sext_ln1118_30_fu_13161_p1;
wire  signed [22:0] sext_ln1118_29_fu_13150_p1;
wire   [22:0] add_ln1118_3_fu_13165_p2;
wire   [14:0] trunc_ln708_s_fu_13171_p4;
wire   [18:0] shl_ln1118_9_fu_13191_p3;
wire  signed [19:0] sext_ln1118_39_fu_13198_p1;
wire   [16:0] shl_ln1118_s_fu_13208_p3;
wire   [19:0] sub_ln1118_2_fu_13202_p2;
wire  signed [19:0] sext_ln1118_40_fu_13215_p1;
wire   [19:0] sub_ln1118_3_fu_13219_p2;
wire   [11:0] tmp_fu_13225_p4;
wire   [20:0] shl_ln1118_12_fu_13242_p3;
wire  signed [21:0] sext_ln1118_43_fu_13249_p1;
wire   [21:0] sub_ln1118_4_fu_13253_p2;
wire   [13:0] trunc_ln708_5_fu_13259_p4;
wire   [19:0] shl_ln1118_13_fu_13279_p3;
wire   [16:0] shl_ln1118_14_fu_13290_p3;
wire  signed [20:0] sext_ln1118_44_fu_13286_p1;
wire  signed [20:0] sext_ln1118_45_fu_13297_p1;
wire   [20:0] sub_ln1118_5_fu_13301_p2;
wire   [12:0] trunc_ln708_11_fu_13307_p4;
wire   [19:0] shl_ln1118_17_fu_13324_p3;
wire  signed [20:0] sext_ln1118_48_fu_13331_p1;
wire   [16:0] shl_ln1118_18_fu_13341_p3;
wire   [20:0] sub_ln1118_6_fu_13335_p2;
wire  signed [20:0] sext_ln1118_49_fu_13348_p1;
wire   [20:0] sub_ln1118_7_fu_13352_p2;
wire   [22:0] trunc_ln708_13_fu_13378_p1;
wire   [22:0] shl_ln1118_21_fu_13388_p3;
wire   [19:0] shl_ln1118_22_fu_13399_p3;
wire  signed [23:0] sext_ln1118_52_fu_13406_p1;
wire  signed [23:0] sext_ln1118_51_fu_13395_p1;
wire   [23:0] add_ln1118_6_fu_13410_p2;
wire   [21:0] shl_ln1118_25_fu_13429_p3;
wire   [17:0] shl_ln1118_26_fu_13440_p3;
wire  signed [22:0] sext_ln1118_56_fu_13447_p1;
wire  signed [22:0] sext_ln1118_55_fu_13436_p1;
wire   [22:0] add_ln1118_7_fu_13451_p2;
wire   [14:0] trunc_ln708_15_fu_13457_p4;
wire   [16:0] shl_ln1118_27_fu_13477_p3;
wire   [22:0] sub_ln1118_11_fu_13471_p2;
wire  signed [22:0] sext_ln1118_57_fu_13484_p1;
wire   [22:0] sub_ln1118_12_fu_13488_p2;
wire   [14:0] trunc_ln708_16_fu_13494_p4;
wire   [20:0] sub_ln1118_13_fu_13508_p2;
wire   [12:0] trunc_ln708_17_fu_13514_p4;
wire   [21:0] trunc_ln708_18_fu_13528_p1;
wire   [18:0] shl_ln1118_28_fu_13538_p3;
wire  signed [21:0] sext_ln1118_58_fu_13545_p1;
wire   [21:0] sub_ln1118_14_fu_13549_p2;
wire   [18:0] shl_ln1118_30_fu_13575_p3;
wire  signed [23:0] sext_ln1118_59_fu_13582_p1;
wire   [23:0] shl_ln1118_29_fu_13568_p3;
wire   [23:0] sub_ln1118_15_fu_13586_p2;
wire   [22:0] tmp_1_fu_13602_p3;
wire  signed [23:0] sext_ln1118_63_fu_13609_p1;
wire   [23:0] sub_ln1118_20_fu_13613_p2;
wire   [22:0] trunc_ln708_21_fu_13638_p1;
wire   [19:0] shl_ln1118_32_fu_13655_p3;
wire   [23:0] shl_ln1118_31_fu_13648_p3;
wire  signed [23:0] sext_ln1118_60_fu_13662_p1;
wire   [23:0] sub_ln1118_16_fu_13666_p2;
wire   [22:0] tmp_2_fu_13685_p3;
wire  signed [23:0] sext_ln1118_19_fu_13103_p1;
wire  signed [23:0] sext_ln1118_64_fu_13692_p1;
wire   [23:0] sub_ln1118_21_fu_13696_p2;
wire   [17:0] shl_ln1118_34_fu_13712_p3;
wire  signed [20:0] sext_ln1118_61_fu_13719_p1;
wire   [20:0] sub_ln1118_18_fu_13723_p2;
wire   [12:0] trunc_ln708_23_fu_13729_p4;
wire  signed [15:0] mult_3_V_fu_13060_p1;
wire  signed [15:0] mult_4_V_fu_13063_p1;
wire   [15:0] add_ln703_2_fu_13753_p2;
wire   [15:0] add_ln703_1_fu_13748_p2;
wire   [15:0] add_ln703_3_fu_13759_p2;
wire   [15:0] add_ln703_fu_13743_p2;
wire   [15:0] add_ln703_4_fu_13765_p2;
wire  signed [15:0] mult_7_V_fu_13096_p1;
wire   [15:0] add_ln703_6_fu_13777_p2;
wire  signed [15:0] mult_9_V_fu_13100_p1;
wire  signed [15:0] mult_10_V_fu_13136_p1;
wire   [15:0] add_ln703_8_fu_13788_p2;
wire   [15:0] add_ln703_9_fu_13794_p2;
wire   [15:0] add_ln703_7_fu_13783_p2;
wire  signed [15:0] mult_13_V_fu_13181_p1;
wire   [15:0] add_ln703_11_fu_13805_p2;
wire  signed [15:0] mult_11_V_fu_13140_p1;
wire  signed [15:0] mult_15_V_fu_13185_p1;
wire  signed [15:0] mult_16_V_fu_13188_p1;
wire   [15:0] add_ln703_13_fu_13816_p2;
wire   [15:0] add_ln703_14_fu_13822_p2;
wire   [15:0] add_ln703_12_fu_13810_p2;
wire   [15:0] add_ln703_17_fu_13833_p2;
wire   [15:0] add_ln703_18_fu_13838_p2;
wire  signed [14:0] sext_ln203_fu_13235_p1;
wire  signed [14:0] sext_ln203_1_fu_13239_p1;
wire   [14:0] add_ln703_23_fu_13850_p2;
wire  signed [15:0] mult_24_V_fu_13269_p1;
wire   [15:0] add_ln703_26_fu_13866_p2;
wire   [15:0] add_ln703_25_fu_13862_p2;
wire  signed [15:0] mult_29_V_fu_13273_p1;
wire   [15:0] add_ln703_32_fu_13883_p2;
wire  signed [15:0] mult_30_V_fu_13276_p1;
wire  signed [15:0] mult_34_V_fu_13317_p1;
wire  signed [15:0] mult_38_V_fu_13321_p1;
wire   [15:0] add_ln703_37_fu_13899_p2;
wire   [15:0] mult_47_V_fu_13416_p4;
wire  signed [15:0] mult_50_V_fu_13467_p1;
wire   [15:0] add_ln703_55_fu_13921_p2;
wire  signed [15:0] mult_49_V_fu_13426_p1;
wire  signed [15:0] mult_54_V_fu_13524_p1;
wire   [15:0] add_ln703_58_fu_13932_p2;
wire  signed [15:0] mult_53_V_fu_13504_p1;
wire   [15:0] add_ln703_60_fu_13943_p2;
wire   [15:0] add_ln703_61_fu_13948_p2;
wire   [15:0] add_ln703_59_fu_13937_p2;
wire  signed [15:0] mult_70_V_fu_13565_p1;
wire   [15:0] add_ln703_77_fu_13964_p2;
wire   [15:0] mult_76_V_fu_13592_p4;
wire   [15:0] add_ln703_82_fu_13979_p2;
wire   [15:0] mult_79_V_fu_13618_p4;
wire  signed [15:0] mult_86_V_fu_13682_p1;
wire   [15:0] add_ln703_100_fu_14005_p2;
wire   [15:0] mult_90_V_fu_13702_p4;
wire  signed [15:0] mult_94_V_fu_13739_p1;
wire   [15:0] add_ln703_105_fu_14022_p2;
wire   [15:0] add_ln703_16_fu_14046_p2;
wire   [15:0] add_ln703_20_fu_14050_p2;
wire   [15:0] add_ln703_21_fu_14055_p2;
wire  signed [15:0] sext_ln703_fu_14066_p1;
wire   [15:0] add_ln703_28_fu_14069_p2;
wire   [15:0] add_ln703_31_fu_14080_p2;
wire   [15:0] add_ln703_36_fu_14090_p2;
wire   [15:0] add_ln703_39_fu_14095_p2;
wire   [15:0] add_ln703_34_fu_14085_p2;
wire  signed [14:0] sext_ln203_2_fu_14031_p1;
wire   [14:0] add_ln703_41_fu_14106_p2;
wire  signed [15:0] sext_ln703_1_fu_14112_p1;
wire   [15:0] add_ln703_40_fu_14100_p2;
wire   [15:0] add_ln703_42_fu_14116_p2;
wire   [15:0] add_ln703_29_fu_14074_p2;
wire  signed [13:0] sext_ln703_2_fu_14128_p1;
wire   [13:0] add_ln703_44_fu_14131_p2;
wire  signed [15:0] sext_ln703_3_fu_14137_p1;
wire   [15:0] add_ln703_43_fu_14122_p2;
wire   [15:0] add_ln703_46_fu_14147_p2;
wire  signed [15:0] mult_43_V_fu_14034_p1;
wire   [15:0] add_ln703_48_fu_14158_p2;
wire   [15:0] add_ln703_50_fu_14164_p2;
wire   [15:0] add_ln703_47_fu_14152_p2;
wire   [15:0] add_ln703_51_fu_14169_p2;
wire   [15:0] add_ln703_54_fu_14181_p2;
wire   [15:0] add_ln703_57_fu_14186_p2;
wire   [15:0] add_ln703_64_fu_14196_p2;
wire   [15:0] add_ln703_63_fu_14191_p2;
wire   [15:0] add_ln703_65_fu_14202_p2;
wire   [15:0] add_ln703_52_fu_14175_p2;
wire  signed [8:0] sext_ln703_4_fu_14214_p1;
wire   [8:0] add_ln703_67_fu_14217_p2;
wire  signed [15:0] sext_ln703_5_fu_14223_p1;
wire   [15:0] add_ln703_68_fu_14227_p2;
wire   [15:0] add_ln703_66_fu_14208_p2;
wire  signed [15:0] mult_60_V_fu_14037_p1;
wire  signed [15:0] mult_64_V_fu_14040_p1;
wire   [15:0] add_ln703_72_fu_14251_p2;
wire   [15:0] add_ln703_71_fu_14245_p2;
wire   [15:0] add_ln703_73_fu_14257_p2;
wire   [15:0] add_ln703_70_fu_14239_p2;
wire   [15:0] add_ln703_76_fu_14269_p2;
wire   [15:0] add_ln703_81_fu_14279_p2;
wire   [15:0] add_ln703_84_fu_14284_p2;
wire   [15:0] add_ln703_79_fu_14274_p2;
wire   [15:0] add_ln703_87_fu_14295_p2;
wire   [15:0] add_ln703_88_fu_14300_p2;
wire   [15:0] add_ln703_85_fu_14289_p2;
wire   [15:0] add_ln703_89_fu_14306_p2;
wire   [15:0] add_ln703_74_fu_14263_p2;
wire   [15:0] add_ln703_91_fu_14318_p2;
wire  signed [15:0] mult_83_V_fu_14043_p1;
wire   [15:0] add_ln703_93_fu_14329_p2;
wire   [15:0] add_ln703_95_fu_14334_p2;
wire   [15:0] add_ln703_92_fu_14323_p2;
wire   [15:0] add_ln703_96_fu_14339_p2;
wire   [15:0] add_ln703_99_fu_14351_p2;
wire   [15:0] add_ln703_104_fu_14361_p2;
wire   [15:0] add_ln703_107_fu_14366_p2;
wire   [15:0] add_ln703_102_fu_14356_p2;
wire   [15:0] add_ln703_109_fu_14377_p2;
wire   [15:0] add_ln703_108_fu_14371_p2;
wire   [15:0] add_ln703_110_fu_14383_p2;
wire   [15:0] add_ln703_97_fu_14345_p2;
wire  signed [14:0] sext_ln703_6_fu_14395_p1;
wire   [14:0] add_ln703_112_fu_14398_p2;
wire  signed [15:0] sext_ln703_7_fu_14404_p1;
wire   [15:0] add_ln703_113_fu_14408_p2;
wire   [15:0] add_ln703_111_fu_14389_p2;
wire   [15:0] add_ln703_22_fu_14060_p2;
wire   [15:0] add_ln703_45_fu_14141_p2;
wire   [15:0] add_ln703_69_fu_14233_p2;
wire   [15:0] add_ln703_90_fu_14312_p2;
wire   [15:0] add_ln703_114_fu_14414_p2;
reg   [1:0] ap_NS_fsm;
reg    ap_idle_pp0_0to0;
reg    ap_reset_idle_pp0;
reg    ap_idle_pp0_1to1;
wire    ap_enable_pp0;

// power-on initialization
initial begin
#0 ap_CS_fsm = 2'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        add_ln703_101_reg_14983 <= add_ln703_101_fu_14011_p2;
        add_ln703_103_reg_14988 <= add_ln703_103_fu_14017_p2;
        add_ln703_106_reg_14993 <= add_ln703_106_fu_14026_p2;
        add_ln703_10_reg_14883 <= add_ln703_10_fu_13799_p2;
        add_ln703_15_reg_14888 <= add_ln703_15_fu_13827_p2;
        add_ln703_19_reg_14893 <= add_ln703_19_fu_13844_p2;
        add_ln703_24_reg_14898 <= add_ln703_24_fu_13856_p2;
        add_ln703_27_reg_14903 <= add_ln703_27_fu_13871_p2;
        add_ln703_30_reg_14908 <= add_ln703_30_fu_13877_p2;
        add_ln703_33_reg_14913 <= add_ln703_33_fu_13888_p2;
        add_ln703_35_reg_14918 <= add_ln703_35_fu_13894_p2;
        add_ln703_38_reg_14923 <= add_ln703_38_fu_13904_p2;
        add_ln703_49_reg_14928 <= add_ln703_49_fu_13910_p2;
        add_ln703_53_reg_14933 <= add_ln703_53_fu_13915_p2;
        add_ln703_56_reg_14938 <= add_ln703_56_fu_13926_p2;
        add_ln703_5_reg_14878 <= add_ln703_5_fu_13771_p2;
        add_ln703_62_reg_14943 <= add_ln703_62_fu_13953_p2;
        add_ln703_75_reg_14948 <= add_ln703_75_fu_13959_p2;
        add_ln703_78_reg_14953 <= add_ln703_78_fu_13969_p2;
        add_ln703_80_reg_14958 <= add_ln703_80_fu_13974_p2;
        add_ln703_83_reg_14963 <= add_ln703_83_fu_13984_p2;
        add_ln703_86_reg_14968 <= add_ln703_86_fu_13990_p2;
        add_ln703_94_reg_14973 <= add_ln703_94_fu_13995_p2;
        add_ln703_98_reg_14978 <= add_ln703_98_fu_14001_p2;
        mult_41_V_reg_14843 <= {{grp_fu_448_p2[23:8]}};
        mult_80_V_reg_14863 <= {{grp_fu_477_p2[23:8]}};
        mult_84_V_reg_14873 <= {{sub_ln1118_16_fu_13666_p2[23:8]}};
        tmp_5_reg_14838 <= {{sub_ln1118_7_fu_13352_p2[20:8]}};
        trunc_ln708_13_reg_14848 <= {{trunc_ln708_13_fu_13378_p1[22:8]}};
        trunc_ln708_18_reg_14853 <= {{trunc_ln708_18_fu_13528_p1[21:8]}};
        trunc_ln708_19_reg_14858 <= {{sub_ln1118_14_fu_13549_p2[21:8]}};
        trunc_ln708_21_reg_14868 <= {{trunc_ln708_21_fu_13638_p1[22:8]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        data_0_V_read_5_reg_14538 <= data_0_V_read;
        data_10_V_read11_reg_14507 <= data_10_V_read;
        data_13_V_read_3_reg_14500 <= data_13_V_read;
        data_14_V_read_3_reg_14493 <= data_14_V_read;
        data_16_V_read_3_reg_14487 <= data_16_V_read;
        data_19_V_read_3_reg_14480 <= data_19_V_read;
        data_3_V_read_4_reg_14533 <= data_3_V_read;
        data_4_V_read_5_reg_14525 <= data_4_V_read;
        data_7_V_read_5_reg_14517 <= data_7_V_read;
        mult_0_V_reg_14551 <= {{mul_ln1118_fu_451_p2[23:8]}};
        mult_12_V_reg_14630 <= {{mul_ln1118_8_fu_483_p2[23:8]}};
        mult_14_V_reg_14641 <= {{mul_ln1118_9_fu_479_p2[23:8]}};
        mult_19_V_reg_14668 <= {{mul_ln1118_13_fu_441_p2[23:8]}};
        mult_22_V_reg_14678 <= {{mul_ln1118_14_fu_474_p2[23:8]}};
        mult_23_V_reg_14683 <= {{mul_ln1118_15_fu_475_p2[23:8]}};
        mult_25_V_reg_14688 <= {{mul_ln1118_16_fu_444_p2[23:8]}};
        mult_2_V_reg_14569 <= {{mul_ln1118_2_fu_466_p2[23:8]}};
        mult_32_V_reg_14703 <= {{grp_fu_455_p2[23:8]}};
        mult_35_V_reg_14708 <= {{mul_ln1118_24_fu_457_p2[23:8]}};
        mult_37_V_reg_14713 <= {{grp_fu_459_p2[23:8]}};
        mult_45_V_reg_14723 <= {{sub_ln1118_9_fu_12741_p2[23:8]}};
        mult_52_V_reg_14733 <= {{mul_ln1118_34_fu_438_p2[23:8]}};
        mult_55_V_reg_14738 <= {{mul_ln1118_35_fu_476_p2[23:8]}};
        mult_56_V_reg_14743 <= {{mul_ln1118_36_fu_454_p2[23:8]}};
        mult_57_V_reg_14748 <= {{mul_ln1118_37_fu_480_p2[23:8]}};
        mult_5_V_reg_14594 <= {{mul_ln1118_4_fu_456_p2[23:8]}};
        mult_66_V_reg_14753 <= {{mul_ln1118_45_fu_463_p2[23:8]}};
        mult_68_V_reg_14758 <= {{mul_ln1118_47_fu_487_p2[23:8]}};
        mult_69_V_reg_14763 <= {{mul_ln1118_48_fu_447_p2[23:8]}};
        mult_72_V_reg_14773 <= {{mul_ln1118_51_fu_471_p2[23:8]}};
        mult_75_V_reg_14778 <= {{mul_ln1118_54_fu_449_p2[23:8]}};
        mult_78_V_reg_14783 <= {{mul_ln1118_56_fu_478_p2[23:8]}};
        mult_88_V_reg_14793 <= {{sub_ln1118_17_fu_12925_p2[23:8]}};
        mult_89_V_reg_14798 <= {{mul_ln1118_63_fu_442_p2[23:8]}};
        mult_8_V_reg_14610 <= {{mul_ln1118_6_fu_470_p2[23:8]}};
        mult_95_V_reg_14803 <= {{mul_ln1118_67_fu_443_p2[23:8]}};
        mult_96_V_reg_14808 <= {{mul_ln1118_68_fu_481_p2[23:8]}};
        mult_97_V_reg_14813 <= {{sub_ln1118_19_fu_12995_p2[23:8]}};
        mult_98_V_reg_14818 <= {{mul_ln1118_69_fu_445_p2[23:8]}};
        sext_ln1118_10_reg_14589 <= sext_ln1118_10_fu_12294_p1;
        sext_ln1118_12_reg_14599 <= sext_ln1118_12_fu_12316_p1;
        sext_ln1118_13_reg_14605 <= sext_ln1118_13_fu_12322_p1;
        sext_ln1118_1_reg_14545 <= sext_ln1118_1_fu_12193_p1;
        sext_ln1118_24_reg_14620 <= sext_ln1118_24_fu_12377_p1;
        sext_ln1118_28_reg_14635 <= sext_ln1118_28_fu_12442_p1;
        sext_ln1118_2_reg_14556 <= sext_ln1118_2_fu_12208_p1;
        sext_ln1118_36_reg_14656 <= sext_ln1118_36_fu_12521_p1;
        sext_ln1118_38_reg_14661 <= sext_ln1118_38_fu_12536_p1;
        sext_ln1118_3_reg_14563 <= sext_ln1118_3_fu_12213_p1;
        sext_ln1118_5_reg_14574 <= sext_ln1118_5_fu_12229_p1;
        tmp_4_reg_14673 <= {{add_ln1118_4_fu_12575_p2[21:8]}};
        tmp_6_reg_14823 <= {{tmp_6_fu_13021_p1[15:5]}};
        tmp_7_reg_14828 <= {{tmp_7_fu_13031_p1[15:8]}};
        tmp_8_reg_14833 <= {{tmp_8_fu_13041_p1[15:2]}};
        trunc_ln708_10_reg_14698 <= {{mul_ln1118_20_fu_472_p2[20:8]}};
        trunc_ln708_12_reg_14718 <= {{add_ln1118_5_fu_12695_p2[19:8]}};
        trunc_ln708_14_reg_14728 <= {{sub_ln1118_10_fu_12781_p2[20:8]}};
        trunc_ln708_1_reg_14584 <= {{grp_fu_450_p2[22:8]}};
        trunc_ln708_20_reg_14768 <= {{mul_ln1118_49_fu_469_p2[21:8]}};
        trunc_ln708_22_reg_14788 <= {{mul_ln1118_61_fu_482_p2[20:8]}};
        trunc_ln708_2_reg_14646 <= {{sub_ln1118_1_fu_12483_p2[22:8]}};
        trunc_ln708_3_reg_14651 <= {{trunc_ln708_3_fu_12511_p1[22:8]}};
        trunc_ln708_6_reg_14615 <= {{trunc_ln708_6_fu_12357_p1[22:8]}};
        trunc_ln708_8_reg_14625 <= {{add_ln1118_2_fu_12407_p2[20:8]}};
        trunc_ln708_9_reg_14693 <= {{mul_ln1118_19_fu_460_p2[22:8]}};
        trunc_ln_reg_14579 <= {{add_ln1118_fu_12258_p2[20:8]}};
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        reg_12129 <= {{grp_fu_452_p2[23:8]}};
        reg_12133 <= {{grp_fu_461_p2[23:8]}};
        reg_12137 <= {{grp_fu_462_p2[23:8]}};
        reg_12141 <= {{grp_fu_446_p2[23:8]}};
        reg_12145 <= {{grp_fu_458_p2[23:8]}};
        reg_12149 <= {{grp_fu_473_p2[23:8]}};
        reg_12153 <= {{grp_fu_468_p2[23:8]}};
        reg_12157 <= {{grp_fu_440_p2[23:8]}};
        reg_12161 <= {{grp_fu_486_p2[23:8]}};
        reg_12165 <= {{grp_fu_453_p2[23:8]}};
        reg_12169 <= {{grp_fu_484_p2[23:8]}};
        reg_12173 <= {{grp_fu_467_p2[23:8]}};
        reg_12177 <= {{grp_fu_485_p2[23:8]}};
        reg_12181 <= {{grp_fu_439_p2[23:8]}};
        reg_12185 <= {{grp_fu_464_p2[23:8]}};
        reg_12189 <= {{grp_fu_465_p2[23:8]}};
    end
end

always @ (*) begin
    if ((((ap_start == 1'b0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b0)) begin
        ap_idle_pp0_0to0 = 1'b1;
    end else begin
        ap_idle_pp0_0to0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter1 == 1'b0)) begin
        ap_idle_pp0_1to1 = 1'b1;
    end else begin
        ap_idle_pp0_1to1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_ce) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0_0to0 == 1'b1))) begin
        ap_reset_idle_pp0 = 1'b1;
    end else begin
        ap_reset_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_fu_439_p0 = 24'd16776753;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_fu_439_p0 = 24'd16776989;
        end else begin
            grp_fu_439_p0 = 'bx;
        end
    end else begin
        grp_fu_439_p0 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_fu_439_p1 = sext_ln1118_1_reg_14545;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_fu_439_p1 = sext_ln1118_10_fu_12294_p1;
        end else begin
            grp_fu_439_p1 = 'bx;
        end
    end else begin
        grp_fu_439_p1 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_fu_440_p0 = 24'd16776940;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_fu_440_p0 = 24'd16776978;
        end else begin
            grp_fu_440_p0 = 'bx;
        end
    end else begin
        grp_fu_440_p0 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_fu_440_p1 = sext_ln1118_24_reg_14620;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_fu_440_p1 = sext_ln1118_9_fu_12279_p1;
        end else begin
            grp_fu_440_p1 = 'bx;
        end
    end else begin
        grp_fu_440_p1 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_fu_446_p0 = 24'd235;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_fu_446_p0 = 24'd16776953;
        end else begin
            grp_fu_446_p0 = 'bx;
        end
    end else begin
        grp_fu_446_p0 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_fu_446_p1 = sext_ln1118_28_reg_14635;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_fu_446_p1 = sext_ln1118_37_fu_12528_p1;
        end else begin
            grp_fu_446_p1 = 'bx;
        end
    end else begin
        grp_fu_446_p1 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_fu_448_p0 = 24'd139;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_fu_448_p0 = 23'd51;
        end else begin
            grp_fu_448_p0 = 'bx;
        end
    end else begin
        grp_fu_448_p0 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_fu_448_p1 = sext_ln1118_2_reg_14556;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_fu_448_p1 = sext_ln1118_18_fu_12351_p1;
        end else begin
            grp_fu_448_p1 = 'bx;
        end
    end else begin
        grp_fu_448_p1 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_fu_450_p0 = 22'd4194283;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_fu_450_p0 = 23'd37;
        end else begin
            grp_fu_450_p0 = 'bx;
        end
    end else begin
        grp_fu_450_p0 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_fu_450_p1 = sext_ln1118_fu_13051_p1;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_fu_450_p1 = sext_ln1118_8_fu_12274_p1;
        end else begin
            grp_fu_450_p1 = 'bx;
        end
    end else begin
        grp_fu_450_p1 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_fu_452_p0 = 24'd16776890;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_fu_452_p0 = 24'd16776924;
        end else begin
            grp_fu_452_p0 = 'bx;
        end
    end else begin
        grp_fu_452_p0 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_fu_452_p1 = sext_ln1118_13_reg_14605;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_fu_452_p1 = sext_ln1118_2_fu_12208_p1;
        end else begin
            grp_fu_452_p1 = 'bx;
        end
    end else begin
        grp_fu_452_p1 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_fu_453_p0 = 24'd16776890;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_fu_453_p0 = 24'd123;
        end else begin
            grp_fu_453_p0 = 'bx;
        end
    end else begin
        grp_fu_453_p0 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_fu_453_p1 = sext_ln1118_28_reg_14635;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_fu_453_p1 = sext_ln1118_37_fu_12528_p1;
        end else begin
            grp_fu_453_p1 = 'bx;
        end
    end else begin
        grp_fu_453_p1 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_fu_455_p0 = 23'd8388556;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_fu_455_p0 = 24'd133;
        end else begin
            grp_fu_455_p0 = 'bx;
        end
    end else begin
        grp_fu_455_p0 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_fu_455_p1 = sext_ln1118_4_fu_13055_p1;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_fu_455_p1 = sext_ln1118_27_fu_12423_p1;
        end else begin
            grp_fu_455_p1 = 'bx;
        end
    end else begin
        grp_fu_455_p1 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_fu_458_p0 = 24'd16777129;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_fu_458_p0 = 24'd16777125;
        end else begin
            grp_fu_458_p0 = 'bx;
        end
    end else begin
        grp_fu_458_p0 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_fu_458_p1 = sext_ln1118_3_reg_14563;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_fu_458_p1 = sext_ln1118_16_fu_12327_p1;
        end else begin
            grp_fu_458_p1 = 'bx;
        end
    end else begin
        grp_fu_458_p1 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_fu_459_p0 = 23'd8388569;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_fu_459_p0 = 24'd16777112;
        end else begin
            grp_fu_459_p0 = 'bx;
        end
    end else begin
        grp_fu_459_p0 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_fu_459_p1 = sext_ln1118_4_fu_13055_p1;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_fu_459_p1 = sext_ln1118_36_fu_12521_p1;
        end else begin
            grp_fu_459_p1 = 'bx;
        end
    end else begin
        grp_fu_459_p1 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_fu_461_p1 = sext_ln1118_3_reg_14563;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_fu_461_p1 = sext_ln1118_12_fu_12316_p1;
        end else begin
            grp_fu_461_p1 = 'bx;
        end
    end else begin
        grp_fu_461_p1 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_fu_462_p0 = 24'd82;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_fu_462_p0 = 24'd16777085;
        end else begin
            grp_fu_462_p0 = 'bx;
        end
    end else begin
        grp_fu_462_p0 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_fu_462_p1 = sext_ln1118_12_reg_14599;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_fu_462_p1 = sext_ln1118_36_fu_12521_p1;
        end else begin
            grp_fu_462_p1 = 'bx;
        end
    end else begin
        grp_fu_462_p1 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_fu_464_p0 = 24'd117;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_fu_464_p0 = 24'd88;
        end else begin
            grp_fu_464_p0 = 'bx;
        end
    end else begin
        grp_fu_464_p0 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_fu_464_p1 = sext_ln1118_36_reg_14656;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_fu_464_p1 = sext_ln1118_24_fu_12377_p1;
        end else begin
            grp_fu_464_p1 = 'bx;
        end
    end else begin
        grp_fu_464_p1 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_fu_465_p0 = 24'd16777038;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_fu_465_p0 = 24'd199;
        end else begin
            grp_fu_465_p0 = 'bx;
        end
    end else begin
        grp_fu_465_p0 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_fu_465_p1 = sext_ln1118_5_reg_14574;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_fu_465_p1 = sext_ln1118_27_fu_12423_p1;
        end else begin
            grp_fu_465_p1 = 'bx;
        end
    end else begin
        grp_fu_465_p1 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_fu_467_p0 = 24'd91;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_fu_467_p0 = 24'd16777022;
        end else begin
            grp_fu_467_p0 = 'bx;
        end
    end else begin
        grp_fu_467_p0 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_fu_467_p1 = sext_ln1118_10_reg_14589;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_fu_467_p1 = sext_ln1118_28_fu_12442_p1;
        end else begin
            grp_fu_467_p1 = 'bx;
        end
    end else begin
        grp_fu_467_p1 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_fu_468_p1 = sext_ln1118_12_reg_14599;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_fu_468_p1 = sext_ln1118_35_fu_12504_p1;
        end else begin
            grp_fu_468_p1 = 'bx;
        end
    end else begin
        grp_fu_468_p1 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_fu_473_p0 = 24'd190;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_fu_473_p0 = 24'd16777110;
        end else begin
            grp_fu_473_p0 = 'bx;
        end
    end else begin
        grp_fu_473_p0 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_fu_473_p1 = sext_ln1118_38_reg_14661;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_fu_473_p1 = sext_ln1118_24_fu_12377_p1;
        end else begin
            grp_fu_473_p1 = 'bx;
        end
    end else begin
        grp_fu_473_p1 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_fu_477_p0 = 24'd16776631;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_fu_477_p0 = 23'd57;
        end else begin
            grp_fu_477_p0 = 'bx;
        end
    end else begin
        grp_fu_477_p0 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_fu_477_p1 = sext_ln1118_1_reg_14545;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_fu_477_p1 = sext_ln1118_34_fu_12499_p1;
        end else begin
            grp_fu_477_p1 = 'bx;
        end
    end else begin
        grp_fu_477_p1 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_fu_484_p0 = 24'd100;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_fu_484_p0 = 24'd16777143;
        end else begin
            grp_fu_484_p0 = 'bx;
        end
    end else begin
        grp_fu_484_p0 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_fu_484_p1 = sext_ln1118_2_reg_14556;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_fu_484_p1 = sext_ln1118_13_fu_12322_p1;
        end else begin
            grp_fu_484_p1 = 'bx;
        end
    end else begin
        grp_fu_484_p1 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_fu_485_p0 = 24'd189;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_fu_485_p0 = 24'd142;
        end else begin
            grp_fu_485_p0 = 'bx;
        end
    end else begin
        grp_fu_485_p0 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_fu_485_p1 = sext_ln1118_2_reg_14556;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_fu_485_p1 = sext_ln1118_31_fu_12447_p1;
        end else begin
            grp_fu_485_p1 = 'bx;
        end
    end else begin
        grp_fu_485_p1 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_fu_486_p0 = 24'd94;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_fu_486_p0 = 24'd89;
        end else begin
            grp_fu_486_p0 = 'bx;
        end
    end else begin
        grp_fu_486_p0 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            grp_fu_486_p1 = sext_ln1118_38_reg_14661;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            grp_fu_486_p1 = sext_ln1118_16_fu_12327_p1;
        end else begin
            grp_fu_486_p1 = 'bx;
        end
    end else begin
        grp_fu_486_p1 = 'bx;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_start == 1'b0) & (ap_idle_pp0_1to1 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_reset_idle_pp0 == 1'b0))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_reset_idle_pp0 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln1118_1_fu_13120_p2 = ($signed(sext_ln1118_23_fu_13116_p1) + $signed(sext_ln1118_21_fu_13106_p1));

assign add_ln1118_2_fu_12407_p2 = ($signed(sext_ln1118_26_fu_12403_p1) + $signed(sext_ln1118_25_fu_12391_p1));

assign add_ln1118_3_fu_13165_p2 = ($signed(sext_ln1118_30_fu_13161_p1) + $signed(sext_ln1118_29_fu_13150_p1));

assign add_ln1118_4_fu_12575_p2 = ($signed(sext_ln1118_42_fu_12571_p1) + $signed(sext_ln1118_41_fu_12559_p1));

assign add_ln1118_5_fu_12695_p2 = ($signed(sext_ln1118_47_fu_12691_p1) + $signed(sext_ln1118_46_fu_12679_p1));

assign add_ln1118_6_fu_13410_p2 = ($signed(sext_ln1118_52_fu_13406_p1) + $signed(sext_ln1118_51_fu_13395_p1));

assign add_ln1118_7_fu_13451_p2 = ($signed(sext_ln1118_56_fu_13447_p1) + $signed(sext_ln1118_55_fu_13436_p1));

assign add_ln1118_fu_12258_p2 = ($signed(sext_ln1118_7_fu_12254_p1) + $signed(sext_ln1118_6_fu_12242_p1));

assign add_ln703_100_fu_14005_p2 = (reg_12185 + reg_12189);

assign add_ln703_101_fu_14011_p2 = (add_ln703_100_fu_14005_p2 + mult_90_V_fu_13702_p4);

assign add_ln703_102_fu_14356_p2 = (add_ln703_101_reg_14983 + add_ln703_99_fu_14351_p2);

assign add_ln703_103_fu_14017_p2 = ($signed(mult_94_V_fu_13739_p1) + $signed(mult_95_V_reg_14803));

assign add_ln703_104_fu_14361_p2 = (add_ln703_103_reg_14988 + reg_12165);

assign add_ln703_105_fu_14022_p2 = (mult_97_V_reg_14813 + mult_98_V_reg_14818);

assign add_ln703_106_fu_14026_p2 = (add_ln703_105_fu_14022_p2 + mult_96_V_reg_14808);

assign add_ln703_107_fu_14366_p2 = (add_ln703_106_reg_14993 + add_ln703_104_fu_14361_p2);

assign add_ln703_108_fu_14371_p2 = (add_ln703_107_fu_14366_p2 + add_ln703_102_fu_14356_p2);

assign add_ln703_109_fu_14377_p2 = (16'd8 + reg_12161);

assign add_ln703_10_fu_13799_p2 = (add_ln703_9_fu_13794_p2 + add_ln703_7_fu_13783_p2);

assign add_ln703_110_fu_14383_p2 = (add_ln703_109_fu_14377_p2 + add_ln703_108_fu_14371_p2);

assign add_ln703_111_fu_14389_p2 = (add_ln703_110_fu_14383_p2 + add_ln703_97_fu_14345_p2);

assign add_ln703_112_fu_14398_p2 = ($signed(15'd7) + $signed(sext_ln703_6_fu_14395_p1));

assign add_ln703_113_fu_14408_p2 = ($signed(16'd65506) + $signed(sext_ln703_7_fu_14404_p1));

assign add_ln703_114_fu_14414_p2 = (add_ln703_113_fu_14408_p2 + add_ln703_111_fu_14389_p2);

assign add_ln703_11_fu_13805_p2 = ($signed(mult_12_V_reg_14630) + $signed(mult_13_V_fu_13181_p1));

assign add_ln703_12_fu_13810_p2 = ($signed(add_ln703_11_fu_13805_p2) + $signed(mult_11_V_fu_13140_p1));

assign add_ln703_13_fu_13816_p2 = ($signed(mult_15_V_fu_13185_p1) + $signed(mult_16_V_fu_13188_p1));

assign add_ln703_14_fu_13822_p2 = (add_ln703_13_fu_13816_p2 + mult_14_V_reg_14641);

assign add_ln703_15_fu_13827_p2 = (add_ln703_14_fu_13822_p2 + add_ln703_12_fu_13810_p2);

assign add_ln703_16_fu_14046_p2 = (add_ln703_15_reg_14888 + add_ln703_10_reg_14883);

assign add_ln703_17_fu_13833_p2 = (reg_12141 + mult_19_V_reg_14668);

assign add_ln703_18_fu_13838_p2 = (add_ln703_17_fu_13833_p2 + reg_12137);

assign add_ln703_19_fu_13844_p2 = ($signed(16'd65507) + $signed(add_ln703_18_fu_13838_p2));

assign add_ln703_1_fu_13748_p2 = (reg_12129 + mult_2_V_reg_14569);

assign add_ln703_20_fu_14050_p2 = (add_ln703_19_reg_14893 + add_ln703_16_fu_14046_p2);

assign add_ln703_21_fu_14055_p2 = (add_ln703_20_fu_14050_p2 + add_ln703_5_reg_14878);

assign add_ln703_22_fu_14060_p2 = ($signed(16'd65415) + $signed(add_ln703_21_fu_14055_p2));

assign add_ln703_23_fu_13850_p2 = ($signed(sext_ln203_fu_13235_p1) + $signed(sext_ln203_1_fu_13239_p1));

assign add_ln703_24_fu_13856_p2 = ($signed(15'd32767) + $signed(add_ln703_23_fu_13850_p2));

assign add_ln703_25_fu_13862_p2 = (mult_22_V_reg_14678 + mult_23_V_reg_14683);

assign add_ln703_26_fu_13866_p2 = ($signed(mult_24_V_fu_13269_p1) + $signed(mult_25_V_reg_14688));

assign add_ln703_27_fu_13871_p2 = (add_ln703_26_fu_13866_p2 + add_ln703_25_fu_13862_p2);

assign add_ln703_28_fu_14069_p2 = ($signed(add_ln703_27_reg_14903) + $signed(sext_ln703_fu_14066_p1));

assign add_ln703_29_fu_14074_p2 = ($signed(16'd65511) + $signed(add_ln703_28_fu_14069_p2));

assign add_ln703_2_fu_13753_p2 = ($signed(mult_3_V_fu_13060_p1) + $signed(mult_4_V_fu_13063_p1));

assign add_ln703_30_fu_13877_p2 = ($signed(reg_12145) + $signed(mult_29_V_fu_13273_p1));

assign add_ln703_31_fu_14080_p2 = (add_ln703_30_reg_14908 + reg_12137);

assign add_ln703_32_fu_13883_p2 = (reg_12149 + mult_32_V_reg_14703);

assign add_ln703_33_fu_13888_p2 = ($signed(add_ln703_32_fu_13883_p2) + $signed(mult_30_V_fu_13276_p1));

assign add_ln703_34_fu_14085_p2 = (add_ln703_33_reg_14913 + add_ln703_31_fu_14080_p2);

assign add_ln703_35_fu_13894_p2 = ($signed(mult_34_V_fu_13317_p1) + $signed(mult_35_V_reg_14708));

assign add_ln703_36_fu_14090_p2 = (add_ln703_35_reg_14918 + reg_12141);

assign add_ln703_37_fu_13899_p2 = ($signed(mult_37_V_reg_14713) + $signed(mult_38_V_fu_13321_p1));

assign add_ln703_38_fu_13904_p2 = (add_ln703_37_fu_13899_p2 + reg_12153);

assign add_ln703_39_fu_14095_p2 = (add_ln703_38_reg_14923 + add_ln703_36_fu_14090_p2);

assign add_ln703_3_fu_13759_p2 = (add_ln703_2_fu_13753_p2 + add_ln703_1_fu_13748_p2);

assign add_ln703_40_fu_14100_p2 = (add_ln703_39_fu_14095_p2 + add_ln703_34_fu_14085_p2);

assign add_ln703_41_fu_14106_p2 = ($signed(15'd32747) + $signed(sext_ln203_2_fu_14031_p1));

assign add_ln703_42_fu_14116_p2 = ($signed(sext_ln703_1_fu_14112_p1) + $signed(add_ln703_40_fu_14100_p2));

assign add_ln703_43_fu_14122_p2 = (add_ln703_42_fu_14116_p2 + add_ln703_29_fu_14074_p2);

assign add_ln703_44_fu_14131_p2 = ($signed(14'd16306) + $signed(sext_ln703_2_fu_14128_p1));

assign add_ln703_45_fu_14141_p2 = ($signed(sext_ln703_3_fu_14137_p1) + $signed(add_ln703_43_fu_14122_p2));

assign add_ln703_46_fu_14147_p2 = (reg_12181 + mult_41_V_reg_14843);

assign add_ln703_47_fu_14152_p2 = (16'd3 + add_ln703_46_fu_14147_p2);

assign add_ln703_48_fu_14158_p2 = ($signed(reg_12133) + $signed(mult_43_V_fu_14034_p1));

assign add_ln703_49_fu_13910_p2 = (reg_12157 + mult_45_V_reg_14723);

assign add_ln703_4_fu_13765_p2 = (add_ln703_3_fu_13759_p2 + add_ln703_fu_13743_p2);

assign add_ln703_50_fu_14164_p2 = (add_ln703_49_reg_14928 + add_ln703_48_fu_14158_p2);

assign add_ln703_51_fu_14169_p2 = (add_ln703_50_fu_14164_p2 + add_ln703_47_fu_14152_p2);

assign add_ln703_52_fu_14175_p2 = (16'd29 + add_ln703_51_fu_14169_p2);

assign add_ln703_53_fu_13915_p2 = (mult_47_V_fu_13416_p4 + reg_12161);

assign add_ln703_54_fu_14181_p2 = (add_ln703_53_reg_14933 + reg_12153);

assign add_ln703_55_fu_13921_p2 = ($signed(mult_50_V_fu_13467_p1) + $signed(mult_52_V_reg_14733));

assign add_ln703_56_fu_13926_p2 = ($signed(add_ln703_55_fu_13921_p2) + $signed(mult_49_V_fu_13426_p1));

assign add_ln703_57_fu_14186_p2 = (add_ln703_56_reg_14938 + add_ln703_54_fu_14181_p2);

assign add_ln703_58_fu_13932_p2 = ($signed(mult_54_V_fu_13524_p1) + $signed(mult_55_V_reg_14738));

assign add_ln703_59_fu_13937_p2 = ($signed(add_ln703_58_fu_13932_p2) + $signed(mult_53_V_fu_13504_p1));

assign add_ln703_5_fu_13771_p2 = ($signed(16'd65497) + $signed(add_ln703_4_fu_13765_p2));

assign add_ln703_60_fu_13943_p2 = (mult_57_V_reg_14748 + reg_12165);

assign add_ln703_61_fu_13948_p2 = (add_ln703_60_fu_13943_p2 + mult_56_V_reg_14743);

assign add_ln703_62_fu_13953_p2 = (add_ln703_61_fu_13948_p2 + add_ln703_59_fu_13937_p2);

assign add_ln703_63_fu_14191_p2 = (add_ln703_62_reg_14943 + add_ln703_57_fu_14186_p2);

assign add_ln703_64_fu_14196_p2 = (16'd33 + reg_12149);

assign add_ln703_65_fu_14202_p2 = (add_ln703_64_fu_14196_p2 + add_ln703_63_fu_14191_p2);

assign add_ln703_66_fu_14208_p2 = (add_ln703_65_fu_14202_p2 + add_ln703_52_fu_14175_p2);

assign add_ln703_67_fu_14217_p2 = ($signed(9'd85) + $signed(sext_ln703_4_fu_14214_p1));

assign add_ln703_68_fu_14227_p2 = ($signed(16'd60) + $signed(sext_ln703_5_fu_14223_p1));

assign add_ln703_69_fu_14233_p2 = (add_ln703_68_fu_14227_p2 + add_ln703_66_fu_14208_p2);

assign add_ln703_6_fu_13777_p2 = ($signed(reg_12133) + $signed(mult_7_V_fu_13096_p1));

assign add_ln703_70_fu_14239_p2 = ($signed(16'd65533) + $signed(mult_60_V_fu_14037_p1));

assign add_ln703_71_fu_14245_p2 = (reg_12177 + reg_12145);

assign add_ln703_72_fu_14251_p2 = ($signed(reg_12189) + $signed(mult_64_V_fu_14040_p1));

assign add_ln703_73_fu_14257_p2 = (add_ln703_72_fu_14251_p2 + add_ln703_71_fu_14245_p2);

assign add_ln703_74_fu_14263_p2 = (add_ln703_73_fu_14257_p2 + add_ln703_70_fu_14239_p2);

assign add_ln703_75_fu_13959_p2 = (mult_66_V_reg_14753 + reg_12169);

assign add_ln703_76_fu_14269_p2 = (add_ln703_75_reg_14948 + reg_12173);

assign add_ln703_77_fu_13964_p2 = ($signed(mult_69_V_reg_14763) + $signed(mult_70_V_fu_13565_p1));

assign add_ln703_78_fu_13969_p2 = (add_ln703_77_fu_13964_p2 + mult_68_V_reg_14758);

assign add_ln703_79_fu_14274_p2 = (add_ln703_78_reg_14953 + add_ln703_76_fu_14269_p2);

assign add_ln703_7_fu_13783_p2 = (add_ln703_6_fu_13777_p2 + mult_5_V_reg_14594);

assign add_ln703_80_fu_13974_p2 = (mult_72_V_reg_14773 + reg_12173);

assign add_ln703_81_fu_14279_p2 = (add_ln703_80_reg_14958 + reg_12157);

assign add_ln703_82_fu_13979_p2 = (mult_75_V_reg_14778 + mult_76_V_fu_13592_p4);

assign add_ln703_83_fu_13984_p2 = (add_ln703_82_fu_13979_p2 + reg_12177);

assign add_ln703_84_fu_14284_p2 = (add_ln703_83_reg_14963 + add_ln703_81_fu_14279_p2);

assign add_ln703_85_fu_14289_p2 = (add_ln703_84_fu_14284_p2 + add_ln703_79_fu_14274_p2);

assign add_ln703_86_fu_13990_p2 = (mult_78_V_reg_14783 + mult_79_V_fu_13618_p4);

assign add_ln703_87_fu_14295_p2 = (add_ln703_86_reg_14968 + reg_12185);

assign add_ln703_88_fu_14300_p2 = (16'd8 + add_ln703_87_fu_14295_p2);

assign add_ln703_89_fu_14306_p2 = (add_ln703_88_fu_14300_p2 + add_ln703_85_fu_14289_p2);

assign add_ln703_8_fu_13788_p2 = ($signed(mult_9_V_fu_13100_p1) + $signed(mult_10_V_fu_13136_p1));

assign add_ln703_90_fu_14312_p2 = (add_ln703_89_fu_14306_p2 + add_ln703_74_fu_14263_p2);

assign add_ln703_91_fu_14318_p2 = (mult_80_V_reg_14863 + reg_12169);

assign add_ln703_92_fu_14323_p2 = (16'd1 + add_ln703_91_fu_14318_p2);

assign add_ln703_93_fu_14329_p2 = ($signed(mult_83_V_fu_14043_p1) + $signed(mult_84_V_reg_14873));

assign add_ln703_94_fu_13995_p2 = ($signed(reg_12181) + $signed(mult_86_V_fu_13682_p1));

assign add_ln703_95_fu_14334_p2 = (add_ln703_94_reg_14973 + add_ln703_93_fu_14329_p2);

assign add_ln703_96_fu_14339_p2 = (add_ln703_95_fu_14334_p2 + add_ln703_92_fu_14323_p2);

assign add_ln703_97_fu_14345_p2 = ($signed(16'd65528) + $signed(add_ln703_96_fu_14339_p2));

assign add_ln703_98_fu_14001_p2 = (mult_88_V_reg_14793 + mult_89_V_reg_14798);

assign add_ln703_99_fu_14351_p2 = (add_ln703_98_reg_14978 + reg_12129);

assign add_ln703_9_fu_13794_p2 = (add_ln703_8_fu_13788_p2 + mult_8_V_reg_14610);

assign add_ln703_fu_13743_p2 = ($signed(16'd65530) + $signed(mult_0_V_reg_14551));

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_start == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((1'b0 == ap_ce) | ((ap_start == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1)));
end

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage1_subdone = (1'b0 == ap_ce);
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_start == 1'b0);
end

assign ap_block_state2_pp0_stage1_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_return_0 = add_ln703_22_fu_14060_p2;

assign ap_return_1 = add_ln703_45_fu_14141_p2;

assign ap_return_2 = add_ln703_69_fu_14233_p2;

assign ap_return_3 = add_ln703_90_fu_14312_p2;

assign ap_return_4 = add_ln703_114_fu_14414_p2;

assign ap_return_5 = 16'd65296;

assign ap_return_6 = 16'd65385;

assign ap_return_7 = 16'd242;

assign ap_return_8 = 16'd15;

assign ap_return_9 = 16'd65507;

assign grp_fu_439_p2 = ($signed(grp_fu_439_p0) * $signed(grp_fu_439_p1));

assign grp_fu_440_p2 = ($signed(grp_fu_440_p0) * $signed(grp_fu_440_p1));

assign grp_fu_446_p2 = ($signed(grp_fu_446_p0) * $signed(grp_fu_446_p1));

assign grp_fu_448_p2 = ($signed({{1'b0}, {grp_fu_448_p0}}) * $signed(grp_fu_448_p1));

assign grp_fu_450_p2 = ($signed(grp_fu_450_p0) * $signed(grp_fu_450_p1));

assign grp_fu_452_p2 = ($signed(grp_fu_452_p0) * $signed(grp_fu_452_p1));

assign grp_fu_453_p2 = ($signed(grp_fu_453_p0) * $signed(grp_fu_453_p1));

assign grp_fu_455_p2 = ($signed(grp_fu_455_p0) * $signed(grp_fu_455_p1));

assign grp_fu_458_p2 = ($signed(grp_fu_458_p0) * $signed(grp_fu_458_p1));

assign grp_fu_459_p2 = ($signed(grp_fu_459_p0) * $signed(grp_fu_459_p1));

assign grp_fu_461_p2 = ($signed({{1'b0}, {24'd141}}) * $signed(grp_fu_461_p1));

assign grp_fu_462_p2 = ($signed(grp_fu_462_p0) * $signed(grp_fu_462_p1));

assign grp_fu_464_p2 = ($signed({{1'b0}, {grp_fu_464_p0}}) * $signed(grp_fu_464_p1));

assign grp_fu_465_p2 = ($signed(grp_fu_465_p0) * $signed(grp_fu_465_p1));

assign grp_fu_467_p2 = ($signed(grp_fu_467_p0) * $signed(grp_fu_467_p1));

assign grp_fu_468_p2 = ($signed({{1'b0}, {24'd92}}) * $signed(grp_fu_468_p1));

assign grp_fu_473_p2 = ($signed(grp_fu_473_p0) * $signed(grp_fu_473_p1));

assign grp_fu_477_p2 = ($signed(grp_fu_477_p0) * $signed(grp_fu_477_p1));

assign grp_fu_484_p2 = ($signed(grp_fu_484_p0) * $signed(grp_fu_484_p1));

assign grp_fu_485_p2 = ($signed({{1'b0}, {grp_fu_485_p0}}) * $signed(grp_fu_485_p1));

assign grp_fu_486_p2 = ($signed({{1'b0}, {grp_fu_486_p0}}) * $signed(grp_fu_486_p1));

assign mul_ln1118_13_fu_441_p1 = sext_ln1118_38_fu_12536_p0;

assign mul_ln1118_13_fu_441_p2 = ($signed(24'd16776910) * $signed(mul_ln1118_13_fu_441_p1));

assign mul_ln1118_14_fu_474_p1 = sext_ln1118_3_fu_12213_p1;

assign mul_ln1118_14_fu_474_p2 = ($signed(24'd16776933) * $signed(mul_ln1118_14_fu_474_p1));

assign mul_ln1118_15_fu_475_p1 = sext_ln1118_5_fu_12229_p0;

assign mul_ln1118_15_fu_475_p2 = ($signed(24'd16777108) * $signed(mul_ln1118_15_fu_475_p1));

assign mul_ln1118_16_fu_444_p1 = sext_ln1118_10_fu_12294_p1;

assign mul_ln1118_16_fu_444_p2 = ($signed({{1'b0}, {24'd114}}) * $signed(mul_ln1118_16_fu_444_p1));

assign mul_ln1118_19_fu_460_p1 = sext_ln1118_18_fu_12351_p0;

assign mul_ln1118_19_fu_460_p2 = ($signed({{1'b0}, {23'd37}}) * $signed(mul_ln1118_19_fu_460_p1));

assign mul_ln1118_20_fu_472_p1 = sext_ln1118_20_fu_12367_p0;

assign mul_ln1118_20_fu_472_p2 = ($signed(21'd2097139) * $signed(mul_ln1118_20_fu_472_p1));

assign mul_ln1118_24_fu_457_p1 = sext_ln1118_32_fu_12463_p1;

assign mul_ln1118_24_fu_457_p2 = ($signed(24'd16776728) * $signed(mul_ln1118_24_fu_457_p1));

assign mul_ln1118_2_fu_466_p1 = sext_ln1118_3_fu_12213_p1;

assign mul_ln1118_2_fu_466_p2 = ($signed(24'd16776984) * $signed(mul_ln1118_2_fu_466_p1));

assign mul_ln1118_34_fu_438_p1 = sext_ln1118_27_fu_12423_p1;

assign mul_ln1118_34_fu_438_p2 = ($signed({{1'b0}, {24'd104}}) * $signed(mul_ln1118_34_fu_438_p1));

assign mul_ln1118_35_fu_476_p1 = sext_ln1118_32_fu_12463_p1;

assign mul_ln1118_35_fu_476_p2 = ($signed({{1'b0}, {24'd67}}) * $signed(mul_ln1118_35_fu_476_p1));

assign mul_ln1118_36_fu_454_p1 = sext_ln1118_35_fu_12504_p1;

assign mul_ln1118_36_fu_454_p2 = ($signed({{1'b0}, {24'd93}}) * $signed(mul_ln1118_36_fu_454_p1));

assign mul_ln1118_37_fu_480_p1 = sext_ln1118_36_fu_12521_p0;

assign mul_ln1118_37_fu_480_p2 = ($signed(24'd16777107) * $signed(mul_ln1118_37_fu_480_p1));

assign mul_ln1118_45_fu_463_p1 = sext_ln1118_12_fu_12316_p0;

assign mul_ln1118_45_fu_463_p2 = ($signed(24'd16776812) * $signed(mul_ln1118_45_fu_463_p1));

assign mul_ln1118_47_fu_487_p1 = sext_ln1118_16_fu_12327_p1;

assign mul_ln1118_47_fu_487_p2 = ($signed({{1'b0}, {24'd71}}) * $signed(mul_ln1118_47_fu_487_p1));

assign mul_ln1118_48_fu_447_p1 = sext_ln1118_17_fu_12345_p1;

assign mul_ln1118_48_fu_447_p2 = ($signed({{1'b0}, {24'd79}}) * $signed(mul_ln1118_48_fu_447_p1));

assign mul_ln1118_49_fu_469_p1 = sext_ln1118_22_fu_12372_p0;

assign mul_ln1118_49_fu_469_p2 = ($signed({{1'b0}, {22'd26}}) * $signed(mul_ln1118_49_fu_469_p1));

assign mul_ln1118_4_fu_456_p1 = sext_ln1118_10_fu_12294_p1;

assign mul_ln1118_4_fu_456_p2 = ($signed({{1'b0}, {24'd83}}) * $signed(mul_ln1118_4_fu_456_p1));

assign mul_ln1118_51_fu_471_p1 = sext_ln1118_27_fu_12423_p1;

assign mul_ln1118_51_fu_471_p2 = ($signed(24'd16777055) * $signed(mul_ln1118_51_fu_471_p1));

assign mul_ln1118_54_fu_449_p1 = sext_ln1118_32_fu_12463_p1;

assign mul_ln1118_54_fu_449_p2 = ($signed(24'd16776977) * $signed(mul_ln1118_54_fu_449_p1));

assign mul_ln1118_56_fu_478_p1 = sext_ln1118_37_fu_12528_p1;

assign mul_ln1118_56_fu_478_p2 = ($signed(24'd16777093) * $signed(mul_ln1118_56_fu_478_p1));

assign mul_ln1118_61_fu_482_p1 = sext_ln1118_11_fu_12311_p0;

assign mul_ln1118_61_fu_482_p2 = ($signed(21'd2097139) * $signed(mul_ln1118_61_fu_482_p1));

assign mul_ln1118_63_fu_442_p1 = sext_ln1118_17_fu_12345_p1;

assign mul_ln1118_63_fu_442_p2 = ($signed(24'd16777069) * $signed(mul_ln1118_63_fu_442_p1));

assign mul_ln1118_67_fu_443_p1 = sext_ln1118_32_fu_12463_p1;

assign mul_ln1118_67_fu_443_p2 = ($signed(24'd16777060) * $signed(mul_ln1118_67_fu_443_p1));

assign mul_ln1118_68_fu_481_p1 = sext_ln1118_35_fu_12504_p1;

assign mul_ln1118_68_fu_481_p2 = ($signed({{1'b0}, {24'd122}}) * $signed(mul_ln1118_68_fu_481_p1));

assign mul_ln1118_69_fu_445_p1 = sext_ln1118_37_fu_12528_p1;

assign mul_ln1118_69_fu_445_p2 = ($signed({{1'b0}, {24'd101}}) * $signed(mul_ln1118_69_fu_445_p1));

assign mul_ln1118_6_fu_470_p1 = sext_ln1118_16_fu_12327_p1;

assign mul_ln1118_6_fu_470_p2 = ($signed(24'd16777054) * $signed(mul_ln1118_6_fu_470_p1));

assign mul_ln1118_8_fu_483_p1 = sext_ln1118_27_fu_12423_p1;

assign mul_ln1118_8_fu_483_p2 = ($signed(24'd16776789) * $signed(mul_ln1118_8_fu_483_p1));

assign mul_ln1118_9_fu_479_p1 = sext_ln1118_31_fu_12447_p0;

assign mul_ln1118_9_fu_479_p2 = ($signed(24'd16777135) * $signed(mul_ln1118_9_fu_479_p1));

assign mul_ln1118_fu_451_p1 = sext_ln1118_1_fu_12193_p0;

assign mul_ln1118_fu_451_p2 = ($signed({{1'b0}, {24'd115}}) * $signed(mul_ln1118_fu_451_p1));

assign mult_10_V_fu_13136_p1 = $signed(trunc_ln708_7_fu_13126_p4);

assign mult_11_V_fu_13140_p1 = $signed(trunc_ln708_8_reg_14625);

assign mult_13_V_fu_13181_p1 = $signed(trunc_ln708_s_fu_13171_p4);

assign mult_15_V_fu_13185_p1 = $signed(trunc_ln708_2_reg_14646);

assign mult_16_V_fu_13188_p1 = $signed(trunc_ln708_3_reg_14651);

assign mult_24_V_fu_13269_p1 = $signed(trunc_ln708_5_fu_13259_p4);

assign mult_29_V_fu_13273_p1 = $signed(trunc_ln708_9_reg_14693);

assign mult_30_V_fu_13276_p1 = $signed(trunc_ln708_10_reg_14698);

assign mult_34_V_fu_13317_p1 = $signed(trunc_ln708_11_fu_13307_p4);

assign mult_38_V_fu_13321_p1 = $signed(trunc_ln708_12_reg_14718);

assign mult_3_V_fu_13060_p1 = $signed(trunc_ln_reg_14579);

assign mult_43_V_fu_14034_p1 = $signed(trunc_ln708_13_reg_14848);

assign mult_47_V_fu_13416_p4 = {{add_ln1118_6_fu_13410_p2[23:8]}};

assign mult_49_V_fu_13426_p1 = $signed(trunc_ln708_14_reg_14728);

assign mult_4_V_fu_13063_p1 = $signed(trunc_ln708_1_reg_14584);

assign mult_50_V_fu_13467_p1 = $signed(trunc_ln708_15_fu_13457_p4);

assign mult_53_V_fu_13504_p1 = $signed(trunc_ln708_16_fu_13494_p4);

assign mult_54_V_fu_13524_p1 = $signed(trunc_ln708_17_fu_13514_p4);

assign mult_60_V_fu_14037_p1 = $signed(trunc_ln708_18_reg_14853);

assign mult_64_V_fu_14040_p1 = $signed(trunc_ln708_19_reg_14858);

assign mult_70_V_fu_13565_p1 = $signed(trunc_ln708_20_reg_14768);

assign mult_76_V_fu_13592_p4 = {{sub_ln1118_15_fu_13586_p2[23:8]}};

assign mult_79_V_fu_13618_p4 = {{sub_ln1118_20_fu_13613_p2[23:8]}};

assign mult_7_V_fu_13096_p1 = $signed(trunc_ln708_4_fu_13086_p4);

assign mult_83_V_fu_14043_p1 = $signed(trunc_ln708_21_reg_14868);

assign mult_86_V_fu_13682_p1 = $signed(trunc_ln708_22_reg_14788);

assign mult_90_V_fu_13702_p4 = {{sub_ln1118_21_fu_13696_p2[23:8]}};

assign mult_94_V_fu_13739_p1 = $signed(trunc_ln708_23_fu_13729_p4);

assign mult_9_V_fu_13100_p1 = $signed(trunc_ln708_6_reg_14615);

assign sext_ln1118_10_fu_12294_p0 = data_5_V_read;

assign sext_ln1118_10_fu_12294_p1 = sext_ln1118_10_fu_12294_p0;

assign sext_ln1118_11_fu_12311_p0 = data_6_V_read;

assign sext_ln1118_12_fu_12316_p0 = data_6_V_read;

assign sext_ln1118_12_fu_12316_p1 = sext_ln1118_12_fu_12316_p0;

assign sext_ln1118_13_fu_12322_p0 = data_7_V_read;

assign sext_ln1118_13_fu_12322_p1 = sext_ln1118_13_fu_12322_p0;

assign sext_ln1118_14_fu_13066_p1 = data_7_V_read_5_reg_14517;

assign sext_ln1118_15_fu_13076_p1 = $signed(shl_ln1118_2_fu_13069_p3);

assign sext_ln1118_16_fu_12327_p0 = data_8_V_read;

assign sext_ln1118_16_fu_12327_p1 = sext_ln1118_16_fu_12327_p0;

assign sext_ln1118_17_fu_12345_p0 = data_9_V_read;

assign sext_ln1118_17_fu_12345_p1 = sext_ln1118_17_fu_12345_p0;

assign sext_ln1118_18_fu_12351_p0 = data_9_V_read;

assign sext_ln1118_18_fu_12351_p1 = sext_ln1118_18_fu_12351_p0;

assign sext_ln1118_19_fu_13103_p1 = data_10_V_read11_reg_14507;

assign sext_ln1118_1_fu_12193_p0 = data_0_V_read;

assign sext_ln1118_1_fu_12193_p1 = sext_ln1118_1_fu_12193_p0;

assign sext_ln1118_20_fu_12367_p0 = data_10_V_read;

assign sext_ln1118_21_fu_13106_p1 = data_10_V_read11_reg_14507;

assign sext_ln1118_22_fu_12372_p0 = data_10_V_read;

assign sext_ln1118_23_fu_13116_p1 = $signed(shl_ln1118_3_fu_13109_p3);

assign sext_ln1118_24_fu_12377_p0 = data_11_V_read;

assign sext_ln1118_24_fu_12377_p1 = sext_ln1118_24_fu_12377_p0;

assign sext_ln1118_25_fu_12391_p1 = $signed(shl_ln1118_4_fu_12383_p3);

assign sext_ln1118_26_fu_12403_p1 = $signed(shl_ln1118_5_fu_12395_p3);

assign sext_ln1118_27_fu_12423_p1 = $signed(data_12_V_read);

assign sext_ln1118_28_fu_12442_p0 = data_13_V_read;

assign sext_ln1118_28_fu_12442_p1 = sext_ln1118_28_fu_12442_p0;

assign sext_ln1118_29_fu_13150_p1 = $signed(shl_ln1118_6_fu_13143_p3);

assign sext_ln1118_2_fu_12208_p0 = data_1_V_read;

assign sext_ln1118_2_fu_12208_p1 = sext_ln1118_2_fu_12208_p0;

assign sext_ln1118_30_fu_13161_p1 = $signed(shl_ln1118_7_fu_13154_p3);

assign sext_ln1118_31_fu_12447_p0 = data_14_V_read;

assign sext_ln1118_31_fu_12447_p1 = sext_ln1118_31_fu_12447_p0;

assign sext_ln1118_32_fu_12463_p0 = data_15_V_read;

assign sext_ln1118_32_fu_12463_p1 = sext_ln1118_32_fu_12463_p0;

assign sext_ln1118_33_fu_12479_p1 = $signed(shl_ln1118_8_fu_12471_p3);

assign sext_ln1118_34_fu_12499_p0 = data_16_V_read;

assign sext_ln1118_34_fu_12499_p1 = sext_ln1118_34_fu_12499_p0;

assign sext_ln1118_35_fu_12504_p0 = data_16_V_read;

assign sext_ln1118_35_fu_12504_p1 = sext_ln1118_35_fu_12504_p0;

assign sext_ln1118_36_fu_12521_p0 = data_17_V_read;

assign sext_ln1118_36_fu_12521_p1 = sext_ln1118_36_fu_12521_p0;

assign sext_ln1118_37_fu_12528_p0 = data_18_V_read;

assign sext_ln1118_37_fu_12528_p1 = sext_ln1118_37_fu_12528_p0;

assign sext_ln1118_38_fu_12536_p0 = data_19_V_read;

assign sext_ln1118_38_fu_12536_p1 = sext_ln1118_38_fu_12536_p0;

assign sext_ln1118_39_fu_13198_p1 = $signed(shl_ln1118_9_fu_13191_p3);

assign sext_ln1118_3_fu_12213_p0 = data_2_V_read;

assign sext_ln1118_3_fu_12213_p1 = sext_ln1118_3_fu_12213_p0;

assign sext_ln1118_40_fu_13215_p1 = $signed(shl_ln1118_s_fu_13208_p3);

assign sext_ln1118_41_fu_12559_p1 = $signed(shl_ln1118_10_fu_12551_p3);

assign sext_ln1118_42_fu_12571_p1 = $signed(shl_ln1118_11_fu_12563_p3);

assign sext_ln1118_43_fu_13249_p1 = $signed(shl_ln1118_12_fu_13242_p3);

assign sext_ln1118_44_fu_13286_p1 = $signed(shl_ln1118_13_fu_13279_p3);

assign sext_ln1118_45_fu_13297_p1 = $signed(shl_ln1118_14_fu_13290_p3);

assign sext_ln1118_46_fu_12679_p1 = $signed(shl_ln1118_15_fu_12671_p3);

assign sext_ln1118_47_fu_12691_p1 = $signed(shl_ln1118_16_fu_12683_p3);

assign sext_ln1118_48_fu_13331_p1 = $signed(shl_ln1118_17_fu_13324_p3);

assign sext_ln1118_49_fu_13348_p1 = $signed(shl_ln1118_18_fu_13341_p3);

assign sext_ln1118_4_fu_13055_p1 = data_3_V_read_4_reg_14533;

assign sext_ln1118_50_fu_12737_p1 = $signed(shl_ln1118_20_fu_12729_p3);

assign sext_ln1118_51_fu_13395_p1 = $signed(shl_ln1118_21_fu_13388_p3);

assign sext_ln1118_52_fu_13406_p1 = $signed(shl_ln1118_22_fu_13399_p3);

assign sext_ln1118_53_fu_12765_p1 = $signed(shl_ln1118_23_fu_12757_p3);

assign sext_ln1118_54_fu_12777_p1 = $signed(shl_ln1118_24_fu_12769_p3);

assign sext_ln1118_55_fu_13436_p1 = $signed(shl_ln1118_25_fu_13429_p3);

assign sext_ln1118_56_fu_13447_p1 = $signed(shl_ln1118_26_fu_13440_p3);

assign sext_ln1118_57_fu_13484_p1 = $signed(shl_ln1118_27_fu_13477_p3);

assign sext_ln1118_58_fu_13545_p1 = $signed(shl_ln1118_28_fu_13538_p3);

assign sext_ln1118_59_fu_13582_p1 = $signed(shl_ln1118_30_fu_13575_p3);

assign sext_ln1118_5_fu_12229_p0 = data_3_V_read;

assign sext_ln1118_5_fu_12229_p1 = sext_ln1118_5_fu_12229_p0;

assign sext_ln1118_60_fu_13662_p1 = $signed(shl_ln1118_32_fu_13655_p3);

assign sext_ln1118_61_fu_13719_p1 = $signed(shl_ln1118_34_fu_13712_p3);

assign sext_ln1118_62_fu_12991_p1 = $signed(shl_ln1118_36_fu_12983_p3);

assign sext_ln1118_63_fu_13609_p1 = $signed(tmp_1_fu_13602_p3);

assign sext_ln1118_64_fu_13692_p1 = $signed(tmp_2_fu_13685_p3);

assign sext_ln1118_6_fu_12242_p1 = $signed(shl_ln_fu_12234_p3);

assign sext_ln1118_7_fu_12254_p1 = $signed(shl_ln1118_1_fu_12246_p3);

assign sext_ln1118_8_fu_12274_p0 = data_4_V_read;

assign sext_ln1118_8_fu_12274_p1 = sext_ln1118_8_fu_12274_p0;

assign sext_ln1118_9_fu_12279_p0 = data_4_V_read;

assign sext_ln1118_9_fu_12279_p1 = sext_ln1118_9_fu_12279_p0;

assign sext_ln1118_fu_13051_p1 = data_0_V_read_5_reg_14538;

assign sext_ln203_1_fu_13239_p1 = $signed(tmp_4_reg_14673);

assign sext_ln203_2_fu_14031_p1 = $signed(tmp_5_reg_14838);

assign sext_ln203_fu_13235_p1 = $signed(tmp_fu_13225_p4);

assign sext_ln703_1_fu_14112_p1 = $signed(add_ln703_41_fu_14106_p2);

assign sext_ln703_2_fu_14128_p1 = $signed(tmp_6_reg_14823);

assign sext_ln703_3_fu_14137_p1 = $signed(add_ln703_44_fu_14131_p2);

assign sext_ln703_4_fu_14214_p1 = $signed(tmp_7_reg_14828);

assign sext_ln703_5_fu_14223_p1 = $signed(add_ln703_67_fu_14217_p2);

assign sext_ln703_6_fu_14395_p1 = $signed(tmp_8_reg_14833);

assign sext_ln703_7_fu_14404_p1 = $signed(add_ln703_112_fu_14398_p2);

assign sext_ln703_fu_14066_p1 = $signed(add_ln703_24_reg_14898);

assign shl_ln1118_10_fu_12551_p1 = data_1_V_read;

assign shl_ln1118_10_fu_12551_p3 = {{shl_ln1118_10_fu_12551_p1}, {5'd0}};

assign shl_ln1118_11_fu_12563_p1 = data_1_V_read;

assign shl_ln1118_11_fu_12563_p3 = {{shl_ln1118_11_fu_12563_p1}, {3'd0}};

assign shl_ln1118_12_fu_13242_p3 = {{data_4_V_read_5_reg_14525}, {5'd0}};

assign shl_ln1118_13_fu_13279_p3 = {{data_14_V_read_3_reg_14493}, {4'd0}};

assign shl_ln1118_14_fu_13290_p3 = {{data_14_V_read_3_reg_14493}, {1'd0}};

assign shl_ln1118_15_fu_12671_p1 = data_18_V_read;

assign shl_ln1118_15_fu_12671_p3 = {{shl_ln1118_15_fu_12671_p1}, {3'd0}};

assign shl_ln1118_16_fu_12683_p1 = data_18_V_read;

assign shl_ln1118_16_fu_12683_p3 = {{shl_ln1118_16_fu_12683_p1}, {1'd0}};

assign shl_ln1118_17_fu_13324_p3 = {{data_19_V_read_3_reg_14480}, {4'd0}};

assign shl_ln1118_18_fu_13341_p3 = {{data_19_V_read_3_reg_14480}, {1'd0}};

assign shl_ln1118_19_fu_12715_p3 = {{trunc_ln1118_fu_12711_p1}, {9'd0}};

assign shl_ln1118_1_fu_12246_p1 = data_3_V_read;

assign shl_ln1118_1_fu_12246_p3 = {{shl_ln1118_1_fu_12246_p1}, {2'd0}};

assign shl_ln1118_20_fu_12729_p1 = data_5_V_read;

assign shl_ln1118_20_fu_12729_p3 = {{shl_ln1118_20_fu_12729_p1}, {6'd0}};

assign shl_ln1118_21_fu_13388_p3 = {{data_7_V_read_5_reg_14517}, {7'd0}};

assign shl_ln1118_22_fu_13399_p3 = {{data_7_V_read_5_reg_14517}, {4'd0}};

assign shl_ln1118_23_fu_12757_p1 = data_9_V_read;

assign shl_ln1118_23_fu_12757_p3 = {{shl_ln1118_23_fu_12757_p1}, {4'd0}};

assign shl_ln1118_24_fu_12769_p1 = data_9_V_read;

assign shl_ln1118_24_fu_12769_p3 = {{shl_ln1118_24_fu_12769_p1}, {1'd0}};

assign shl_ln1118_25_fu_13429_p3 = {{data_10_V_read11_reg_14507}, {6'd0}};

assign shl_ln1118_26_fu_13440_p3 = {{data_10_V_read11_reg_14507}, {2'd0}};

assign shl_ln1118_27_fu_13477_p3 = {{data_13_V_read_3_reg_14500}, {1'd0}};

assign shl_ln1118_28_fu_13538_p3 = {{data_4_V_read_5_reg_14525}, {3'd0}};

assign shl_ln1118_29_fu_13568_p3 = {{data_16_V_read_3_reg_14487}, {8'd0}};

assign shl_ln1118_2_fu_13069_p3 = {{data_7_V_read_5_reg_14517}, {6'd0}};

assign shl_ln1118_30_fu_13575_p3 = {{data_16_V_read_3_reg_14487}, {3'd0}};

assign shl_ln1118_31_fu_13648_p3 = {{data_4_V_read_5_reg_14525}, {8'd0}};

assign shl_ln1118_32_fu_13655_p3 = {{data_4_V_read_5_reg_14525}, {4'd0}};

assign shl_ln1118_33_fu_12917_p1 = data_8_V_read;

assign shl_ln1118_33_fu_12917_p3 = {{shl_ln1118_33_fu_12917_p1}, {8'd0}};

assign shl_ln1118_34_fu_13712_p3 = {{data_14_V_read_3_reg_14493}, {2'd0}};

assign shl_ln1118_35_fu_12975_p3 = {{trunc_ln1118_1_fu_12971_p1}, {9'd0}};

assign shl_ln1118_36_fu_12983_p1 = data_17_V_read;

assign shl_ln1118_36_fu_12983_p3 = {{shl_ln1118_36_fu_12983_p1}, {4'd0}};

assign shl_ln1118_3_fu_13109_p3 = {{data_10_V_read11_reg_14507}, {3'd0}};

assign shl_ln1118_4_fu_12383_p1 = data_11_V_read;

assign shl_ln1118_4_fu_12383_p3 = {{shl_ln1118_4_fu_12383_p1}, {4'd0}};

assign shl_ln1118_5_fu_12395_p1 = data_11_V_read;

assign shl_ln1118_5_fu_12395_p3 = {{shl_ln1118_5_fu_12395_p1}, {1'd0}};

assign shl_ln1118_6_fu_13143_p3 = {{data_13_V_read_3_reg_14500}, {6'd0}};

assign shl_ln1118_7_fu_13154_p3 = {{data_13_V_read_3_reg_14500}, {3'd0}};

assign shl_ln1118_8_fu_12471_p1 = data_15_V_read;

assign shl_ln1118_8_fu_12471_p3 = {{shl_ln1118_8_fu_12471_p1}, {6'd0}};

assign shl_ln1118_9_fu_13191_p3 = {{data_0_V_read_5_reg_14538}, {3'd0}};

assign shl_ln1118_s_fu_13208_p3 = {{data_0_V_read_5_reg_14538}, {1'd0}};

assign shl_ln_fu_12234_p1 = data_3_V_read;

assign shl_ln_fu_12234_p3 = {{shl_ln_fu_12234_p1}, {4'd0}};

assign sub_ln1118_10_fu_12781_p2 = ($signed(sext_ln1118_54_fu_12777_p1) - $signed(sext_ln1118_53_fu_12765_p1));

assign sub_ln1118_11_fu_13471_p2 = ($signed(23'd0) - $signed(sext_ln1118_29_fu_13150_p1));

assign sub_ln1118_12_fu_13488_p2 = ($signed(sub_ln1118_11_fu_13471_p2) - $signed(sext_ln1118_57_fu_13484_p1));

assign sub_ln1118_13_fu_13508_p2 = ($signed(sext_ln1118_45_fu_13297_p1) - $signed(sext_ln1118_44_fu_13286_p1));

assign sub_ln1118_14_fu_13549_p2 = ($signed(sub_ln1118_4_fu_13253_p2) - $signed(sext_ln1118_58_fu_13545_p1));

assign sub_ln1118_15_fu_13586_p2 = ($signed(sext_ln1118_59_fu_13582_p1) - $signed(shl_ln1118_29_fu_13568_p3));

assign sub_ln1118_16_fu_13666_p2 = ($signed(shl_ln1118_31_fu_13648_p3) - $signed(sext_ln1118_60_fu_13662_p1));

assign sub_ln1118_17_fu_12925_p2 = ($signed(shl_ln1118_33_fu_12917_p3) - $signed(sext_ln1118_16_fu_12327_p1));

assign sub_ln1118_18_fu_13723_p2 = ($signed(sext_ln1118_61_fu_13719_p1) - $signed(sext_ln1118_44_fu_13286_p1));

assign sub_ln1118_19_fu_12995_p2 = ($signed(sext_ln1118_62_fu_12991_p1) - $signed(shl_ln1118_35_fu_12975_p3));

assign sub_ln1118_1_fu_12483_p2 = ($signed(23'd0) - $signed(sext_ln1118_33_fu_12479_p1));

assign sub_ln1118_20_fu_13613_p2 = ($signed(sext_ln1118_38_reg_14661) - $signed(sext_ln1118_63_fu_13609_p1));

assign sub_ln1118_21_fu_13696_p2 = ($signed(sext_ln1118_19_fu_13103_p1) - $signed(sext_ln1118_64_fu_13692_p1));

assign sub_ln1118_2_fu_13202_p2 = ($signed(20'd0) - $signed(sext_ln1118_39_fu_13198_p1));

assign sub_ln1118_3_fu_13219_p2 = ($signed(sub_ln1118_2_fu_13202_p2) - $signed(sext_ln1118_40_fu_13215_p1));

assign sub_ln1118_4_fu_13253_p2 = ($signed(22'd0) - $signed(sext_ln1118_43_fu_13249_p1));

assign sub_ln1118_5_fu_13301_p2 = ($signed(sext_ln1118_44_fu_13286_p1) - $signed(sext_ln1118_45_fu_13297_p1));

assign sub_ln1118_6_fu_13335_p2 = ($signed(21'd0) - $signed(sext_ln1118_48_fu_13331_p1));

assign sub_ln1118_7_fu_13352_p2 = ($signed(sub_ln1118_6_fu_13335_p2) - $signed(sext_ln1118_49_fu_13348_p1));

assign sub_ln1118_8_fu_12723_p2 = (24'd0 - shl_ln1118_19_fu_12715_p3);

assign sub_ln1118_9_fu_12741_p2 = ($signed(sub_ln1118_8_fu_12723_p2) - $signed(sext_ln1118_50_fu_12737_p1));

assign sub_ln1118_fu_13080_p2 = ($signed(sext_ln1118_15_fu_13076_p1) - $signed(sext_ln1118_14_fu_13066_p1));

assign tmp_1_fu_13602_p3 = {{data_19_V_read_3_reg_14480}, {7'd0}};

assign tmp_2_fu_13685_p3 = {{data_10_V_read11_reg_14507}, {7'd0}};

assign tmp_6_fu_13021_p1 = data_7_V_read;

assign tmp_7_fu_13031_p1 = data_11_V_read;

assign tmp_8_fu_13041_p1 = data_2_V_read;

assign tmp_fu_13225_p4 = {{sub_ln1118_3_fu_13219_p2[19:8]}};

assign trunc_ln1118_1_fu_12971_p0 = data_17_V_read;

assign trunc_ln1118_1_fu_12971_p1 = trunc_ln1118_1_fu_12971_p0[14:0];

assign trunc_ln1118_fu_12711_p0 = data_5_V_read;

assign trunc_ln1118_fu_12711_p1 = trunc_ln1118_fu_12711_p0[14:0];

assign trunc_ln708_11_fu_13307_p4 = {{sub_ln1118_5_fu_13301_p2[20:8]}};

assign trunc_ln708_13_fu_13378_p1 = grp_fu_455_p2;

assign trunc_ln708_15_fu_13457_p4 = {{add_ln1118_7_fu_13451_p2[22:8]}};

assign trunc_ln708_16_fu_13494_p4 = {{sub_ln1118_12_fu_13488_p2[22:8]}};

assign trunc_ln708_17_fu_13514_p4 = {{sub_ln1118_13_fu_13508_p2[20:8]}};

assign trunc_ln708_18_fu_13528_p1 = grp_fu_450_p2;

assign trunc_ln708_21_fu_13638_p1 = grp_fu_459_p2;

assign trunc_ln708_23_fu_13729_p4 = {{sub_ln1118_18_fu_13723_p2[20:8]}};

assign trunc_ln708_3_fu_12511_p1 = grp_fu_477_p2;

assign trunc_ln708_4_fu_13086_p4 = {{sub_ln1118_fu_13080_p2[22:8]}};

assign trunc_ln708_5_fu_13259_p4 = {{sub_ln1118_4_fu_13253_p2[21:8]}};

assign trunc_ln708_6_fu_12357_p1 = grp_fu_448_p2;

assign trunc_ln708_7_fu_13126_p4 = {{add_ln1118_1_fu_13120_p2[19:8]}};

assign trunc_ln708_s_fu_13171_p4 = {{add_ln1118_3_fu_13165_p2[22:8]}};

endmodule //pointwise_conv_1d_cl_0_0_0_0_0_0
