name: b_tag
channels:
  - conda-forge
  - defaults
dependencies:
  - root=6.24.0
  - python=3.6
  - tensorflow
  - keras
  - scikit-learn
  - matplotlib
  - numpy
  - pip=20.3.3
  - pip:
    - h5py==2.10.0
    - scipy==1.5.4
    - mplhep
    - git+https://github.com/fastmachinelearning/hls4ml.git
