name: b_tag
dependencies:
  - python=3.8
  - tensorflow
  - keras
  - scikit-learn
  - matplotlib
  - numpy
  - pip
  - pip:
    - h5py==2.10.0
    - scipy==1.5.4
    - mplhep
#    - git+https://github.com/Keb-L/hls4ml.git@cnn_merge
