// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _dense_latency_ap_fixed_ap_fixed_config11_0_0_HH_
#define _dense_latency_ap_fixed_ap_fixed_config11_0_0_HH_

#include "systemc.h"
#include "AESL_pkg.h"


namespace ap_rtl {

struct dense_latency_ap_fixed_ap_fixed_config11_0_0 : public sc_module {
    // Port declarations 18
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_in< sc_lv<16> > data_0_V_read;
    sc_in< sc_lv<16> > data_1_V_read;
    sc_in< sc_lv<16> > data_2_V_read;
    sc_in< sc_lv<16> > data_3_V_read;
    sc_in< sc_lv<16> > data_4_V_read;
    sc_in< sc_lv<16> > data_5_V_read;
    sc_in< sc_lv<16> > data_6_V_read;
    sc_in< sc_lv<16> > data_7_V_read;
    sc_in< sc_lv<16> > data_8_V_read;
    sc_in< sc_lv<16> > data_9_V_read;
    sc_out< sc_lv<16> > ap_return;
    sc_in< sc_logic > ap_ce;


    // Module declarations
    dense_latency_ap_fixed_ap_fixed_config11_0_0(sc_module_name name);
    SC_HAS_PROCESS(dense_latency_ap_fixed_ap_fixed_config11_0_0);

    ~dense_latency_ap_fixed_ap_fixed_config11_0_0();

    sc_trace_file* mVcdFile;

    sc_signal< sc_lv<4> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_lv<16> > reg_227;
    sc_signal< sc_logic > ap_CS_fsm_state3;
    sc_signal< sc_lv<15> > trunc_ln708_s_reg_556;
    sc_signal< sc_lv<16> > trunc_ln708_4_reg_561;
    sc_signal< sc_logic > ap_CS_fsm_state2;
    sc_signal< sc_lv<16> > trunc_ln708_6_reg_566;
    sc_signal< sc_lv<14> > trunc_ln708_26_reg_571;
    sc_signal< sc_lv<16> > add_ln703_fu_415_p2;
    sc_signal< sc_lv<16> > add_ln703_reg_576;
    sc_signal< sc_lv<16> > add_ln703_119_fu_426_p2;
    sc_signal< sc_lv<16> > add_ln703_119_reg_581;
    sc_signal< sc_lv<16> > ap_port_reg_data_0_V_read;
    sc_signal< sc_lv<16> > ap_port_reg_data_3_V_read;
    sc_signal< sc_lv<16> > ap_port_reg_data_4_V_read;
    sc_signal< sc_lv<16> > ap_port_reg_data_5_V_read;
    sc_signal< sc_lv<16> > ap_port_reg_data_6_V_read;
    sc_signal< sc_lv<16> > ap_port_reg_data_7_V_read;
    sc_signal< sc_lv<16> > ap_port_reg_data_8_V_read;
    sc_signal< sc_lv<16> > ap_port_reg_data_9_V_read;
    sc_signal< sc_logic > ap_CS_fsm_state4;
    sc_signal< sc_lv<16> > grp_fu_166_p0;
    sc_signal< sc_lv<24> > sext_ln1118_66_fu_231_p1;
    sc_signal< sc_lv<24> > sext_ln1118_70_fu_251_p1;
    sc_signal< sc_lv<24> > sext_ln1118_74_fu_370_p1;
    sc_signal< sc_lv<10> > grp_fu_166_p1;
    sc_signal< sc_lv<16> > grp_fu_167_p0;
    sc_signal< sc_lv<23> > sext_ln1118_67_fu_236_p1;
    sc_signal< sc_lv<24> > sext_ln1118_73_fu_256_p1;
    sc_signal< sc_lv<10> > grp_fu_167_p1;
    sc_signal< sc_lv<24> > grp_fu_166_p2;
    sc_signal< sc_lv<23> > trunc_ln708_s_fu_241_p1;
    sc_signal< sc_lv<24> > grp_fu_167_p2;
    sc_signal< sc_lv<23> > shl_ln_fu_271_p3;
    sc_signal< sc_lv<24> > sext_ln1118_fu_279_p1;
    sc_signal< sc_lv<21> > shl_ln1118_s_fu_289_p3;
    sc_signal< sc_lv<24> > sub_ln1118_fu_283_p2;
    sc_signal< sc_lv<24> > sext_ln1118_65_fu_297_p1;
    sc_signal< sc_lv<24> > sub_ln1118_22_fu_301_p2;
    sc_signal< sc_lv<22> > shl_ln1118_37_fu_320_p3;
    sc_signal< sc_lv<23> > sext_ln1118_68_fu_328_p1;
    sc_signal< sc_lv<17> > shl_ln1118_38_fu_338_p3;
    sc_signal< sc_lv<23> > sub_ln1118_23_fu_332_p2;
    sc_signal< sc_lv<23> > sext_ln1118_69_fu_346_p1;
    sc_signal< sc_lv<23> > sub_ln1118_24_fu_350_p2;
    sc_signal< sc_lv<15> > trunc_ln708_24_fu_356_p4;
    sc_signal< sc_lv<21> > shl_ln1118_42_fu_375_p3;
    sc_signal< sc_lv<18> > shl_ln1118_43_fu_387_p3;
    sc_signal< sc_lv<22> > sext_ln1118_78_fu_395_p1;
    sc_signal< sc_lv<22> > sext_ln1118_77_fu_383_p1;
    sc_signal< sc_lv<22> > sub_ln1118_28_fu_399_p2;
    sc_signal< sc_lv<16> > sext_ln708_1_fu_366_p1;
    sc_signal< sc_lv<16> > sext_ln708_fu_317_p1;
    sc_signal< sc_lv<16> > trunc_ln_fu_307_p4;
    sc_signal< sc_lv<16> > add_ln703_118_fu_421_p2;
    sc_signal< sc_lv<16> > sext_ln1118_71_fu_432_p0;
    sc_signal< sc_lv<16> > shl_ln1118_39_fu_436_p1;
    sc_signal< sc_lv<23> > shl_ln1118_39_fu_436_p3;
    sc_signal< sc_lv<24> > sext_ln1118_72_fu_444_p1;
    sc_signal< sc_lv<24> > sub_ln1118_25_fu_448_p2;
    sc_signal< sc_lv<24> > sext_ln1118_71_fu_432_p1;
    sc_signal< sc_lv<24> > sub_ln1118_26_fu_454_p2;
    sc_signal< sc_lv<22> > shl_ln1118_40_fu_470_p3;
    sc_signal< sc_lv<19> > shl_ln1118_41_fu_482_p3;
    sc_signal< sc_lv<23> > sext_ln1118_76_fu_490_p1;
    sc_signal< sc_lv<23> > sext_ln1118_75_fu_478_p1;
    sc_signal< sc_lv<23> > sub_ln1118_27_fu_494_p2;
    sc_signal< sc_lv<15> > trunc_ln708_25_fu_500_p4;
    sc_signal< sc_lv<16> > sext_ln708_3_fu_514_p1;
    sc_signal< sc_lv<16> > trunc_ln708_5_fu_460_p4;
    sc_signal< sc_lv<16> > add_ln703_115_fu_517_p2;
    sc_signal< sc_lv<16> > add_ln703_116_fu_523_p2;
    sc_signal< sc_lv<16> > sext_ln708_2_fu_510_p1;
    sc_signal< sc_lv<16> > add_ln703_120_fu_534_p2;
    sc_signal< sc_lv<16> > add_ln703_121_fu_540_p2;
    sc_signal< sc_lv<16> > add_ln703_117_fu_529_p2;
    sc_signal< sc_lv<16> > add_ln703_122_fu_545_p2;
    sc_signal< sc_lv<4> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<4> ap_ST_fsm_state1;
    static const sc_lv<4> ap_ST_fsm_state2;
    static const sc_lv<4> ap_ST_fsm_state3;
    static const sc_lv<4> ap_ST_fsm_state4;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<32> ap_const_lv32_3;
    static const sc_lv<24> ap_const_lv24_47;
    static const sc_lv<24> ap_const_lv24_FFFF3E;
    static const sc_lv<24> ap_const_lv24_EB;
    static const sc_lv<23> ap_const_lv23_7FFFCC;
    static const sc_lv<24> ap_const_lv24_A7;
    static const sc_lv<32> ap_const_lv32_8;
    static const sc_lv<32> ap_const_lv32_17;
    static const sc_lv<32> ap_const_lv32_16;
    static const sc_lv<7> ap_const_lv7_0;
    static const sc_lv<24> ap_const_lv24_0;
    static const sc_lv<5> ap_const_lv5_0;
    static const sc_lv<6> ap_const_lv6_0;
    static const sc_lv<23> ap_const_lv23_0;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<2> ap_const_lv2_0;
    static const sc_lv<32> ap_const_lv32_15;
    static const sc_lv<3> ap_const_lv3_0;
    static const sc_lv<16> ap_const_lv16_14;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_add_ln703_115_fu_517_p2();
    void thread_add_ln703_116_fu_523_p2();
    void thread_add_ln703_117_fu_529_p2();
    void thread_add_ln703_118_fu_421_p2();
    void thread_add_ln703_119_fu_426_p2();
    void thread_add_ln703_120_fu_534_p2();
    void thread_add_ln703_121_fu_540_p2();
    void thread_add_ln703_122_fu_545_p2();
    void thread_add_ln703_fu_415_p2();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state2();
    void thread_ap_CS_fsm_state3();
    void thread_ap_CS_fsm_state4();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_ap_return();
    void thread_grp_fu_166_p0();
    void thread_grp_fu_166_p1();
    void thread_grp_fu_166_p2();
    void thread_grp_fu_167_p0();
    void thread_grp_fu_167_p1();
    void thread_grp_fu_167_p2();
    void thread_sext_ln1118_65_fu_297_p1();
    void thread_sext_ln1118_66_fu_231_p1();
    void thread_sext_ln1118_67_fu_236_p1();
    void thread_sext_ln1118_68_fu_328_p1();
    void thread_sext_ln1118_69_fu_346_p1();
    void thread_sext_ln1118_70_fu_251_p1();
    void thread_sext_ln1118_71_fu_432_p0();
    void thread_sext_ln1118_71_fu_432_p1();
    void thread_sext_ln1118_72_fu_444_p1();
    void thread_sext_ln1118_73_fu_256_p1();
    void thread_sext_ln1118_74_fu_370_p1();
    void thread_sext_ln1118_75_fu_478_p1();
    void thread_sext_ln1118_76_fu_490_p1();
    void thread_sext_ln1118_77_fu_383_p1();
    void thread_sext_ln1118_78_fu_395_p1();
    void thread_sext_ln1118_fu_279_p1();
    void thread_sext_ln708_1_fu_366_p1();
    void thread_sext_ln708_2_fu_510_p1();
    void thread_sext_ln708_3_fu_514_p1();
    void thread_sext_ln708_fu_317_p1();
    void thread_shl_ln1118_37_fu_320_p3();
    void thread_shl_ln1118_38_fu_338_p3();
    void thread_shl_ln1118_39_fu_436_p1();
    void thread_shl_ln1118_39_fu_436_p3();
    void thread_shl_ln1118_40_fu_470_p3();
    void thread_shl_ln1118_41_fu_482_p3();
    void thread_shl_ln1118_42_fu_375_p3();
    void thread_shl_ln1118_43_fu_387_p3();
    void thread_shl_ln1118_s_fu_289_p3();
    void thread_shl_ln_fu_271_p3();
    void thread_sub_ln1118_22_fu_301_p2();
    void thread_sub_ln1118_23_fu_332_p2();
    void thread_sub_ln1118_24_fu_350_p2();
    void thread_sub_ln1118_25_fu_448_p2();
    void thread_sub_ln1118_26_fu_454_p2();
    void thread_sub_ln1118_27_fu_494_p2();
    void thread_sub_ln1118_28_fu_399_p2();
    void thread_sub_ln1118_fu_283_p2();
    void thread_trunc_ln708_24_fu_356_p4();
    void thread_trunc_ln708_25_fu_500_p4();
    void thread_trunc_ln708_5_fu_460_p4();
    void thread_trunc_ln708_s_fu_241_p1();
    void thread_trunc_ln_fu_307_p4();
    void thread_ap_NS_fsm();
};

}

using namespace ap_rtl;

#endif
