// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _relu_ap_fixed_ap_fixed_16_8_5_3_0_relu_config8_s_HH_
#define _relu_ap_fixed_ap_fixed_16_8_5_3_0_relu_config8_s_HH_

#include "systemc.h"
#include "AESL_pkg.h"


namespace ap_rtl {

struct relu_ap_fixed_ap_fixed_16_8_5_3_0_relu_config8_s : public sc_module {
    // Port declarations 47
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_in< sc_logic > ap_continue;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_in< sc_lv<16> > data_0_V_read;
    sc_in< sc_lv<16> > data_1_V_read;
    sc_in< sc_lv<16> > data_2_V_read;
    sc_in< sc_lv<16> > data_3_V_read;
    sc_in< sc_lv<16> > data_4_V_read;
    sc_in< sc_lv<16> > data_5_V_read;
    sc_in< sc_lv<16> > data_6_V_read;
    sc_in< sc_lv<16> > data_7_V_read;
    sc_in< sc_lv<16> > data_8_V_read;
    sc_in< sc_lv<16> > data_9_V_read;
    sc_in< sc_lv<16> > data_10_V_read;
    sc_in< sc_lv<16> > data_11_V_read;
    sc_in< sc_lv<16> > data_12_V_read;
    sc_in< sc_lv<16> > data_13_V_read;
    sc_in< sc_lv<16> > data_14_V_read;
    sc_in< sc_lv<16> > data_15_V_read;
    sc_in< sc_lv<16> > data_16_V_read;
    sc_in< sc_lv<16> > data_17_V_read;
    sc_in< sc_lv<16> > data_18_V_read;
    sc_in< sc_lv<16> > data_19_V_read;
    sc_out< sc_lv<15> > ap_return_0;
    sc_out< sc_lv<15> > ap_return_1;
    sc_out< sc_lv<15> > ap_return_2;
    sc_out< sc_lv<15> > ap_return_3;
    sc_out< sc_lv<15> > ap_return_4;
    sc_out< sc_lv<15> > ap_return_5;
    sc_out< sc_lv<15> > ap_return_6;
    sc_out< sc_lv<15> > ap_return_7;
    sc_out< sc_lv<15> > ap_return_8;
    sc_out< sc_lv<15> > ap_return_9;
    sc_out< sc_lv<15> > ap_return_10;
    sc_out< sc_lv<15> > ap_return_11;
    sc_out< sc_lv<15> > ap_return_12;
    sc_out< sc_lv<15> > ap_return_13;
    sc_out< sc_lv<15> > ap_return_14;
    sc_out< sc_lv<15> > ap_return_15;
    sc_out< sc_lv<15> > ap_return_16;
    sc_out< sc_lv<15> > ap_return_17;
    sc_out< sc_lv<15> > ap_return_18;
    sc_out< sc_lv<15> > ap_return_19;


    // Module declarations
    relu_ap_fixed_ap_fixed_16_8_5_3_0_relu_config8_s(sc_module_name name);
    SC_HAS_PROCESS(relu_ap_fixed_ap_fixed_16_8_5_3_0_relu_config8_s);

    ~relu_ap_fixed_ap_fixed_16_8_5_3_0_relu_config8_s();

    sc_trace_file* mVcdFile;

    sc_signal< sc_logic > ap_done_reg;
    sc_signal< sc_lv<1> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< bool > ap_block_state1;
    sc_signal< sc_lv<1> > icmp_ln1494_fu_188_p2;
    sc_signal< sc_lv<15> > trunc_ln1494_fu_184_p1;
    sc_signal< sc_lv<1> > icmp_ln1494_1_fu_206_p2;
    sc_signal< sc_lv<15> > trunc_ln1494_1_fu_202_p1;
    sc_signal< sc_lv<1> > icmp_ln1494_2_fu_224_p2;
    sc_signal< sc_lv<15> > trunc_ln1494_2_fu_220_p1;
    sc_signal< sc_lv<1> > icmp_ln1494_3_fu_242_p2;
    sc_signal< sc_lv<15> > trunc_ln1494_3_fu_238_p1;
    sc_signal< sc_lv<1> > icmp_ln1494_4_fu_260_p2;
    sc_signal< sc_lv<15> > trunc_ln1494_4_fu_256_p1;
    sc_signal< sc_lv<1> > icmp_ln1494_5_fu_278_p2;
    sc_signal< sc_lv<15> > trunc_ln1494_5_fu_274_p1;
    sc_signal< sc_lv<1> > icmp_ln1494_6_fu_296_p2;
    sc_signal< sc_lv<15> > trunc_ln1494_6_fu_292_p1;
    sc_signal< sc_lv<1> > icmp_ln1494_7_fu_314_p2;
    sc_signal< sc_lv<15> > trunc_ln1494_7_fu_310_p1;
    sc_signal< sc_lv<1> > icmp_ln1494_8_fu_332_p2;
    sc_signal< sc_lv<15> > trunc_ln1494_8_fu_328_p1;
    sc_signal< sc_lv<1> > icmp_ln1494_9_fu_350_p2;
    sc_signal< sc_lv<15> > trunc_ln1494_9_fu_346_p1;
    sc_signal< sc_lv<1> > icmp_ln1494_10_fu_368_p2;
    sc_signal< sc_lv<15> > trunc_ln1494_10_fu_364_p1;
    sc_signal< sc_lv<1> > icmp_ln1494_11_fu_386_p2;
    sc_signal< sc_lv<15> > trunc_ln1494_11_fu_382_p1;
    sc_signal< sc_lv<1> > icmp_ln1494_12_fu_404_p2;
    sc_signal< sc_lv<15> > trunc_ln1494_12_fu_400_p1;
    sc_signal< sc_lv<1> > icmp_ln1494_13_fu_422_p2;
    sc_signal< sc_lv<15> > trunc_ln1494_13_fu_418_p1;
    sc_signal< sc_lv<1> > icmp_ln1494_14_fu_440_p2;
    sc_signal< sc_lv<15> > trunc_ln1494_14_fu_436_p1;
    sc_signal< sc_lv<1> > icmp_ln1494_15_fu_458_p2;
    sc_signal< sc_lv<15> > trunc_ln1494_15_fu_454_p1;
    sc_signal< sc_lv<1> > icmp_ln1494_16_fu_476_p2;
    sc_signal< sc_lv<15> > trunc_ln1494_16_fu_472_p1;
    sc_signal< sc_lv<1> > icmp_ln1494_17_fu_494_p2;
    sc_signal< sc_lv<15> > trunc_ln1494_17_fu_490_p1;
    sc_signal< sc_lv<1> > icmp_ln1494_18_fu_512_p2;
    sc_signal< sc_lv<15> > trunc_ln1494_18_fu_508_p1;
    sc_signal< sc_lv<1> > icmp_ln1494_19_fu_530_p2;
    sc_signal< sc_lv<15> > trunc_ln1494_19_fu_526_p1;
    sc_signal< sc_lv<15> > select_ln81_fu_194_p3;
    sc_signal< sc_lv<15> > select_ln81_1_fu_212_p3;
    sc_signal< sc_lv<15> > select_ln81_2_fu_230_p3;
    sc_signal< sc_lv<15> > select_ln81_3_fu_248_p3;
    sc_signal< sc_lv<15> > select_ln81_4_fu_266_p3;
    sc_signal< sc_lv<15> > select_ln81_5_fu_284_p3;
    sc_signal< sc_lv<15> > select_ln81_6_fu_302_p3;
    sc_signal< sc_lv<15> > select_ln81_7_fu_320_p3;
    sc_signal< sc_lv<15> > select_ln81_8_fu_338_p3;
    sc_signal< sc_lv<15> > select_ln81_9_fu_356_p3;
    sc_signal< sc_lv<15> > select_ln81_10_fu_374_p3;
    sc_signal< sc_lv<15> > select_ln81_11_fu_392_p3;
    sc_signal< sc_lv<15> > select_ln81_12_fu_410_p3;
    sc_signal< sc_lv<15> > select_ln81_13_fu_428_p3;
    sc_signal< sc_lv<15> > select_ln81_14_fu_446_p3;
    sc_signal< sc_lv<15> > select_ln81_15_fu_464_p3;
    sc_signal< sc_lv<15> > select_ln81_16_fu_482_p3;
    sc_signal< sc_lv<15> > select_ln81_17_fu_500_p3;
    sc_signal< sc_lv<15> > select_ln81_18_fu_518_p3;
    sc_signal< sc_lv<15> > select_ln81_19_fu_536_p3;
    sc_signal< sc_lv<15> > ap_return_0_preg;
    sc_signal< sc_lv<15> > ap_return_1_preg;
    sc_signal< sc_lv<15> > ap_return_2_preg;
    sc_signal< sc_lv<15> > ap_return_3_preg;
    sc_signal< sc_lv<15> > ap_return_4_preg;
    sc_signal< sc_lv<15> > ap_return_5_preg;
    sc_signal< sc_lv<15> > ap_return_6_preg;
    sc_signal< sc_lv<15> > ap_return_7_preg;
    sc_signal< sc_lv<15> > ap_return_8_preg;
    sc_signal< sc_lv<15> > ap_return_9_preg;
    sc_signal< sc_lv<15> > ap_return_10_preg;
    sc_signal< sc_lv<15> > ap_return_11_preg;
    sc_signal< sc_lv<15> > ap_return_12_preg;
    sc_signal< sc_lv<15> > ap_return_13_preg;
    sc_signal< sc_lv<15> > ap_return_14_preg;
    sc_signal< sc_lv<15> > ap_return_15_preg;
    sc_signal< sc_lv<15> > ap_return_16_preg;
    sc_signal< sc_lv<15> > ap_return_17_preg;
    sc_signal< sc_lv<15> > ap_return_18_preg;
    sc_signal< sc_lv<15> > ap_return_19_preg;
    sc_signal< sc_lv<1> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<1> ap_ST_fsm_state1;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<16> ap_const_lv16_0;
    static const sc_lv<15> ap_const_lv15_0;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_ap_CS_fsm_state1();
    void thread_ap_block_state1();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_ap_return_0();
    void thread_ap_return_1();
    void thread_ap_return_10();
    void thread_ap_return_11();
    void thread_ap_return_12();
    void thread_ap_return_13();
    void thread_ap_return_14();
    void thread_ap_return_15();
    void thread_ap_return_16();
    void thread_ap_return_17();
    void thread_ap_return_18();
    void thread_ap_return_19();
    void thread_ap_return_2();
    void thread_ap_return_3();
    void thread_ap_return_4();
    void thread_ap_return_5();
    void thread_ap_return_6();
    void thread_ap_return_7();
    void thread_ap_return_8();
    void thread_ap_return_9();
    void thread_icmp_ln1494_10_fu_368_p2();
    void thread_icmp_ln1494_11_fu_386_p2();
    void thread_icmp_ln1494_12_fu_404_p2();
    void thread_icmp_ln1494_13_fu_422_p2();
    void thread_icmp_ln1494_14_fu_440_p2();
    void thread_icmp_ln1494_15_fu_458_p2();
    void thread_icmp_ln1494_16_fu_476_p2();
    void thread_icmp_ln1494_17_fu_494_p2();
    void thread_icmp_ln1494_18_fu_512_p2();
    void thread_icmp_ln1494_19_fu_530_p2();
    void thread_icmp_ln1494_1_fu_206_p2();
    void thread_icmp_ln1494_2_fu_224_p2();
    void thread_icmp_ln1494_3_fu_242_p2();
    void thread_icmp_ln1494_4_fu_260_p2();
    void thread_icmp_ln1494_5_fu_278_p2();
    void thread_icmp_ln1494_6_fu_296_p2();
    void thread_icmp_ln1494_7_fu_314_p2();
    void thread_icmp_ln1494_8_fu_332_p2();
    void thread_icmp_ln1494_9_fu_350_p2();
    void thread_icmp_ln1494_fu_188_p2();
    void thread_select_ln81_10_fu_374_p3();
    void thread_select_ln81_11_fu_392_p3();
    void thread_select_ln81_12_fu_410_p3();
    void thread_select_ln81_13_fu_428_p3();
    void thread_select_ln81_14_fu_446_p3();
    void thread_select_ln81_15_fu_464_p3();
    void thread_select_ln81_16_fu_482_p3();
    void thread_select_ln81_17_fu_500_p3();
    void thread_select_ln81_18_fu_518_p3();
    void thread_select_ln81_19_fu_536_p3();
    void thread_select_ln81_1_fu_212_p3();
    void thread_select_ln81_2_fu_230_p3();
    void thread_select_ln81_3_fu_248_p3();
    void thread_select_ln81_4_fu_266_p3();
    void thread_select_ln81_5_fu_284_p3();
    void thread_select_ln81_6_fu_302_p3();
    void thread_select_ln81_7_fu_320_p3();
    void thread_select_ln81_8_fu_338_p3();
    void thread_select_ln81_9_fu_356_p3();
    void thread_select_ln81_fu_194_p3();
    void thread_trunc_ln1494_10_fu_364_p1();
    void thread_trunc_ln1494_11_fu_382_p1();
    void thread_trunc_ln1494_12_fu_400_p1();
    void thread_trunc_ln1494_13_fu_418_p1();
    void thread_trunc_ln1494_14_fu_436_p1();
    void thread_trunc_ln1494_15_fu_454_p1();
    void thread_trunc_ln1494_16_fu_472_p1();
    void thread_trunc_ln1494_17_fu_490_p1();
    void thread_trunc_ln1494_18_fu_508_p1();
    void thread_trunc_ln1494_19_fu_526_p1();
    void thread_trunc_ln1494_1_fu_202_p1();
    void thread_trunc_ln1494_2_fu_220_p1();
    void thread_trunc_ln1494_3_fu_238_p1();
    void thread_trunc_ln1494_4_fu_256_p1();
    void thread_trunc_ln1494_5_fu_274_p1();
    void thread_trunc_ln1494_6_fu_292_p1();
    void thread_trunc_ln1494_7_fu_310_p1();
    void thread_trunc_ln1494_8_fu_328_p1();
    void thread_trunc_ln1494_9_fu_346_p1();
    void thread_trunc_ln1494_fu_184_p1();
    void thread_ap_NS_fsm();
};

}

using namespace ap_rtl;

#endif
