// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "dense_latency_ap_fixed_ap_fixed_config10_0_0.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic dense_latency_ap_fixed_ap_fixed_config10_0_0::ap_const_logic_1 = sc_dt::Log_1;
const bool dense_latency_ap_fixed_ap_fixed_config10_0_0::ap_const_boolean_1 = true;
const sc_lv<24> dense_latency_ap_fixed_ap_fixed_config10_0_0::ap_const_lv24_57 = "1010111";
const sc_lv<24> dense_latency_ap_fixed_ap_fixed_config10_0_0::ap_const_lv24_5F = "1011111";
const sc_lv<24> dense_latency_ap_fixed_ap_fixed_config10_0_0::ap_const_lv24_FFFF92 = "111111111111111110010010";
const sc_lv<24> dense_latency_ap_fixed_ap_fixed_config10_0_0::ap_const_lv24_FFFFB6 = "111111111111111110110110";
const sc_lv<24> dense_latency_ap_fixed_ap_fixed_config10_0_0::ap_const_lv24_FFFF50 = "111111111111111101010000";
const sc_lv<24> dense_latency_ap_fixed_ap_fixed_config10_0_0::ap_const_lv24_47 = "1000111";
const sc_lv<24> dense_latency_ap_fixed_ap_fixed_config10_0_0::ap_const_lv24_D4 = "11010100";
const sc_lv<24> dense_latency_ap_fixed_ap_fixed_config10_0_0::ap_const_lv24_9D = "10011101";
const sc_lv<24> dense_latency_ap_fixed_ap_fixed_config10_0_0::ap_const_lv24_FFFFBB = "111111111111111110111011";
const sc_lv<32> dense_latency_ap_fixed_ap_fixed_config10_0_0::ap_const_lv32_8 = "1000";
const sc_lv<32> dense_latency_ap_fixed_ap_fixed_config10_0_0::ap_const_lv32_17 = "10111";
const sc_lv<3> dense_latency_ap_fixed_ap_fixed_config10_0_0::ap_const_lv3_0 = "000";
const sc_lv<1> dense_latency_ap_fixed_ap_fixed_config10_0_0::ap_const_lv1_0 = "0";
const sc_lv<32> dense_latency_ap_fixed_ap_fixed_config10_0_0::ap_const_lv32_13 = "10011";
const sc_lv<16> dense_latency_ap_fixed_ap_fixed_config10_0_0::ap_const_lv16_6 = "110";
const sc_logic dense_latency_ap_fixed_ap_fixed_config10_0_0::ap_const_logic_0 = sc_dt::Log_0;

dense_latency_ap_fixed_ap_fixed_config10_0_0::dense_latency_ap_fixed_ap_fixed_config10_0_0(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_add_ln1118_fu_709_p2);
    sensitive << ( sext_ln1118_7_fu_693_p1 );
    sensitive << ( sext_ln1118_8_fu_705_p1 );

    SC_METHOD(thread_add_ln703_1_fu_765_p2);
    sensitive << ( trunc_ln708_4_fu_645_p4 );
    sensitive << ( trunc_ln708_3_fu_630_p4 );

    SC_METHOD(thread_add_ln703_2_fu_771_p2);
    sensitive << ( trunc_ln708_2_fu_615_p4 );
    sensitive << ( add_ln703_1_fu_765_p2 );

    SC_METHOD(thread_add_ln703_3_fu_777_p2);
    sensitive << ( add_ln703_fu_759_p2 );
    sensitive << ( add_ln703_2_fu_771_p2 );

    SC_METHOD(thread_add_ln703_4_fu_783_p2);
    sensitive << ( sext_ln708_fu_725_p1 );
    sensitive << ( trunc_ln708_6_fu_675_p4 );

    SC_METHOD(thread_add_ln703_5_fu_789_p2);
    sensitive << ( trunc_ln708_5_fu_660_p4 );
    sensitive << ( add_ln703_4_fu_783_p2 );

    SC_METHOD(thread_add_ln703_6_fu_795_p2);
    sensitive << ( trunc_ln708_9_fu_749_p4 );

    SC_METHOD(thread_add_ln703_7_fu_801_p2);
    sensitive << ( trunc_ln708_8_fu_734_p4 );
    sensitive << ( add_ln703_6_fu_795_p2 );

    SC_METHOD(thread_add_ln703_8_fu_807_p2);
    sensitive << ( add_ln703_5_fu_789_p2 );
    sensitive << ( add_ln703_7_fu_801_p2 );

    SC_METHOD(thread_add_ln703_fu_759_p2);
    sensitive << ( trunc_ln708_1_fu_600_p4 );
    sensitive << ( trunc_ln_fu_585_p4 );

    SC_METHOD(thread_ap_ready);

    SC_METHOD(thread_ap_return);
    sensitive << ( add_ln703_3_fu_777_p2 );
    sensitive << ( add_ln703_8_fu_807_p2 );

    SC_METHOD(thread_mul_ln1118_1_fu_153_p0);
    sensitive << ( data_1_V_read );

    SC_METHOD(thread_mul_ln1118_1_fu_153_p2);
    sensitive << ( mul_ln1118_1_fu_153_p0 );

    SC_METHOD(thread_mul_ln1118_2_fu_149_p0);
    sensitive << ( data_2_V_read );

    SC_METHOD(thread_mul_ln1118_2_fu_149_p2);
    sensitive << ( mul_ln1118_2_fu_149_p0 );

    SC_METHOD(thread_mul_ln1118_3_fu_147_p0);
    sensitive << ( data_3_V_read );

    SC_METHOD(thread_mul_ln1118_3_fu_147_p2);
    sensitive << ( mul_ln1118_3_fu_147_p0 );

    SC_METHOD(thread_mul_ln1118_4_fu_148_p0);
    sensitive << ( data_4_V_read );

    SC_METHOD(thread_mul_ln1118_4_fu_148_p2);
    sensitive << ( mul_ln1118_4_fu_148_p0 );

    SC_METHOD(thread_mul_ln1118_5_fu_155_p0);
    sensitive << ( data_5_V_read );

    SC_METHOD(thread_mul_ln1118_5_fu_155_p2);
    sensitive << ( mul_ln1118_5_fu_155_p0 );

    SC_METHOD(thread_mul_ln1118_6_fu_152_p0);
    sensitive << ( data_6_V_read );

    SC_METHOD(thread_mul_ln1118_6_fu_152_p2);
    sensitive << ( mul_ln1118_6_fu_152_p0 );

    SC_METHOD(thread_mul_ln1118_7_fu_154_p0);
    sensitive << ( data_8_V_read );

    SC_METHOD(thread_mul_ln1118_7_fu_154_p2);
    sensitive << ( mul_ln1118_7_fu_154_p0 );

    SC_METHOD(thread_mul_ln1118_8_fu_146_p0);
    sensitive << ( data_9_V_read );

    SC_METHOD(thread_mul_ln1118_8_fu_146_p2);
    sensitive << ( mul_ln1118_8_fu_146_p0 );

    SC_METHOD(thread_mul_ln1118_fu_151_p0);
    sensitive << ( data_0_V_read );

    SC_METHOD(thread_mul_ln1118_fu_151_p2);
    sensitive << ( mul_ln1118_fu_151_p0 );

    SC_METHOD(thread_sext_ln1118_7_fu_693_p1);
    sensitive << ( shl_ln_fu_685_p3 );

    SC_METHOD(thread_sext_ln1118_8_fu_705_p1);
    sensitive << ( shl_ln1118_s_fu_697_p3 );

    SC_METHOD(thread_sext_ln708_fu_725_p1);
    sensitive << ( trunc_ln708_s_fu_715_p4 );

    SC_METHOD(thread_shl_ln1118_s_fu_697_p3);
    sensitive << ( data_7_V_read );

    SC_METHOD(thread_shl_ln_fu_685_p3);
    sensitive << ( data_7_V_read );

    SC_METHOD(thread_trunc_ln708_1_fu_600_p4);
    sensitive << ( mul_ln1118_1_fu_153_p2 );

    SC_METHOD(thread_trunc_ln708_2_fu_615_p4);
    sensitive << ( mul_ln1118_2_fu_149_p2 );

    SC_METHOD(thread_trunc_ln708_3_fu_630_p4);
    sensitive << ( mul_ln1118_3_fu_147_p2 );

    SC_METHOD(thread_trunc_ln708_4_fu_645_p4);
    sensitive << ( mul_ln1118_4_fu_148_p2 );

    SC_METHOD(thread_trunc_ln708_5_fu_660_p4);
    sensitive << ( mul_ln1118_5_fu_155_p2 );

    SC_METHOD(thread_trunc_ln708_6_fu_675_p4);
    sensitive << ( mul_ln1118_6_fu_152_p2 );

    SC_METHOD(thread_trunc_ln708_8_fu_734_p4);
    sensitive << ( mul_ln1118_7_fu_154_p2 );

    SC_METHOD(thread_trunc_ln708_9_fu_749_p4);
    sensitive << ( mul_ln1118_8_fu_146_p2 );

    SC_METHOD(thread_trunc_ln708_s_fu_715_p4);
    sensitive << ( add_ln1118_fu_709_p2 );

    SC_METHOD(thread_trunc_ln_fu_585_p4);
    sensitive << ( mul_ln1118_fu_151_p2 );

    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "dense_latency_ap_fixed_ap_fixed_config10_0_0_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, data_0_V_read, "(port)data_0_V_read");
    sc_trace(mVcdFile, data_1_V_read, "(port)data_1_V_read");
    sc_trace(mVcdFile, data_2_V_read, "(port)data_2_V_read");
    sc_trace(mVcdFile, data_3_V_read, "(port)data_3_V_read");
    sc_trace(mVcdFile, data_4_V_read, "(port)data_4_V_read");
    sc_trace(mVcdFile, data_5_V_read, "(port)data_5_V_read");
    sc_trace(mVcdFile, data_6_V_read, "(port)data_6_V_read");
    sc_trace(mVcdFile, data_7_V_read, "(port)data_7_V_read");
    sc_trace(mVcdFile, data_8_V_read, "(port)data_8_V_read");
    sc_trace(mVcdFile, data_9_V_read, "(port)data_9_V_read");
    sc_trace(mVcdFile, ap_return, "(port)ap_return");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, mul_ln1118_8_fu_146_p0, "mul_ln1118_8_fu_146_p0");
    sc_trace(mVcdFile, mul_ln1118_3_fu_147_p0, "mul_ln1118_3_fu_147_p0");
    sc_trace(mVcdFile, mul_ln1118_4_fu_148_p0, "mul_ln1118_4_fu_148_p0");
    sc_trace(mVcdFile, mul_ln1118_2_fu_149_p0, "mul_ln1118_2_fu_149_p0");
    sc_trace(mVcdFile, mul_ln1118_fu_151_p0, "mul_ln1118_fu_151_p0");
    sc_trace(mVcdFile, mul_ln1118_6_fu_152_p0, "mul_ln1118_6_fu_152_p0");
    sc_trace(mVcdFile, mul_ln1118_1_fu_153_p0, "mul_ln1118_1_fu_153_p0");
    sc_trace(mVcdFile, mul_ln1118_7_fu_154_p0, "mul_ln1118_7_fu_154_p0");
    sc_trace(mVcdFile, mul_ln1118_5_fu_155_p0, "mul_ln1118_5_fu_155_p0");
    sc_trace(mVcdFile, mul_ln1118_fu_151_p2, "mul_ln1118_fu_151_p2");
    sc_trace(mVcdFile, mul_ln1118_1_fu_153_p2, "mul_ln1118_1_fu_153_p2");
    sc_trace(mVcdFile, mul_ln1118_2_fu_149_p2, "mul_ln1118_2_fu_149_p2");
    sc_trace(mVcdFile, mul_ln1118_3_fu_147_p2, "mul_ln1118_3_fu_147_p2");
    sc_trace(mVcdFile, mul_ln1118_4_fu_148_p2, "mul_ln1118_4_fu_148_p2");
    sc_trace(mVcdFile, mul_ln1118_5_fu_155_p2, "mul_ln1118_5_fu_155_p2");
    sc_trace(mVcdFile, mul_ln1118_6_fu_152_p2, "mul_ln1118_6_fu_152_p2");
    sc_trace(mVcdFile, shl_ln_fu_685_p3, "shl_ln_fu_685_p3");
    sc_trace(mVcdFile, shl_ln1118_s_fu_697_p3, "shl_ln1118_s_fu_697_p3");
    sc_trace(mVcdFile, sext_ln1118_7_fu_693_p1, "sext_ln1118_7_fu_693_p1");
    sc_trace(mVcdFile, sext_ln1118_8_fu_705_p1, "sext_ln1118_8_fu_705_p1");
    sc_trace(mVcdFile, add_ln1118_fu_709_p2, "add_ln1118_fu_709_p2");
    sc_trace(mVcdFile, trunc_ln708_s_fu_715_p4, "trunc_ln708_s_fu_715_p4");
    sc_trace(mVcdFile, mul_ln1118_7_fu_154_p2, "mul_ln1118_7_fu_154_p2");
    sc_trace(mVcdFile, mul_ln1118_8_fu_146_p2, "mul_ln1118_8_fu_146_p2");
    sc_trace(mVcdFile, trunc_ln708_1_fu_600_p4, "trunc_ln708_1_fu_600_p4");
    sc_trace(mVcdFile, trunc_ln_fu_585_p4, "trunc_ln_fu_585_p4");
    sc_trace(mVcdFile, trunc_ln708_4_fu_645_p4, "trunc_ln708_4_fu_645_p4");
    sc_trace(mVcdFile, trunc_ln708_3_fu_630_p4, "trunc_ln708_3_fu_630_p4");
    sc_trace(mVcdFile, trunc_ln708_2_fu_615_p4, "trunc_ln708_2_fu_615_p4");
    sc_trace(mVcdFile, add_ln703_1_fu_765_p2, "add_ln703_1_fu_765_p2");
    sc_trace(mVcdFile, add_ln703_fu_759_p2, "add_ln703_fu_759_p2");
    sc_trace(mVcdFile, add_ln703_2_fu_771_p2, "add_ln703_2_fu_771_p2");
    sc_trace(mVcdFile, sext_ln708_fu_725_p1, "sext_ln708_fu_725_p1");
    sc_trace(mVcdFile, trunc_ln708_6_fu_675_p4, "trunc_ln708_6_fu_675_p4");
    sc_trace(mVcdFile, trunc_ln708_5_fu_660_p4, "trunc_ln708_5_fu_660_p4");
    sc_trace(mVcdFile, add_ln703_4_fu_783_p2, "add_ln703_4_fu_783_p2");
    sc_trace(mVcdFile, trunc_ln708_9_fu_749_p4, "trunc_ln708_9_fu_749_p4");
    sc_trace(mVcdFile, trunc_ln708_8_fu_734_p4, "trunc_ln708_8_fu_734_p4");
    sc_trace(mVcdFile, add_ln703_6_fu_795_p2, "add_ln703_6_fu_795_p2");
    sc_trace(mVcdFile, add_ln703_5_fu_789_p2, "add_ln703_5_fu_789_p2");
    sc_trace(mVcdFile, add_ln703_7_fu_801_p2, "add_ln703_7_fu_801_p2");
    sc_trace(mVcdFile, add_ln703_3_fu_777_p2, "add_ln703_3_fu_777_p2");
    sc_trace(mVcdFile, add_ln703_8_fu_807_p2, "add_ln703_8_fu_807_p2");
#endif

    }
}

dense_latency_ap_fixed_ap_fixed_config10_0_0::~dense_latency_ap_fixed_ap_fixed_config10_0_0() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

}

void dense_latency_ap_fixed_ap_fixed_config10_0_0::thread_add_ln1118_fu_709_p2() {
    add_ln1118_fu_709_p2 = (!sext_ln1118_7_fu_693_p1.read().is_01() || !sext_ln1118_8_fu_705_p1.read().is_01())? sc_lv<20>(): (sc_bigint<20>(sext_ln1118_7_fu_693_p1.read()) + sc_bigint<20>(sext_ln1118_8_fu_705_p1.read()));
}

void dense_latency_ap_fixed_ap_fixed_config10_0_0::thread_add_ln703_1_fu_765_p2() {
    add_ln703_1_fu_765_p2 = (!trunc_ln708_4_fu_645_p4.read().is_01() || !trunc_ln708_3_fu_630_p4.read().is_01())? sc_lv<16>(): (sc_biguint<16>(trunc_ln708_4_fu_645_p4.read()) + sc_biguint<16>(trunc_ln708_3_fu_630_p4.read()));
}

void dense_latency_ap_fixed_ap_fixed_config10_0_0::thread_add_ln703_2_fu_771_p2() {
    add_ln703_2_fu_771_p2 = (!trunc_ln708_2_fu_615_p4.read().is_01() || !add_ln703_1_fu_765_p2.read().is_01())? sc_lv<16>(): (sc_biguint<16>(trunc_ln708_2_fu_615_p4.read()) + sc_biguint<16>(add_ln703_1_fu_765_p2.read()));
}

void dense_latency_ap_fixed_ap_fixed_config10_0_0::thread_add_ln703_3_fu_777_p2() {
    add_ln703_3_fu_777_p2 = (!add_ln703_fu_759_p2.read().is_01() || !add_ln703_2_fu_771_p2.read().is_01())? sc_lv<16>(): (sc_biguint<16>(add_ln703_fu_759_p2.read()) + sc_biguint<16>(add_ln703_2_fu_771_p2.read()));
}

void dense_latency_ap_fixed_ap_fixed_config10_0_0::thread_add_ln703_4_fu_783_p2() {
    add_ln703_4_fu_783_p2 = (!sext_ln708_fu_725_p1.read().is_01() || !trunc_ln708_6_fu_675_p4.read().is_01())? sc_lv<16>(): (sc_bigint<16>(sext_ln708_fu_725_p1.read()) + sc_biguint<16>(trunc_ln708_6_fu_675_p4.read()));
}

void dense_latency_ap_fixed_ap_fixed_config10_0_0::thread_add_ln703_5_fu_789_p2() {
    add_ln703_5_fu_789_p2 = (!trunc_ln708_5_fu_660_p4.read().is_01() || !add_ln703_4_fu_783_p2.read().is_01())? sc_lv<16>(): (sc_biguint<16>(trunc_ln708_5_fu_660_p4.read()) + sc_biguint<16>(add_ln703_4_fu_783_p2.read()));
}

void dense_latency_ap_fixed_ap_fixed_config10_0_0::thread_add_ln703_6_fu_795_p2() {
    add_ln703_6_fu_795_p2 = (!trunc_ln708_9_fu_749_p4.read().is_01() || !ap_const_lv16_6.is_01())? sc_lv<16>(): (sc_biguint<16>(trunc_ln708_9_fu_749_p4.read()) + sc_biguint<16>(ap_const_lv16_6));
}

void dense_latency_ap_fixed_ap_fixed_config10_0_0::thread_add_ln703_7_fu_801_p2() {
    add_ln703_7_fu_801_p2 = (!trunc_ln708_8_fu_734_p4.read().is_01() || !add_ln703_6_fu_795_p2.read().is_01())? sc_lv<16>(): (sc_biguint<16>(trunc_ln708_8_fu_734_p4.read()) + sc_biguint<16>(add_ln703_6_fu_795_p2.read()));
}

void dense_latency_ap_fixed_ap_fixed_config10_0_0::thread_add_ln703_8_fu_807_p2() {
    add_ln703_8_fu_807_p2 = (!add_ln703_5_fu_789_p2.read().is_01() || !add_ln703_7_fu_801_p2.read().is_01())? sc_lv<16>(): (sc_biguint<16>(add_ln703_5_fu_789_p2.read()) + sc_biguint<16>(add_ln703_7_fu_801_p2.read()));
}

void dense_latency_ap_fixed_ap_fixed_config10_0_0::thread_add_ln703_fu_759_p2() {
    add_ln703_fu_759_p2 = (!trunc_ln708_1_fu_600_p4.read().is_01() || !trunc_ln_fu_585_p4.read().is_01())? sc_lv<16>(): (sc_biguint<16>(trunc_ln708_1_fu_600_p4.read()) + sc_biguint<16>(trunc_ln_fu_585_p4.read()));
}

void dense_latency_ap_fixed_ap_fixed_config10_0_0::thread_ap_ready() {
    ap_ready = ap_const_logic_1;
}

void dense_latency_ap_fixed_ap_fixed_config10_0_0::thread_ap_return() {
    ap_return = (!add_ln703_3_fu_777_p2.read().is_01() || !add_ln703_8_fu_807_p2.read().is_01())? sc_lv<16>(): (sc_biguint<16>(add_ln703_3_fu_777_p2.read()) + sc_biguint<16>(add_ln703_8_fu_807_p2.read()));
}

void dense_latency_ap_fixed_ap_fixed_config10_0_0::thread_mul_ln1118_1_fu_153_p0() {
    mul_ln1118_1_fu_153_p0 = data_1_V_read.read();
}

void dense_latency_ap_fixed_ap_fixed_config10_0_0::thread_mul_ln1118_1_fu_153_p2() {
    mul_ln1118_1_fu_153_p2 = (!mul_ln1118_1_fu_153_p0.read().is_01() || !ap_const_lv24_D4.is_01())? sc_lv<24>(): sc_bigint<16>(mul_ln1118_1_fu_153_p0.read()) * sc_biguint<24>(ap_const_lv24_D4);
}

void dense_latency_ap_fixed_ap_fixed_config10_0_0::thread_mul_ln1118_2_fu_149_p0() {
    mul_ln1118_2_fu_149_p0 = data_2_V_read.read();
}

void dense_latency_ap_fixed_ap_fixed_config10_0_0::thread_mul_ln1118_2_fu_149_p2() {
    mul_ln1118_2_fu_149_p2 = (!mul_ln1118_2_fu_149_p0.read().is_01() || !ap_const_lv24_FFFFB6.is_01())? sc_lv<24>(): sc_bigint<16>(mul_ln1118_2_fu_149_p0.read()) * sc_bigint<24>(ap_const_lv24_FFFFB6);
}

void dense_latency_ap_fixed_ap_fixed_config10_0_0::thread_mul_ln1118_3_fu_147_p0() {
    mul_ln1118_3_fu_147_p0 = data_3_V_read.read();
}

void dense_latency_ap_fixed_ap_fixed_config10_0_0::thread_mul_ln1118_3_fu_147_p2() {
    mul_ln1118_3_fu_147_p2 = (!mul_ln1118_3_fu_147_p0.read().is_01() || !ap_const_lv24_5F.is_01())? sc_lv<24>(): sc_bigint<16>(mul_ln1118_3_fu_147_p0.read()) * sc_biguint<24>(ap_const_lv24_5F);
}

void dense_latency_ap_fixed_ap_fixed_config10_0_0::thread_mul_ln1118_4_fu_148_p0() {
    mul_ln1118_4_fu_148_p0 = data_4_V_read.read();
}

void dense_latency_ap_fixed_ap_fixed_config10_0_0::thread_mul_ln1118_4_fu_148_p2() {
    mul_ln1118_4_fu_148_p2 = (!mul_ln1118_4_fu_148_p0.read().is_01() || !ap_const_lv24_FFFF92.is_01())? sc_lv<24>(): sc_bigint<16>(mul_ln1118_4_fu_148_p0.read()) * sc_bigint<24>(ap_const_lv24_FFFF92);
}

void dense_latency_ap_fixed_ap_fixed_config10_0_0::thread_mul_ln1118_5_fu_155_p0() {
    mul_ln1118_5_fu_155_p0 = data_5_V_read.read();
}

void dense_latency_ap_fixed_ap_fixed_config10_0_0::thread_mul_ln1118_5_fu_155_p2() {
    mul_ln1118_5_fu_155_p2 = (!mul_ln1118_5_fu_155_p0.read().is_01() || !ap_const_lv24_FFFFBB.is_01())? sc_lv<24>(): sc_bigint<16>(mul_ln1118_5_fu_155_p0.read()) * sc_bigint<24>(ap_const_lv24_FFFFBB);
}

void dense_latency_ap_fixed_ap_fixed_config10_0_0::thread_mul_ln1118_6_fu_152_p0() {
    mul_ln1118_6_fu_152_p0 = data_6_V_read.read();
}

void dense_latency_ap_fixed_ap_fixed_config10_0_0::thread_mul_ln1118_6_fu_152_p2() {
    mul_ln1118_6_fu_152_p2 = (!mul_ln1118_6_fu_152_p0.read().is_01() || !ap_const_lv24_47.is_01())? sc_lv<24>(): sc_bigint<16>(mul_ln1118_6_fu_152_p0.read()) * sc_biguint<24>(ap_const_lv24_47);
}

void dense_latency_ap_fixed_ap_fixed_config10_0_0::thread_mul_ln1118_7_fu_154_p0() {
    mul_ln1118_7_fu_154_p0 = data_8_V_read.read();
}

void dense_latency_ap_fixed_ap_fixed_config10_0_0::thread_mul_ln1118_7_fu_154_p2() {
    mul_ln1118_7_fu_154_p2 = (!mul_ln1118_7_fu_154_p0.read().is_01() || !ap_const_lv24_9D.is_01())? sc_lv<24>(): sc_bigint<16>(mul_ln1118_7_fu_154_p0.read()) * sc_biguint<24>(ap_const_lv24_9D);
}

void dense_latency_ap_fixed_ap_fixed_config10_0_0::thread_mul_ln1118_8_fu_146_p0() {
    mul_ln1118_8_fu_146_p0 = data_9_V_read.read();
}

void dense_latency_ap_fixed_ap_fixed_config10_0_0::thread_mul_ln1118_8_fu_146_p2() {
    mul_ln1118_8_fu_146_p2 = (!mul_ln1118_8_fu_146_p0.read().is_01() || !ap_const_lv24_57.is_01())? sc_lv<24>(): sc_bigint<16>(mul_ln1118_8_fu_146_p0.read()) * sc_biguint<24>(ap_const_lv24_57);
}

void dense_latency_ap_fixed_ap_fixed_config10_0_0::thread_mul_ln1118_fu_151_p0() {
    mul_ln1118_fu_151_p0 = data_0_V_read.read();
}

void dense_latency_ap_fixed_ap_fixed_config10_0_0::thread_mul_ln1118_fu_151_p2() {
    mul_ln1118_fu_151_p2 = (!mul_ln1118_fu_151_p0.read().is_01() || !ap_const_lv24_FFFF50.is_01())? sc_lv<24>(): sc_bigint<16>(mul_ln1118_fu_151_p0.read()) * sc_bigint<24>(ap_const_lv24_FFFF50);
}

void dense_latency_ap_fixed_ap_fixed_config10_0_0::thread_sext_ln1118_7_fu_693_p1() {
    sext_ln1118_7_fu_693_p1 = esl_sext<20,19>(shl_ln_fu_685_p3.read());
}

void dense_latency_ap_fixed_ap_fixed_config10_0_0::thread_sext_ln1118_8_fu_705_p1() {
    sext_ln1118_8_fu_705_p1 = esl_sext<20,17>(shl_ln1118_s_fu_697_p3.read());
}

void dense_latency_ap_fixed_ap_fixed_config10_0_0::thread_sext_ln708_fu_725_p1() {
    sext_ln708_fu_725_p1 = esl_sext<16,12>(trunc_ln708_s_fu_715_p4.read());
}

void dense_latency_ap_fixed_ap_fixed_config10_0_0::thread_shl_ln1118_s_fu_697_p3() {
    shl_ln1118_s_fu_697_p3 = esl_concat<16,1>(data_7_V_read.read(), ap_const_lv1_0);
}

void dense_latency_ap_fixed_ap_fixed_config10_0_0::thread_shl_ln_fu_685_p3() {
    shl_ln_fu_685_p3 = esl_concat<16,3>(data_7_V_read.read(), ap_const_lv3_0);
}

void dense_latency_ap_fixed_ap_fixed_config10_0_0::thread_trunc_ln708_1_fu_600_p4() {
    trunc_ln708_1_fu_600_p4 = mul_ln1118_1_fu_153_p2.read().range(23, 8);
}

void dense_latency_ap_fixed_ap_fixed_config10_0_0::thread_trunc_ln708_2_fu_615_p4() {
    trunc_ln708_2_fu_615_p4 = mul_ln1118_2_fu_149_p2.read().range(23, 8);
}

void dense_latency_ap_fixed_ap_fixed_config10_0_0::thread_trunc_ln708_3_fu_630_p4() {
    trunc_ln708_3_fu_630_p4 = mul_ln1118_3_fu_147_p2.read().range(23, 8);
}

void dense_latency_ap_fixed_ap_fixed_config10_0_0::thread_trunc_ln708_4_fu_645_p4() {
    trunc_ln708_4_fu_645_p4 = mul_ln1118_4_fu_148_p2.read().range(23, 8);
}

void dense_latency_ap_fixed_ap_fixed_config10_0_0::thread_trunc_ln708_5_fu_660_p4() {
    trunc_ln708_5_fu_660_p4 = mul_ln1118_5_fu_155_p2.read().range(23, 8);
}

void dense_latency_ap_fixed_ap_fixed_config10_0_0::thread_trunc_ln708_6_fu_675_p4() {
    trunc_ln708_6_fu_675_p4 = mul_ln1118_6_fu_152_p2.read().range(23, 8);
}

void dense_latency_ap_fixed_ap_fixed_config10_0_0::thread_trunc_ln708_8_fu_734_p4() {
    trunc_ln708_8_fu_734_p4 = mul_ln1118_7_fu_154_p2.read().range(23, 8);
}

void dense_latency_ap_fixed_ap_fixed_config10_0_0::thread_trunc_ln708_9_fu_749_p4() {
    trunc_ln708_9_fu_749_p4 = mul_ln1118_8_fu_146_p2.read().range(23, 8);
}

void dense_latency_ap_fixed_ap_fixed_config10_0_0::thread_trunc_ln708_s_fu_715_p4() {
    trunc_ln708_s_fu_715_p4 = add_ln1118_fu_709_p2.read().range(19, 8);
}

void dense_latency_ap_fixed_ap_fixed_config10_0_0::thread_trunc_ln_fu_585_p4() {
    trunc_ln_fu_585_p4 = mul_ln1118_fu_151_p2.read().range(23, 8);
}

}

