// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "dense_latency_ap_fixed_ap_fixed_config10_0_0.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic dense_latency_ap_fixed_ap_fixed_config10_0_0::ap_const_logic_1 = sc_dt::Log_1;
const bool dense_latency_ap_fixed_ap_fixed_config10_0_0::ap_const_boolean_1 = true;
const sc_lv<24> dense_latency_ap_fixed_ap_fixed_config10_0_0::ap_const_lv24_47 = "1000111";
const sc_lv<24> dense_latency_ap_fixed_ap_fixed_config10_0_0::ap_const_lv24_A7 = "10100111";
const sc_lv<24> dense_latency_ap_fixed_ap_fixed_config10_0_0::ap_const_lv24_FFFF3E = "111111111111111100111110";
const sc_lv<24> dense_latency_ap_fixed_ap_fixed_config10_0_0::ap_const_lv24_EB = "11101011";
const sc_lv<23> dense_latency_ap_fixed_ap_fixed_config10_0_0::ap_const_lv23_7FFFCC = "11111111111111111001100";
const sc_lv<7> dense_latency_ap_fixed_ap_fixed_config10_0_0::ap_const_lv7_0 = "0000000";
const sc_lv<24> dense_latency_ap_fixed_ap_fixed_config10_0_0::ap_const_lv24_0 = "000000000000000000000000";
const sc_lv<5> dense_latency_ap_fixed_ap_fixed_config10_0_0::ap_const_lv5_0 = "00000";
const sc_lv<32> dense_latency_ap_fixed_ap_fixed_config10_0_0::ap_const_lv32_8 = "1000";
const sc_lv<32> dense_latency_ap_fixed_ap_fixed_config10_0_0::ap_const_lv32_17 = "10111";
const sc_lv<32> dense_latency_ap_fixed_ap_fixed_config10_0_0::ap_const_lv32_16 = "10110";
const sc_lv<6> dense_latency_ap_fixed_ap_fixed_config10_0_0::ap_const_lv6_0 = "000000";
const sc_lv<23> dense_latency_ap_fixed_ap_fixed_config10_0_0::ap_const_lv23_0 = "00000000000000000000000";
const sc_lv<1> dense_latency_ap_fixed_ap_fixed_config10_0_0::ap_const_lv1_0 = "0";
const sc_lv<3> dense_latency_ap_fixed_ap_fixed_config10_0_0::ap_const_lv3_0 = "000";
const sc_lv<2> dense_latency_ap_fixed_ap_fixed_config10_0_0::ap_const_lv2_0 = "00";
const sc_lv<32> dense_latency_ap_fixed_ap_fixed_config10_0_0::ap_const_lv32_15 = "10101";
const sc_lv<15> dense_latency_ap_fixed_ap_fixed_config10_0_0::ap_const_lv15_14 = "10100";
const sc_logic dense_latency_ap_fixed_ap_fixed_config10_0_0::ap_const_logic_0 = sc_dt::Log_0;

dense_latency_ap_fixed_ap_fixed_config10_0_0::dense_latency_ap_fixed_ap_fixed_config10_0_0(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_add_ln703_1_fu_715_p2);
    sensitive << ( sext_ln708_1_fu_534_p1 );
    sensitive << ( trunc_ln708_4_fu_543_p4 );

    SC_METHOD(thread_add_ln703_2_fu_721_p2);
    sensitive << ( add_ln703_1_fu_715_p2 );
    sensitive << ( sext_ln708_fu_484_p1 );

    SC_METHOD(thread_add_ln703_3_fu_727_p2);
    sensitive << ( add_ln703_2_fu_721_p2 );
    sensitive << ( add_ln703_fu_709_p2 );

    SC_METHOD(thread_add_ln703_4_fu_733_p2);
    sensitive << ( trunc_ln708_6_fu_596_p4 );
    sensitive << ( trunc_ln708_7_fu_611_p4 );

    SC_METHOD(thread_add_ln703_5_fu_739_p2);
    sensitive << ( add_ln703_4_fu_733_p2 );
    sensitive << ( trunc_ln708_5_fu_581_p4 );

    SC_METHOD(thread_add_ln703_6_fu_745_p2);
    sensitive << ( sext_ln101_fu_705_p1 );

    SC_METHOD(thread_add_ln703_7_fu_755_p2);
    sensitive << ( sext_ln703_fu_751_p1 );
    sensitive << ( sext_ln708_2_fu_661_p1 );

    SC_METHOD(thread_add_ln703_8_fu_761_p2);
    sensitive << ( add_ln703_7_fu_755_p2 );
    sensitive << ( add_ln703_5_fu_739_p2 );

    SC_METHOD(thread_add_ln703_fu_709_p2);
    sensitive << ( trunc_ln_fu_444_p4 );
    sensitive << ( trunc_ln708_1_fu_459_p4 );

    SC_METHOD(thread_ap_ready);

    SC_METHOD(thread_ap_return);
    sensitive << ( add_ln703_8_fu_761_p2 );
    sensitive << ( add_ln703_3_fu_727_p2 );

    SC_METHOD(thread_mul_ln1118_1_fu_171_p0);
    sensitive << ( data_2_V_read );

    SC_METHOD(thread_mul_ln1118_1_fu_171_p2);
    sensitive << ( mul_ln1118_1_fu_171_p0 );

    SC_METHOD(thread_mul_ln1118_2_fu_167_p0);
    sensitive << ( data_4_V_read );

    SC_METHOD(thread_mul_ln1118_2_fu_167_p2);
    sensitive << ( mul_ln1118_2_fu_167_p0 );

    SC_METHOD(thread_mul_ln1118_3_fu_164_p0);
    sensitive << ( data_6_V_read );

    SC_METHOD(thread_mul_ln1118_3_fu_164_p2);
    sensitive << ( mul_ln1118_3_fu_164_p0 );

    SC_METHOD(thread_mul_ln1118_4_fu_168_p0);
    sensitive << ( data_7_V_read );

    SC_METHOD(thread_mul_ln1118_4_fu_168_p2);
    sensitive << ( mul_ln1118_4_fu_168_p0 );

    SC_METHOD(thread_mul_ln1118_fu_162_p0);
    sensitive << ( data_1_V_read );

    SC_METHOD(thread_mul_ln1118_fu_162_p2);
    sensitive << ( mul_ln1118_fu_162_p0 );

    SC_METHOD(thread_sext_ln101_fu_705_p1);
    sensitive << ( tmp_4_fu_695_p4 );

    SC_METHOD(thread_sext_ln1118_11_fu_629_p1);
    sensitive << ( shl_ln1118_4_fu_621_p3 );

    SC_METHOD(thread_sext_ln1118_12_fu_641_p1);
    sensitive << ( shl_ln1118_5_fu_633_p3 );

    SC_METHOD(thread_sext_ln1118_13_fu_673_p1);
    sensitive << ( shl_ln1118_6_fu_665_p3 );

    SC_METHOD(thread_sext_ln1118_14_fu_685_p1);
    sensitive << ( shl_ln1118_7_fu_677_p3 );

    SC_METHOD(thread_sext_ln1118_1_fu_434_p1);
    sensitive << ( shl_ln1118_s_fu_426_p3 );

    SC_METHOD(thread_sext_ln1118_4_fu_496_p1);
    sensitive << ( shl_ln1118_1_fu_488_p3 );

    SC_METHOD(thread_sext_ln1118_5_fu_514_p1);
    sensitive << ( shl_ln1118_2_fu_506_p3 );

    SC_METHOD(thread_sext_ln1118_7_fu_553_p0);
    sensitive << ( data_5_V_read );

    SC_METHOD(thread_sext_ln1118_7_fu_553_p1);
    sensitive << ( sext_ln1118_7_fu_553_p0 );

    SC_METHOD(thread_sext_ln1118_8_fu_565_p1);
    sensitive << ( shl_ln1118_3_fu_557_p3 );

    SC_METHOD(thread_sext_ln1118_fu_416_p1);
    sensitive << ( shl_ln_fu_408_p3 );

    SC_METHOD(thread_sext_ln703_fu_751_p1);
    sensitive << ( add_ln703_6_fu_745_p2 );

    SC_METHOD(thread_sext_ln708_1_fu_534_p1);
    sensitive << ( trunc_ln708_2_fu_524_p4 );

    SC_METHOD(thread_sext_ln708_2_fu_661_p1);
    sensitive << ( trunc_ln708_3_fu_651_p4 );

    SC_METHOD(thread_sext_ln708_fu_484_p1);
    sensitive << ( trunc_ln708_s_fu_474_p4 );

    SC_METHOD(thread_shl_ln1118_1_fu_488_p3);
    sensitive << ( data_3_V_read );

    SC_METHOD(thread_shl_ln1118_2_fu_506_p3);
    sensitive << ( data_3_V_read );

    SC_METHOD(thread_shl_ln1118_3_fu_557_p1);
    sensitive << ( data_5_V_read );

    SC_METHOD(thread_shl_ln1118_3_fu_557_p3);
    sensitive << ( shl_ln1118_3_fu_557_p1 );

    SC_METHOD(thread_shl_ln1118_4_fu_621_p3);
    sensitive << ( data_8_V_read );

    SC_METHOD(thread_shl_ln1118_5_fu_633_p3);
    sensitive << ( data_8_V_read );

    SC_METHOD(thread_shl_ln1118_6_fu_665_p3);
    sensitive << ( data_9_V_read );

    SC_METHOD(thread_shl_ln1118_7_fu_677_p3);
    sensitive << ( data_9_V_read );

    SC_METHOD(thread_shl_ln1118_s_fu_426_p3);
    sensitive << ( data_0_V_read );

    SC_METHOD(thread_shl_ln_fu_408_p3);
    sensitive << ( data_0_V_read );

    SC_METHOD(thread_sub_ln1118_1_fu_438_p2);
    sensitive << ( sub_ln1118_fu_420_p2 );
    sensitive << ( sext_ln1118_1_fu_434_p1 );

    SC_METHOD(thread_sub_ln1118_2_fu_500_p2);
    sensitive << ( sext_ln1118_4_fu_496_p1 );

    SC_METHOD(thread_sub_ln1118_3_fu_518_p2);
    sensitive << ( sub_ln1118_2_fu_500_p2 );
    sensitive << ( sext_ln1118_5_fu_514_p1 );

    SC_METHOD(thread_sub_ln1118_4_fu_569_p2);
    sensitive << ( sext_ln1118_8_fu_565_p1 );

    SC_METHOD(thread_sub_ln1118_5_fu_575_p2);
    sensitive << ( sub_ln1118_4_fu_569_p2 );
    sensitive << ( sext_ln1118_7_fu_553_p1 );

    SC_METHOD(thread_sub_ln1118_6_fu_645_p2);
    sensitive << ( sext_ln1118_12_fu_641_p1 );
    sensitive << ( sext_ln1118_11_fu_629_p1 );

    SC_METHOD(thread_sub_ln1118_7_fu_689_p2);
    sensitive << ( sext_ln1118_14_fu_685_p1 );
    sensitive << ( sext_ln1118_13_fu_673_p1 );

    SC_METHOD(thread_sub_ln1118_fu_420_p2);
    sensitive << ( sext_ln1118_fu_416_p1 );

    SC_METHOD(thread_tmp_4_fu_695_p4);
    sensitive << ( sub_ln1118_7_fu_689_p2 );

    SC_METHOD(thread_trunc_ln708_1_fu_459_p4);
    sensitive << ( mul_ln1118_fu_162_p2 );

    SC_METHOD(thread_trunc_ln708_2_fu_524_p4);
    sensitive << ( sub_ln1118_3_fu_518_p2 );

    SC_METHOD(thread_trunc_ln708_3_fu_651_p4);
    sensitive << ( sub_ln1118_6_fu_645_p2 );

    SC_METHOD(thread_trunc_ln708_4_fu_543_p4);
    sensitive << ( mul_ln1118_2_fu_167_p2 );

    SC_METHOD(thread_trunc_ln708_5_fu_581_p4);
    sensitive << ( sub_ln1118_5_fu_575_p2 );

    SC_METHOD(thread_trunc_ln708_6_fu_596_p4);
    sensitive << ( mul_ln1118_3_fu_164_p2 );

    SC_METHOD(thread_trunc_ln708_7_fu_611_p4);
    sensitive << ( mul_ln1118_4_fu_168_p2 );

    SC_METHOD(thread_trunc_ln708_s_fu_474_p4);
    sensitive << ( mul_ln1118_1_fu_171_p2 );

    SC_METHOD(thread_trunc_ln_fu_444_p4);
    sensitive << ( sub_ln1118_1_fu_438_p2 );

    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "dense_latency_ap_fixed_ap_fixed_config10_0_0_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, data_0_V_read, "(port)data_0_V_read");
    sc_trace(mVcdFile, data_1_V_read, "(port)data_1_V_read");
    sc_trace(mVcdFile, data_2_V_read, "(port)data_2_V_read");
    sc_trace(mVcdFile, data_3_V_read, "(port)data_3_V_read");
    sc_trace(mVcdFile, data_4_V_read, "(port)data_4_V_read");
    sc_trace(mVcdFile, data_5_V_read, "(port)data_5_V_read");
    sc_trace(mVcdFile, data_6_V_read, "(port)data_6_V_read");
    sc_trace(mVcdFile, data_7_V_read, "(port)data_7_V_read");
    sc_trace(mVcdFile, data_8_V_read, "(port)data_8_V_read");
    sc_trace(mVcdFile, data_9_V_read, "(port)data_9_V_read");
    sc_trace(mVcdFile, ap_return, "(port)ap_return");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, mul_ln1118_fu_162_p0, "mul_ln1118_fu_162_p0");
    sc_trace(mVcdFile, mul_ln1118_3_fu_164_p0, "mul_ln1118_3_fu_164_p0");
    sc_trace(mVcdFile, mul_ln1118_2_fu_167_p0, "mul_ln1118_2_fu_167_p0");
    sc_trace(mVcdFile, mul_ln1118_4_fu_168_p0, "mul_ln1118_4_fu_168_p0");
    sc_trace(mVcdFile, mul_ln1118_1_fu_171_p0, "mul_ln1118_1_fu_171_p0");
    sc_trace(mVcdFile, shl_ln_fu_408_p3, "shl_ln_fu_408_p3");
    sc_trace(mVcdFile, sext_ln1118_fu_416_p1, "sext_ln1118_fu_416_p1");
    sc_trace(mVcdFile, shl_ln1118_s_fu_426_p3, "shl_ln1118_s_fu_426_p3");
    sc_trace(mVcdFile, sub_ln1118_fu_420_p2, "sub_ln1118_fu_420_p2");
    sc_trace(mVcdFile, sext_ln1118_1_fu_434_p1, "sext_ln1118_1_fu_434_p1");
    sc_trace(mVcdFile, sub_ln1118_1_fu_438_p2, "sub_ln1118_1_fu_438_p2");
    sc_trace(mVcdFile, mul_ln1118_fu_162_p2, "mul_ln1118_fu_162_p2");
    sc_trace(mVcdFile, mul_ln1118_1_fu_171_p2, "mul_ln1118_1_fu_171_p2");
    sc_trace(mVcdFile, trunc_ln708_s_fu_474_p4, "trunc_ln708_s_fu_474_p4");
    sc_trace(mVcdFile, shl_ln1118_1_fu_488_p3, "shl_ln1118_1_fu_488_p3");
    sc_trace(mVcdFile, sext_ln1118_4_fu_496_p1, "sext_ln1118_4_fu_496_p1");
    sc_trace(mVcdFile, shl_ln1118_2_fu_506_p3, "shl_ln1118_2_fu_506_p3");
    sc_trace(mVcdFile, sub_ln1118_2_fu_500_p2, "sub_ln1118_2_fu_500_p2");
    sc_trace(mVcdFile, sext_ln1118_5_fu_514_p1, "sext_ln1118_5_fu_514_p1");
    sc_trace(mVcdFile, sub_ln1118_3_fu_518_p2, "sub_ln1118_3_fu_518_p2");
    sc_trace(mVcdFile, trunc_ln708_2_fu_524_p4, "trunc_ln708_2_fu_524_p4");
    sc_trace(mVcdFile, mul_ln1118_2_fu_167_p2, "mul_ln1118_2_fu_167_p2");
    sc_trace(mVcdFile, sext_ln1118_7_fu_553_p0, "sext_ln1118_7_fu_553_p0");
    sc_trace(mVcdFile, shl_ln1118_3_fu_557_p1, "shl_ln1118_3_fu_557_p1");
    sc_trace(mVcdFile, shl_ln1118_3_fu_557_p3, "shl_ln1118_3_fu_557_p3");
    sc_trace(mVcdFile, sext_ln1118_8_fu_565_p1, "sext_ln1118_8_fu_565_p1");
    sc_trace(mVcdFile, sub_ln1118_4_fu_569_p2, "sub_ln1118_4_fu_569_p2");
    sc_trace(mVcdFile, sext_ln1118_7_fu_553_p1, "sext_ln1118_7_fu_553_p1");
    sc_trace(mVcdFile, sub_ln1118_5_fu_575_p2, "sub_ln1118_5_fu_575_p2");
    sc_trace(mVcdFile, mul_ln1118_3_fu_164_p2, "mul_ln1118_3_fu_164_p2");
    sc_trace(mVcdFile, mul_ln1118_4_fu_168_p2, "mul_ln1118_4_fu_168_p2");
    sc_trace(mVcdFile, shl_ln1118_4_fu_621_p3, "shl_ln1118_4_fu_621_p3");
    sc_trace(mVcdFile, shl_ln1118_5_fu_633_p3, "shl_ln1118_5_fu_633_p3");
    sc_trace(mVcdFile, sext_ln1118_12_fu_641_p1, "sext_ln1118_12_fu_641_p1");
    sc_trace(mVcdFile, sext_ln1118_11_fu_629_p1, "sext_ln1118_11_fu_629_p1");
    sc_trace(mVcdFile, sub_ln1118_6_fu_645_p2, "sub_ln1118_6_fu_645_p2");
    sc_trace(mVcdFile, trunc_ln708_3_fu_651_p4, "trunc_ln708_3_fu_651_p4");
    sc_trace(mVcdFile, shl_ln1118_6_fu_665_p3, "shl_ln1118_6_fu_665_p3");
    sc_trace(mVcdFile, shl_ln1118_7_fu_677_p3, "shl_ln1118_7_fu_677_p3");
    sc_trace(mVcdFile, sext_ln1118_14_fu_685_p1, "sext_ln1118_14_fu_685_p1");
    sc_trace(mVcdFile, sext_ln1118_13_fu_673_p1, "sext_ln1118_13_fu_673_p1");
    sc_trace(mVcdFile, sub_ln1118_7_fu_689_p2, "sub_ln1118_7_fu_689_p2");
    sc_trace(mVcdFile, tmp_4_fu_695_p4, "tmp_4_fu_695_p4");
    sc_trace(mVcdFile, trunc_ln_fu_444_p4, "trunc_ln_fu_444_p4");
    sc_trace(mVcdFile, trunc_ln708_1_fu_459_p4, "trunc_ln708_1_fu_459_p4");
    sc_trace(mVcdFile, sext_ln708_1_fu_534_p1, "sext_ln708_1_fu_534_p1");
    sc_trace(mVcdFile, trunc_ln708_4_fu_543_p4, "trunc_ln708_4_fu_543_p4");
    sc_trace(mVcdFile, add_ln703_1_fu_715_p2, "add_ln703_1_fu_715_p2");
    sc_trace(mVcdFile, sext_ln708_fu_484_p1, "sext_ln708_fu_484_p1");
    sc_trace(mVcdFile, add_ln703_2_fu_721_p2, "add_ln703_2_fu_721_p2");
    sc_trace(mVcdFile, add_ln703_fu_709_p2, "add_ln703_fu_709_p2");
    sc_trace(mVcdFile, trunc_ln708_6_fu_596_p4, "trunc_ln708_6_fu_596_p4");
    sc_trace(mVcdFile, trunc_ln708_7_fu_611_p4, "trunc_ln708_7_fu_611_p4");
    sc_trace(mVcdFile, add_ln703_4_fu_733_p2, "add_ln703_4_fu_733_p2");
    sc_trace(mVcdFile, trunc_ln708_5_fu_581_p4, "trunc_ln708_5_fu_581_p4");
    sc_trace(mVcdFile, sext_ln101_fu_705_p1, "sext_ln101_fu_705_p1");
    sc_trace(mVcdFile, add_ln703_6_fu_745_p2, "add_ln703_6_fu_745_p2");
    sc_trace(mVcdFile, sext_ln703_fu_751_p1, "sext_ln703_fu_751_p1");
    sc_trace(mVcdFile, sext_ln708_2_fu_661_p1, "sext_ln708_2_fu_661_p1");
    sc_trace(mVcdFile, add_ln703_7_fu_755_p2, "add_ln703_7_fu_755_p2");
    sc_trace(mVcdFile, add_ln703_5_fu_739_p2, "add_ln703_5_fu_739_p2");
    sc_trace(mVcdFile, add_ln703_8_fu_761_p2, "add_ln703_8_fu_761_p2");
    sc_trace(mVcdFile, add_ln703_3_fu_727_p2, "add_ln703_3_fu_727_p2");
#endif

    }
}

dense_latency_ap_fixed_ap_fixed_config10_0_0::~dense_latency_ap_fixed_ap_fixed_config10_0_0() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

}

void dense_latency_ap_fixed_ap_fixed_config10_0_0::thread_add_ln703_1_fu_715_p2() {
    add_ln703_1_fu_715_p2 = (!sext_ln708_1_fu_534_p1.read().is_01() || !trunc_ln708_4_fu_543_p4.read().is_01())? sc_lv<16>(): (sc_bigint<16>(sext_ln708_1_fu_534_p1.read()) + sc_biguint<16>(trunc_ln708_4_fu_543_p4.read()));
}

void dense_latency_ap_fixed_ap_fixed_config10_0_0::thread_add_ln703_2_fu_721_p2() {
    add_ln703_2_fu_721_p2 = (!add_ln703_1_fu_715_p2.read().is_01() || !sext_ln708_fu_484_p1.read().is_01())? sc_lv<16>(): (sc_biguint<16>(add_ln703_1_fu_715_p2.read()) + sc_bigint<16>(sext_ln708_fu_484_p1.read()));
}

void dense_latency_ap_fixed_ap_fixed_config10_0_0::thread_add_ln703_3_fu_727_p2() {
    add_ln703_3_fu_727_p2 = (!add_ln703_2_fu_721_p2.read().is_01() || !add_ln703_fu_709_p2.read().is_01())? sc_lv<16>(): (sc_biguint<16>(add_ln703_2_fu_721_p2.read()) + sc_biguint<16>(add_ln703_fu_709_p2.read()));
}

void dense_latency_ap_fixed_ap_fixed_config10_0_0::thread_add_ln703_4_fu_733_p2() {
    add_ln703_4_fu_733_p2 = (!trunc_ln708_6_fu_596_p4.read().is_01() || !trunc_ln708_7_fu_611_p4.read().is_01())? sc_lv<16>(): (sc_biguint<16>(trunc_ln708_6_fu_596_p4.read()) + sc_biguint<16>(trunc_ln708_7_fu_611_p4.read()));
}

void dense_latency_ap_fixed_ap_fixed_config10_0_0::thread_add_ln703_5_fu_739_p2() {
    add_ln703_5_fu_739_p2 = (!add_ln703_4_fu_733_p2.read().is_01() || !trunc_ln708_5_fu_581_p4.read().is_01())? sc_lv<16>(): (sc_biguint<16>(add_ln703_4_fu_733_p2.read()) + sc_biguint<16>(trunc_ln708_5_fu_581_p4.read()));
}

void dense_latency_ap_fixed_ap_fixed_config10_0_0::thread_add_ln703_6_fu_745_p2() {
    add_ln703_6_fu_745_p2 = (!sext_ln101_fu_705_p1.read().is_01() || !ap_const_lv15_14.is_01())? sc_lv<15>(): (sc_bigint<15>(sext_ln101_fu_705_p1.read()) + sc_biguint<15>(ap_const_lv15_14));
}

void dense_latency_ap_fixed_ap_fixed_config10_0_0::thread_add_ln703_7_fu_755_p2() {
    add_ln703_7_fu_755_p2 = (!sext_ln703_fu_751_p1.read().is_01() || !sext_ln708_2_fu_661_p1.read().is_01())? sc_lv<16>(): (sc_bigint<16>(sext_ln703_fu_751_p1.read()) + sc_bigint<16>(sext_ln708_2_fu_661_p1.read()));
}

void dense_latency_ap_fixed_ap_fixed_config10_0_0::thread_add_ln703_8_fu_761_p2() {
    add_ln703_8_fu_761_p2 = (!add_ln703_7_fu_755_p2.read().is_01() || !add_ln703_5_fu_739_p2.read().is_01())? sc_lv<16>(): (sc_biguint<16>(add_ln703_7_fu_755_p2.read()) + sc_biguint<16>(add_ln703_5_fu_739_p2.read()));
}

void dense_latency_ap_fixed_ap_fixed_config10_0_0::thread_add_ln703_fu_709_p2() {
    add_ln703_fu_709_p2 = (!trunc_ln_fu_444_p4.read().is_01() || !trunc_ln708_1_fu_459_p4.read().is_01())? sc_lv<16>(): (sc_biguint<16>(trunc_ln_fu_444_p4.read()) + sc_biguint<16>(trunc_ln708_1_fu_459_p4.read()));
}

void dense_latency_ap_fixed_ap_fixed_config10_0_0::thread_ap_ready() {
    ap_ready = ap_const_logic_1;
}

void dense_latency_ap_fixed_ap_fixed_config10_0_0::thread_ap_return() {
    ap_return = (!add_ln703_8_fu_761_p2.read().is_01() || !add_ln703_3_fu_727_p2.read().is_01())? sc_lv<16>(): (sc_biguint<16>(add_ln703_8_fu_761_p2.read()) + sc_biguint<16>(add_ln703_3_fu_727_p2.read()));
}

void dense_latency_ap_fixed_ap_fixed_config10_0_0::thread_mul_ln1118_1_fu_171_p0() {
    mul_ln1118_1_fu_171_p0 = data_2_V_read.read();
}

void dense_latency_ap_fixed_ap_fixed_config10_0_0::thread_mul_ln1118_1_fu_171_p2() {
    mul_ln1118_1_fu_171_p2 = (!mul_ln1118_1_fu_171_p0.read().is_01() || !ap_const_lv23_7FFFCC.is_01())? sc_lv<23>(): sc_bigint<16>(mul_ln1118_1_fu_171_p0.read()) * sc_bigint<23>(ap_const_lv23_7FFFCC);
}

void dense_latency_ap_fixed_ap_fixed_config10_0_0::thread_mul_ln1118_2_fu_167_p0() {
    mul_ln1118_2_fu_167_p0 = data_4_V_read.read();
}

void dense_latency_ap_fixed_ap_fixed_config10_0_0::thread_mul_ln1118_2_fu_167_p2() {
    mul_ln1118_2_fu_167_p2 = (!mul_ln1118_2_fu_167_p0.read().is_01() || !ap_const_lv24_FFFF3E.is_01())? sc_lv<24>(): sc_bigint<16>(mul_ln1118_2_fu_167_p0.read()) * sc_bigint<24>(ap_const_lv24_FFFF3E);
}

void dense_latency_ap_fixed_ap_fixed_config10_0_0::thread_mul_ln1118_3_fu_164_p0() {
    mul_ln1118_3_fu_164_p0 = data_6_V_read.read();
}

void dense_latency_ap_fixed_ap_fixed_config10_0_0::thread_mul_ln1118_3_fu_164_p2() {
    mul_ln1118_3_fu_164_p2 = (!mul_ln1118_3_fu_164_p0.read().is_01() || !ap_const_lv24_A7.is_01())? sc_lv<24>(): sc_bigint<16>(mul_ln1118_3_fu_164_p0.read()) * sc_biguint<24>(ap_const_lv24_A7);
}

void dense_latency_ap_fixed_ap_fixed_config10_0_0::thread_mul_ln1118_4_fu_168_p0() {
    mul_ln1118_4_fu_168_p0 = data_7_V_read.read();
}

void dense_latency_ap_fixed_ap_fixed_config10_0_0::thread_mul_ln1118_4_fu_168_p2() {
    mul_ln1118_4_fu_168_p2 = (!mul_ln1118_4_fu_168_p0.read().is_01() || !ap_const_lv24_EB.is_01())? sc_lv<24>(): sc_bigint<16>(mul_ln1118_4_fu_168_p0.read()) * sc_biguint<24>(ap_const_lv24_EB);
}

void dense_latency_ap_fixed_ap_fixed_config10_0_0::thread_mul_ln1118_fu_162_p0() {
    mul_ln1118_fu_162_p0 = data_1_V_read.read();
}

void dense_latency_ap_fixed_ap_fixed_config10_0_0::thread_mul_ln1118_fu_162_p2() {
    mul_ln1118_fu_162_p2 = (!mul_ln1118_fu_162_p0.read().is_01() || !ap_const_lv24_47.is_01())? sc_lv<24>(): sc_bigint<16>(mul_ln1118_fu_162_p0.read()) * sc_biguint<24>(ap_const_lv24_47);
}

void dense_latency_ap_fixed_ap_fixed_config10_0_0::thread_sext_ln101_fu_705_p1() {
    sext_ln101_fu_705_p1 = esl_sext<15,14>(tmp_4_fu_695_p4.read());
}

void dense_latency_ap_fixed_ap_fixed_config10_0_0::thread_sext_ln1118_11_fu_629_p1() {
    sext_ln1118_11_fu_629_p1 = esl_sext<23,22>(shl_ln1118_4_fu_621_p3.read());
}

void dense_latency_ap_fixed_ap_fixed_config10_0_0::thread_sext_ln1118_12_fu_641_p1() {
    sext_ln1118_12_fu_641_p1 = esl_sext<23,19>(shl_ln1118_5_fu_633_p3.read());
}

void dense_latency_ap_fixed_ap_fixed_config10_0_0::thread_sext_ln1118_13_fu_673_p1() {
    sext_ln1118_13_fu_673_p1 = esl_sext<22,21>(shl_ln1118_6_fu_665_p3.read());
}

void dense_latency_ap_fixed_ap_fixed_config10_0_0::thread_sext_ln1118_14_fu_685_p1() {
    sext_ln1118_14_fu_685_p1 = esl_sext<22,18>(shl_ln1118_7_fu_677_p3.read());
}

void dense_latency_ap_fixed_ap_fixed_config10_0_0::thread_sext_ln1118_1_fu_434_p1() {
    sext_ln1118_1_fu_434_p1 = esl_sext<24,21>(shl_ln1118_s_fu_426_p3.read());
}

void dense_latency_ap_fixed_ap_fixed_config10_0_0::thread_sext_ln1118_4_fu_496_p1() {
    sext_ln1118_4_fu_496_p1 = esl_sext<23,22>(shl_ln1118_1_fu_488_p3.read());
}

void dense_latency_ap_fixed_ap_fixed_config10_0_0::thread_sext_ln1118_5_fu_514_p1() {
    sext_ln1118_5_fu_514_p1 = esl_sext<23,17>(shl_ln1118_2_fu_506_p3.read());
}

void dense_latency_ap_fixed_ap_fixed_config10_0_0::thread_sext_ln1118_7_fu_553_p0() {
    sext_ln1118_7_fu_553_p0 = data_5_V_read.read();
}

void dense_latency_ap_fixed_ap_fixed_config10_0_0::thread_sext_ln1118_7_fu_553_p1() {
    sext_ln1118_7_fu_553_p1 = esl_sext<24,16>(sext_ln1118_7_fu_553_p0.read());
}

void dense_latency_ap_fixed_ap_fixed_config10_0_0::thread_sext_ln1118_8_fu_565_p1() {
    sext_ln1118_8_fu_565_p1 = esl_sext<24,23>(shl_ln1118_3_fu_557_p3.read());
}

void dense_latency_ap_fixed_ap_fixed_config10_0_0::thread_sext_ln1118_fu_416_p1() {
    sext_ln1118_fu_416_p1 = esl_sext<24,23>(shl_ln_fu_408_p3.read());
}

void dense_latency_ap_fixed_ap_fixed_config10_0_0::thread_sext_ln703_fu_751_p1() {
    sext_ln703_fu_751_p1 = esl_sext<16,15>(add_ln703_6_fu_745_p2.read());
}

void dense_latency_ap_fixed_ap_fixed_config10_0_0::thread_sext_ln708_1_fu_534_p1() {
    sext_ln708_1_fu_534_p1 = esl_sext<16,15>(trunc_ln708_2_fu_524_p4.read());
}

void dense_latency_ap_fixed_ap_fixed_config10_0_0::thread_sext_ln708_2_fu_661_p1() {
    sext_ln708_2_fu_661_p1 = esl_sext<16,15>(trunc_ln708_3_fu_651_p4.read());
}

void dense_latency_ap_fixed_ap_fixed_config10_0_0::thread_sext_ln708_fu_484_p1() {
    sext_ln708_fu_484_p1 = esl_sext<16,15>(trunc_ln708_s_fu_474_p4.read());
}

void dense_latency_ap_fixed_ap_fixed_config10_0_0::thread_shl_ln1118_1_fu_488_p3() {
    shl_ln1118_1_fu_488_p3 = esl_concat<16,6>(data_3_V_read.read(), ap_const_lv6_0);
}

void dense_latency_ap_fixed_ap_fixed_config10_0_0::thread_shl_ln1118_2_fu_506_p3() {
    shl_ln1118_2_fu_506_p3 = esl_concat<16,1>(data_3_V_read.read(), ap_const_lv1_0);
}

void dense_latency_ap_fixed_ap_fixed_config10_0_0::thread_shl_ln1118_3_fu_557_p1() {
    shl_ln1118_3_fu_557_p1 = data_5_V_read.read();
}

void dense_latency_ap_fixed_ap_fixed_config10_0_0::thread_shl_ln1118_3_fu_557_p3() {
    shl_ln1118_3_fu_557_p3 = esl_concat<16,7>(shl_ln1118_3_fu_557_p1.read(), ap_const_lv7_0);
}

void dense_latency_ap_fixed_ap_fixed_config10_0_0::thread_shl_ln1118_4_fu_621_p3() {
    shl_ln1118_4_fu_621_p3 = esl_concat<16,6>(data_8_V_read.read(), ap_const_lv6_0);
}

void dense_latency_ap_fixed_ap_fixed_config10_0_0::thread_shl_ln1118_5_fu_633_p3() {
    shl_ln1118_5_fu_633_p3 = esl_concat<16,3>(data_8_V_read.read(), ap_const_lv3_0);
}

void dense_latency_ap_fixed_ap_fixed_config10_0_0::thread_shl_ln1118_6_fu_665_p3() {
    shl_ln1118_6_fu_665_p3 = esl_concat<16,5>(data_9_V_read.read(), ap_const_lv5_0);
}

void dense_latency_ap_fixed_ap_fixed_config10_0_0::thread_shl_ln1118_7_fu_677_p3() {
    shl_ln1118_7_fu_677_p3 = esl_concat<16,2>(data_9_V_read.read(), ap_const_lv2_0);
}

void dense_latency_ap_fixed_ap_fixed_config10_0_0::thread_shl_ln1118_s_fu_426_p3() {
    shl_ln1118_s_fu_426_p3 = esl_concat<16,5>(data_0_V_read.read(), ap_const_lv5_0);
}

void dense_latency_ap_fixed_ap_fixed_config10_0_0::thread_shl_ln_fu_408_p3() {
    shl_ln_fu_408_p3 = esl_concat<16,7>(data_0_V_read.read(), ap_const_lv7_0);
}

void dense_latency_ap_fixed_ap_fixed_config10_0_0::thread_sub_ln1118_1_fu_438_p2() {
    sub_ln1118_1_fu_438_p2 = (!sub_ln1118_fu_420_p2.read().is_01() || !sext_ln1118_1_fu_434_p1.read().is_01())? sc_lv<24>(): (sc_biguint<24>(sub_ln1118_fu_420_p2.read()) - sc_bigint<24>(sext_ln1118_1_fu_434_p1.read()));
}

void dense_latency_ap_fixed_ap_fixed_config10_0_0::thread_sub_ln1118_2_fu_500_p2() {
    sub_ln1118_2_fu_500_p2 = (!ap_const_lv23_0.is_01() || !sext_ln1118_4_fu_496_p1.read().is_01())? sc_lv<23>(): (sc_biguint<23>(ap_const_lv23_0) - sc_bigint<23>(sext_ln1118_4_fu_496_p1.read()));
}

void dense_latency_ap_fixed_ap_fixed_config10_0_0::thread_sub_ln1118_3_fu_518_p2() {
    sub_ln1118_3_fu_518_p2 = (!sub_ln1118_2_fu_500_p2.read().is_01() || !sext_ln1118_5_fu_514_p1.read().is_01())? sc_lv<23>(): (sc_biguint<23>(sub_ln1118_2_fu_500_p2.read()) - sc_bigint<23>(sext_ln1118_5_fu_514_p1.read()));
}

void dense_latency_ap_fixed_ap_fixed_config10_0_0::thread_sub_ln1118_4_fu_569_p2() {
    sub_ln1118_4_fu_569_p2 = (!ap_const_lv24_0.is_01() || !sext_ln1118_8_fu_565_p1.read().is_01())? sc_lv<24>(): (sc_biguint<24>(ap_const_lv24_0) - sc_bigint<24>(sext_ln1118_8_fu_565_p1.read()));
}

void dense_latency_ap_fixed_ap_fixed_config10_0_0::thread_sub_ln1118_5_fu_575_p2() {
    sub_ln1118_5_fu_575_p2 = (!sub_ln1118_4_fu_569_p2.read().is_01() || !sext_ln1118_7_fu_553_p1.read().is_01())? sc_lv<24>(): (sc_biguint<24>(sub_ln1118_4_fu_569_p2.read()) - sc_bigint<24>(sext_ln1118_7_fu_553_p1.read()));
}

void dense_latency_ap_fixed_ap_fixed_config10_0_0::thread_sub_ln1118_6_fu_645_p2() {
    sub_ln1118_6_fu_645_p2 = (!sext_ln1118_12_fu_641_p1.read().is_01() || !sext_ln1118_11_fu_629_p1.read().is_01())? sc_lv<23>(): (sc_bigint<23>(sext_ln1118_12_fu_641_p1.read()) - sc_bigint<23>(sext_ln1118_11_fu_629_p1.read()));
}

void dense_latency_ap_fixed_ap_fixed_config10_0_0::thread_sub_ln1118_7_fu_689_p2() {
    sub_ln1118_7_fu_689_p2 = (!sext_ln1118_14_fu_685_p1.read().is_01() || !sext_ln1118_13_fu_673_p1.read().is_01())? sc_lv<22>(): (sc_bigint<22>(sext_ln1118_14_fu_685_p1.read()) - sc_bigint<22>(sext_ln1118_13_fu_673_p1.read()));
}

void dense_latency_ap_fixed_ap_fixed_config10_0_0::thread_sub_ln1118_fu_420_p2() {
    sub_ln1118_fu_420_p2 = (!ap_const_lv24_0.is_01() || !sext_ln1118_fu_416_p1.read().is_01())? sc_lv<24>(): (sc_biguint<24>(ap_const_lv24_0) - sc_bigint<24>(sext_ln1118_fu_416_p1.read()));
}

void dense_latency_ap_fixed_ap_fixed_config10_0_0::thread_tmp_4_fu_695_p4() {
    tmp_4_fu_695_p4 = sub_ln1118_7_fu_689_p2.read().range(21, 8);
}

void dense_latency_ap_fixed_ap_fixed_config10_0_0::thread_trunc_ln708_1_fu_459_p4() {
    trunc_ln708_1_fu_459_p4 = mul_ln1118_fu_162_p2.read().range(23, 8);
}

void dense_latency_ap_fixed_ap_fixed_config10_0_0::thread_trunc_ln708_2_fu_524_p4() {
    trunc_ln708_2_fu_524_p4 = sub_ln1118_3_fu_518_p2.read().range(22, 8);
}

void dense_latency_ap_fixed_ap_fixed_config10_0_0::thread_trunc_ln708_3_fu_651_p4() {
    trunc_ln708_3_fu_651_p4 = sub_ln1118_6_fu_645_p2.read().range(22, 8);
}

void dense_latency_ap_fixed_ap_fixed_config10_0_0::thread_trunc_ln708_4_fu_543_p4() {
    trunc_ln708_4_fu_543_p4 = mul_ln1118_2_fu_167_p2.read().range(23, 8);
}

void dense_latency_ap_fixed_ap_fixed_config10_0_0::thread_trunc_ln708_5_fu_581_p4() {
    trunc_ln708_5_fu_581_p4 = sub_ln1118_5_fu_575_p2.read().range(23, 8);
}

void dense_latency_ap_fixed_ap_fixed_config10_0_0::thread_trunc_ln708_6_fu_596_p4() {
    trunc_ln708_6_fu_596_p4 = mul_ln1118_3_fu_164_p2.read().range(23, 8);
}

void dense_latency_ap_fixed_ap_fixed_config10_0_0::thread_trunc_ln708_7_fu_611_p4() {
    trunc_ln708_7_fu_611_p4 = mul_ln1118_4_fu_168_p2.read().range(23, 8);
}

void dense_latency_ap_fixed_ap_fixed_config10_0_0::thread_trunc_ln708_s_fu_474_p4() {
    trunc_ln708_s_fu_474_p4 = mul_ln1118_1_fu_171_p2.read().range(22, 8);
}

void dense_latency_ap_fixed_ap_fixed_config10_0_0::thread_trunc_ln_fu_444_p4() {
    trunc_ln_fu_444_p4 = sub_ln1118_1_fu_438_p2.read().range(23, 8);
}

}

